# Auto-generated by ../../../../tools/maven/maven-inputs2nix.sh
{}:

let
  repositories = {
    apache = "https://repo1.maven.org/maven2";
    clojars = "https://repo.clojars.org";
    fabric-io = "https://maven.fabric.io/public";
    google = "https://dl.google.com/dl/android/maven2";
    jcenter = "https://jcenter.bintray.com";
    maven = "https://repo1.maven.org/maven2";
  };

in {
  "https://dl.google.com/dl/android/maven2/com/android/databinding/baseLibrary/3.1.2/baseLibrary-3.1.2" = {
    host = repositories.google;
    path = "com/android/databinding/baseLibrary/3.1.2/baseLibrary-3.1.2";
    type = "jar";
    pom = {
      sha1 = "d437cc61f659075791b9c2085d506da5d96e9f93";
      sha256 = "182z8iiydz9vz39692ggbvhfkkqsp6sm54grp2kan74c17v3y4zn";
    };
    jar = {
      sha1 = "1b6a1add6a577708b62737dc31c479549f77750d";
      sha256 = "1phr1ilfmp0l5hz8zb08bxpscavcjfpzs3qjvd19fq0qrniwvnm6";
    };
  };
  "https://dl.google.com/dl/android/maven2/com/android/databinding/compilerCommon/3.1.2/compilerCommon-3.1.2" = {
    host = repositories.google;
    path = "com/android/databinding/compilerCommon/3.1.2/compilerCommon-3.1.2";
    type = "jar";
    pom = {
      sha1 = "953cedf2fc80b431ab55a5253de3c6dd4bd15d31";
      sha256 = "1dd101hfsmx4d4a2k1jm01j7h16kfci13wyrs2snvwijvyc4jkzb";
    };
    jar = {
      sha1 = "be65c11ded4242932046f23ecfa5c7ccb0e98f46";
      sha256 = "11xqq8ckjsyvjcyw9xmlwv3yxx2lsmz724y3vnh3k23yv31r7krf";
    };
  };
  "https://dl.google.com/dl/android/maven2/com/android/tools/analytics-library/protos/26.1.2/protos-26.1.2" = {
    host = repositories.google;
    path = "com/android/tools/analytics-library/protos/26.1.2/protos-26.1.2";
    type = "jar";
    pom = {
      sha1 = "409ad1605df8bbaeeee7c5a16a730e3b2afb8fed";
      sha256 = "0si4bldygjl6p89smkwy5ngas8hg9wxvvr9x3sj63kijlp2g5im1";
    };
    jar = {
      sha1 = "ba53bcde9703b2bf9871128952dce844c5d743fa";
      sha256 = "1fydllfnmhfkhl89z6qjbphw0ipbd185sly3xima0wmm885jlrsj";
    };
  };
  "https://dl.google.com/dl/android/maven2/com/android/tools/analytics-library/shared/26.1.2/shared-26.1.2" = {
    host = repositories.google;
    path = "com/android/tools/analytics-library/shared/26.1.2/shared-26.1.2";
    type = "jar";
    pom = {
      sha1 = "a95fff98355e8332bc65dd3975227633ae3d321c";
      sha256 = "1s3bqr4jdsz45m415kp4azh4j4cgsmp1a0gkhkal2s7ssfwd0miw";
    };
    jar = {
      sha1 = "bc21fe64fdaa64e59672e7d546d373f430e7557c";
      sha256 = "1sg8z5sidb9izs7f6wpv865jk8xax03wfa1np3p7zy6633d0wzjw";
    };
  };
  "https://dl.google.com/dl/android/maven2/com/android/tools/analytics-library/tracker/26.1.2/tracker-26.1.2" = {
    host = repositories.google;
    path = "com/android/tools/analytics-library/tracker/26.1.2/tracker-26.1.2";
    type = "jar";
    pom = {
      sha1 = "612666eeaa539158bbe51ce08d095ed91d100fc0";
      sha256 = "0f447iz6d6qa4jy5n5bc5qa5njr51mnbwh4i9jxcyfjg46vkzp19";
    };
    jar = {
      sha1 = "2d2260da92e50ac072f89d60a596d03aab3a8757";
      sha256 = "10j2vybdplxq8bffs88xyq43l5dyv5wnl738z03gnkzlmnh7my86";
    };
  };
  "https://dl.google.com/dl/android/maven2/com/android/tools/annotations/26.1.2/annotations-26.1.2" = {
    host = repositories.google;
    path = "com/android/tools/annotations/26.1.2/annotations-26.1.2";
    type = "jar";
    pom = {
      sha1 = "b41b94af82d6d3852c666ecbd9b13708525ba603";
      sha256 = "0khk0ijs5xa4j8ny5svz7bx4hidh3z691qp85xra29l95xwii3yy";
    };
    jar = {
      sha1 = "4f4e0ee71b9ccaa4a70cc86e40fb84ada2ed99a3";
      sha256 = "0640j9wr7kwgp2md32jzrjrh12lanzqng11wis1cmk64yp53sxvj";
    };
  };
  "https://dl.google.com/dl/android/maven2/com/android/tools/build/aapt2-proto/0.1.0/aapt2-proto-0.1.0" = {
    host = repositories.google;
    path = "com/android/tools/build/aapt2-proto/0.1.0/aapt2-proto-0.1.0";
    type = "jar";
    pom = {
      sha1 = "d3492c6cfb99d5d556cf4840c2efd63493ce2ac1";
      sha256 = "1h9vlambl1k51nx86qm0yfyavpf9qfrh7gja1q3qsqj10jinb8kc";
    };
    jar = {
      sha1 = "d1eb93a21a8d3590c3bfac574a8b6dffb2dbd21c";
      sha256 = "1x69zbk977hyc97hpc3bxmh19yiiq3hkl3hadjmwps08z4g13990";
    };
  };
  "https://dl.google.com/dl/android/maven2/com/android/tools/build/apksig/3.1.2/apksig-3.1.2" = {
    host = repositories.google;
    path = "com/android/tools/build/apksig/3.1.2/apksig-3.1.2";
    type = "jar";
    pom = {
      sha1 = "7a4c0447afdb81e966777ff38b59fbb53aaf858f";
      sha256 = "0jszfw0p511w1r43pw3kksj0lsny7dkv2jv6a38znp2w5mv718nf";
    };
    jar = {
      sha1 = "5af360dd30015a9a47c8ab0af0e6b05f64760edc";
      sha256 = "1gm88k34ldqqgnf5d793b64d8ng0xrbqh81xhxbisk8jb52nlsa0";
    };
  };
  "https://dl.google.com/dl/android/maven2/com/android/tools/build/builder/3.1.2/builder-3.1.2" = {
    host = repositories.google;
    path = "com/android/tools/build/builder/3.1.2/builder-3.1.2";
    type = "jar";
    pom = {
      sha1 = "9af1e21fcc76771b4b496644f1e705dee333a128";
      sha256 = "0rss89rjhym8zjnpkq7w59hbfb1lamx23xhwbxflgiiknbdcn3q4";
    };
    jar = {
      sha1 = "133b1f665104f0ebf01f71b61e4794385d7b5f1b";
      sha256 = "050xxf61i0b8sd4909qqnz5gxvyrydcwgyqr6r1yivz289d843xn";
    };
  };
  "https://dl.google.com/dl/android/maven2/com/android/tools/build/builder-model/3.1.2/builder-model-3.1.2" = {
    host = repositories.google;
    path = "com/android/tools/build/builder-model/3.1.2/builder-model-3.1.2";
    type = "jar";
    pom = {
      sha1 = "c70ad9deca2118a91fd2b69e6b265a03fec2770b";
      sha256 = "1qsz27kq3licd7x6y0haxz940q3lyx54qi0smr8hm2kfh56pin79";
    };
    jar = {
      sha1 = "4504b655fa8fe72302020ca9a2387f3f23fbfb57";
      sha256 = "05sf2cx8pbhx7pcx3hklf0n5i8fg6qh3993srav655aw2cmgm6yl";
    };
  };
  "https://dl.google.com/dl/android/maven2/com/android/tools/build/builder-test-api/3.1.2/builder-test-api-3.1.2" = {
    host = repositories.google;
    path = "com/android/tools/build/builder-test-api/3.1.2/builder-test-api-3.1.2";
    type = "jar";
    pom = {
      sha1 = "049c180ef7f85cd5cf748e9a67e734127564b809";
      sha256 = "1r3frklphcqg9whyazwrqcgjbnq849vj5vlcyhbjxhcdz734xc9x";
    };
    jar = {
      sha1 = "ffb00b786822df6538377a90df9f2d11c022efc3";
      sha256 = "17ry6qcwf40pslm4k6p88y3d30s29m1n440hi48v2h8dfh5sbqnz";
    };
  };
  "https://dl.google.com/dl/android/maven2/com/android/tools/build/bundletool/0.1.0-alpha01/bundletool-0.1.0-alpha01" = {
    host = repositories.google;
    path = "com/android/tools/build/bundletool/0.1.0-alpha01/bundletool-0.1.0-alpha01";
    type = "jar";
    pom = {
      sha1 = "834b735a36a399e2bb0276842ce97c55f6d6c072";
      sha256 = "1271sgv8jxdgsf60chx8yjc0jsfs38xd2jhdmdv8d8h4iwrpcrvc";
    };
    jar = {
      sha1 = "f7c303e37818223bd98566fcbea29aa0964c4d06";
      sha256 = "05bgc6sh1cz4l8mbw6jyx78pq275szq011z5cgpjdkdbpzq5dnrv";
    };
  };
  "https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.1.2/gradle-3.1.2" = {
    host = repositories.google;
    path = "com/android/tools/build/gradle/3.1.2/gradle-3.1.2";
    type = "jar";
    pom = {
      sha1 = "01cce0dda7c8c4f7e8301c00d4b56d05725b8ded";
      sha256 = "06nvcyk06zzl37iif8v42818pafxl668902gz2d536ff9dak09sj";
    };
    jar = {
      sha1 = "1608fa49add4d13366db7844998c6e59711f7e2a";
      sha256 = "05g93qf2ws4jmwd1p2jfscza1lmcgbkc2zv2lklhnz0v8g3hq3bd";
    };
  };
  "https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle-api/3.1.2/gradle-api-3.1.2" = {
    host = repositories.google;
    path = "com/android/tools/build/gradle-api/3.1.2/gradle-api-3.1.2";
    type = "jar";
    pom = {
      sha1 = "ae30f82e2d47067846bcbe6c5e8de6469772b96f";
      sha256 = "1aw93l3hdpbxmsyg8q3flvpgrbxckkf45c6j4al15yifrnwb3k9x";
    };
    jar = {
      sha1 = "427e25639a55911cadcf70657c9b2ded2ad6af2b";
      sha256 = "14s8glsya8bd2767z7as80mj1kmw9nfgi3jw1ymq6i9yi5dwr2z5";
    };
  };
  "https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle-core/3.1.2/gradle-core-3.1.2" = {
    host = repositories.google;
    path = "com/android/tools/build/gradle-core/3.1.2/gradle-core-3.1.2";
    type = "jar";
    pom = {
      sha1 = "453bfb98ea56c19ac9bc20281fb357dcd9c5d3ea";
      sha256 = "14wwbj3c9g8jkg0mjrbcqqzj80xhz7h0g4pcwkxjbcx6jl3n0d8s";
    };
    jar = {
      sha1 = "ccab33656c1baa6514d88f4d9356db19d0e9823b";
      sha256 = "09fd4m3v28yk6cwc40jd7aky06bv4cz114rfmmchbzdzjnvzcywc";
    };
  };
  "https://dl.google.com/dl/android/maven2/com/android/tools/build/manifest-merger/26.1.2/manifest-merger-26.1.2" = {
    host = repositories.google;
    path = "com/android/tools/build/manifest-merger/26.1.2/manifest-merger-26.1.2";
    type = "jar";
    pom = {
      sha1 = "b1956b22f18c2a81eccaad9df55f0e3ca381af6d";
      sha256 = "1lwzlhgm49yl8vgm74qi7masb2xqinzj4nmz459aly0dng82wli4";
    };
    jar = {
      sha1 = "79f398427650c76f0c66c89f10e4886a1fe68c26";
      sha256 = "0709xdkvgcnn15jasvxfwzbz966k2q9cyjlmgc876r96lmzc4qcw";
    };
  };
  "https://dl.google.com/dl/android/maven2/com/android/tools/build/transform-api/2.0.0-deprecated-use-gradle-api/transform-api-2.0.0-deprecated-use-gradle-api" = {
    host = repositories.google;
    path = "com/android/tools/build/transform-api/2.0.0-deprecated-use-gradle-api/transform-api-2.0.0-deprecated-use-gradle-api";
    type = "jar";
    pom = {
      sha1 = "7d636f89a401a7603740ef05ac87f5a1e2811efe";
      sha256 = "0xc5zmf6125cpdb4144mblznjs16q4k5z4jpjbbs3g4ads2z6qkw";
    };
    jar = {
      sha1 = "47f6c56527c42425742fa9b56ffd3fd80763fe03";
      sha256 = "0h2p4b7900j3girbkayq6b92pfw283rqnn74p4nlqlqwbv8a7r2d";
    };
  };
  "https://dl.google.com/dl/android/maven2/com/android/tools/common/26.1.2/common-26.1.2" = {
    host = repositories.google;
    path = "com/android/tools/common/26.1.2/common-26.1.2";
    type = "jar";
    pom = {
      sha1 = "c1e48d703812ff923e6e3357ea669c5f1e34f9e9";
      sha256 = "1qb8561nzalbh0c5i4a8d6hv327kb0l97i9hzw675fki1sllxadv";
    };
    jar = {
      sha1 = "c31bbd68c51ed0ef3b8d7cdd5615acf762473887";
      sha256 = "1rl8wxslw5gyg42sn0pgcayhiv159mf71fwn314w9jvxq7q20hza";
    };
  };
  "https://dl.google.com/dl/android/maven2/com/android/tools/ddms/ddmlib/26.1.2/ddmlib-26.1.2" = {
    host = repositories.google;
    path = "com/android/tools/ddms/ddmlib/26.1.2/ddmlib-26.1.2";
    type = "jar";
    pom = {
      sha1 = "5b2d7985bdf81122f014b6e90764cb03191cf5f8";
      sha256 = "0v6n0y0saf0fykwbjlkmyi84ygg9gj4c37awg3j714m6dzcif8j4";
    };
    jar = {
      sha1 = "1d423e621fb5c89fed13e41d0ed026cf5d8d7e7b";
      sha256 = "0i2ch21bbr1nyyzmrgvph4jghp50xdcrwarws03jz21nxzxsb8hq";
    };
  };
  "https://dl.google.com/dl/android/maven2/com/android/tools/dvlib/26.1.2/dvlib-26.1.2" = {
    host = repositories.google;
    path = "com/android/tools/dvlib/26.1.2/dvlib-26.1.2";
    type = "jar";
    pom = {
      sha1 = "11e6834486703b1f8a343ee72ae8bf1644f48dc3";
      sha256 = "13kx9y9x8vw7lz4y9pb87h6h2vrgp79nnqxzqh9xid2kdd52h36q";
    };
    jar = {
      sha1 = "eb39925fee6e726468fc10344ec988c086301ed7";
      sha256 = "1sihc6a358j91crl6qlzvrmkjzjb1w7brdnyqjb5qnb6nr7sm1qi";
    };
  };
  "https://dl.google.com/dl/android/maven2/com/android/tools/layoutlib/layoutlib-api/26.1.2/layoutlib-api-26.1.2" = {
    host = repositories.google;
    path = "com/android/tools/layoutlib/layoutlib-api/26.1.2/layoutlib-api-26.1.2";
    type = "jar";
    pom = {
      sha1 = "e6d2f83c268fbdf7ba71eaf72bf88108bb807627";
      sha256 = "0mkcwz7hjknx6z7c8v393x38wyyr9k6w13gyyrsa9p7diybirbvy";
    };
    jar = {
      sha1 = "03697abf628d30042c1082ea846454dfd1e8da3e";
      sha256 = "0krbcvmyni9piwjl9asm1xy4a177cbwfyfqm53wrkmy7zhwh08i0";
    };
  };
  "https://dl.google.com/dl/android/maven2/com/android/tools/lint/lint-gradle-api/26.1.2/lint-gradle-api-26.1.2" = {
    host = repositories.google;
    path = "com/android/tools/lint/lint-gradle-api/26.1.2/lint-gradle-api-26.1.2";
    type = "jar";
    pom = {
      sha1 = "f68c47a57523ed87b225532b98f2dd2ece9552bb";
      sha256 = "0p1jnzg1k5cfh6g01x5d5ji9fz73x6lp8s2qlsajw6pxlvy34q8v";
    };
    jar = {
      sha1 = "8c54aedfe9da66e64402de04883cee083c127a3b";
      sha256 = "141xy21m3gwanz35yci4afwgp141dyrrw72ijiffbhq3icm4ya3i";
    };
  };
  "https://dl.google.com/dl/android/maven2/com/android/tools/repository/26.1.2/repository-26.1.2" = {
    host = repositories.google;
    path = "com/android/tools/repository/26.1.2/repository-26.1.2";
    type = "jar";
    pom = {
      sha1 = "80f0348bd2be42cd50b982abfc80b44e9fdac92f";
      sha256 = "0y5f5yjq40grjzkzkav2c63z901wfyqlbcnsby93n22x59sqmm3l";
    };
    jar = {
      sha1 = "c8209ccb8ee0e5e3f293fd71d2a827f440ab811c";
      sha256 = "06p00r3g3yis2z5mxmnlwvy5w7r75gzfwlclk1vbsckdml9fb1lb";
    };
  };
  "https://dl.google.com/dl/android/maven2/com/android/tools/sdk-common/26.1.2/sdk-common-26.1.2" = {
    host = repositories.google;
    path = "com/android/tools/sdk-common/26.1.2/sdk-common-26.1.2";
    type = "jar";
    pom = {
      sha1 = "ea8f4a3a8e52f03ee5fa7bfc20dbfd81a0ba22d8";
      sha256 = "0qr8zzvs7vlv1c4519xmsfpy675ngjwb1ccdf2d3hdzy1p1npc53";
    };
    jar = {
      sha1 = "02cf773af3fb0e1bbd56a80fc6903a9d2a40a248";
      sha256 = "15hq4p7cg7n3jv33q5axh3b8jdq1wdlh5h8ybg5ws88alqh4fn13";
    };
  };
  "https://dl.google.com/dl/android/maven2/com/android/tools/sdklib/26.1.2/sdklib-26.1.2" = {
    host = repositories.google;
    path = "com/android/tools/sdklib/26.1.2/sdklib-26.1.2";
    type = "jar";
    pom = {
      sha1 = "b92a891817072eeb1c0971aace71f2d77a8d29e5";
      sha256 = "1wb42y65i5b03szgb52281s54b616ymwa9ip2fmj6v8zfc0vhsh4";
    };
    jar = {
      sha1 = "094697a9dff499b64b6e101bedb89a89825150af";
      sha256 = "0kmzlmr74gc5x037ndsqbgnci6g21vs4k5iz1nkyzf4sqnphz1yk";
    };
  };
  "https://jcenter.bintray.com/com/google/auto/auto-parent/3/auto-parent-3" = {
    host = repositories.jcenter;
    path = "com/google/auto/auto-parent/3/auto-parent-3";
    type = "jar";
    pom = {
      sha1 = "8e22bd67b5aeb5f03fd50efd5910ba6dfb7f4c86";
      sha256 = "1a78xc2zm7ixc1499amka8i6kq0cqm0f123kq894glngg04ip3y9";
    };
  };
  "https://jcenter.bintray.com/com/google/auto/value/auto-value/1.5.2/auto-value-1.5.2" = {
    host = repositories.jcenter;
    path = "com/google/auto/value/auto-value/1.5.2/auto-value-1.5.2";
    type = "jar";
    pom = {
      sha1 = "e9ba039f98da8c1ea01ad9715befc4a6cf4fdc7c";
      sha256 = "13b8ghy1fmqbx8p688l87kspnr491d6b8yrsap0f1y0f192b27wh";
    };
    jar = {
      sha1 = "1b94ab7ec707e2220a0d1a7517488d1843236345";
      sha256 = "1kzlnzsb15n1fb1z446426cscqll0gnqqwvnmbsbjfcv8chr9b3c";
    };
  };
  "https://jcenter.bintray.com/com/google/code/findbugs/jsr305/1.3.9/jsr305-1.3.9" = {
    host = repositories.jcenter;
    path = "com/google/code/findbugs/jsr305/1.3.9/jsr305-1.3.9";
    type = "jar";
    pom = {
      sha1 = "67ea333a3244bc20a17d6f0c29498071dfa409fc";
      sha256 = "0fm9gfc8ris3mq3zp06ra8fks3f8mxj60vdnybp7lg8w668r3azy";
    };
    jar = {
      sha1 = "40719ea6961c0cb6afaeb6a921eaa1f6afd4cfdf";
      sha256 = "1vf98qdxy0l4v1f0mvqxz92ydrd29vpyczmv999q22m9xsh22mwh";
    };
  };
  "https://jcenter.bintray.com/com/google/code/gson/gson/2.7/gson-2.7" = {
    host = repositories.jcenter;
    path = "com/google/code/gson/gson/2.7/gson-2.7";
    type = "jar";
    pom = {
      sha1 = "09f9e39f9b791aeb73ba428ad30872f1a703edb3";
      sha256 = "1phf2qksjf75ykwgp39189jdbqsn5zrmi07g8h522yxq0zn3cfbj";
    };
    jar = {
      sha1 = "751f548c85fa49f330cecbb1875893f971b33c4e";
      sha256 = "0clda1xrjfja969xsbrhc61ip588xvsi9k054kpd4cz1m5gfnhrd";
    };
  };
  "https://jcenter.bintray.com/com/google/code/gson/gson-parent/2.7/gson-parent-2.7" = {
    host = repositories.jcenter;
    path = "com/google/code/gson/gson-parent/2.7/gson-parent-2.7";
    type = "jar";
    pom = {
      sha1 = "3e147803ee87007ec82a1f625a0034be35c9b8a8";
      sha256 = "0ar7wk4zrdlb56jywsk6v3cpji8cjsi3kzmcr061yc12fdrqq7l7";
    };
  };
  "https://jcenter.bintray.com/com/googlecode/json-simple/json-simple/1.1/json-simple-1.1" = {
    host = repositories.jcenter;
    path = "com/googlecode/json-simple/json-simple/1.1/json-simple-1.1";
    type = "jar";
    pom = {
      sha1 = "a2c3a73d894b86ac979b88be6537b284eb4bf916";
      sha256 = "1avxrxknd1xy8ahq67rrkh8jlkb5hwsciljzvdvd9v8gzbh9pa27";
    };
    jar = {
      sha1 = "5e303a03d04e6788dddfa3655272580ae0fc13bb";
      sha256 = "0fb49wk04rl324qclzb1cpp715vjzijr8iwsgzs0ixs9qvs8951d";
    };
  };
  "https://jcenter.bintray.com/com/googlecode/juniversalchardet/juniversalchardet/1.0.3/juniversalchardet-1.0.3" = {
    host = repositories.jcenter;
    path = "com/googlecode/juniversalchardet/juniversalchardet/1.0.3/juniversalchardet-1.0.3";
    type = "jar";
    pom = {
      sha1 = "be6da8320adedafc712d645ddaaad00357b55408";
      sha256 = "0sq85z68pcf87j9vcis5garlxl325lz0q01skcm69kf76ndkjikq";
    };
    jar = {
      sha1 = "cd49678784c46aa8789c060538e0154013bb421b";
      sha256 = "0xjakmvlyl4i2lwb1prc19vx0mbbgpb6rhlxwx8vdf4kc68gwyvm";
    };
  };
  "https://jcenter.bintray.com/com/google/errorprone/error_prone_annotations/2.1.2/error_prone_annotations-2.1.2" = {
    host = repositories.jcenter;
    path = "com/google/errorprone/error_prone_annotations/2.1.2/error_prone_annotations-2.1.2";
    type = "jar";
    pom = {
      sha1 = "44f5d3b9781c31822991ff9f948d6cbfb8cdf055";
      sha256 = "04894gp1inj1cpgp68cjh0rzpv0svfzhv2spak2prvdlp25mh2hq";
    };
    jar = {
      sha1 = "6dcc08f90f678ac33e5ef78c3c752b6f59e63e0c";
      sha256 = "0akq6zj7fd6i0abyz5c0q5aikp7lldrbind4lbvn0q60blxqfg6y";
    };
  };
  "https://jcenter.bintray.com/com/google/errorprone/error_prone_parent/2.1.2/error_prone_parent-2.1.2" = {
    host = repositories.jcenter;
    path = "com/google/errorprone/error_prone_parent/2.1.2/error_prone_parent-2.1.2";
    type = "jar";
    pom = {
      sha1 = "ae2dd256d508d2ffc9d77fbec0414ee695973a8a";
      sha256 = "0hx1cf07n7kwcl2pwiab628fm8fmymgy7bwdkvr3nswgvcfxddn6";
    };
  };
  "https://jcenter.bintray.com/com/google/google/1/google-1" = {
    host = repositories.jcenter;
    path = "com/google/google/1/google-1";
    type = "jar";
    pom = {
      sha1 = "c35a5268151b7a1bbb77f7ee94a950f00e32db61";
      sha256 = "10by4ybrjnl8zwfg4ca74d0gcl4p9l7dzlfb9iwxw7m325xb2vfd";
    };
  };
  "https://jcenter.bintray.com/com/google/guava/guava/22.0/guava-22.0" = {
    host = repositories.jcenter;
    path = "com/google/guava/guava/22.0/guava-22.0";
    type = "jar";
    pom = {
      sha1 = "b87878db57d5cfc2ca7d3972cc8f7486bf02fbca";
      sha256 = "0cxzz1aq5wprdhag9vkfqyb160slpgw2jsvdcvhnvpb51ysb7bdz";
    };
    jar = {
      sha1 = "3564ef3803de51fb0530a8377ec6100b33b0d073";
      sha256 = "17jpmgwz19jq9b4jr45ishihsk513m5apd7hfc44inp4gm6fjn0i";
    };
  };
  "https://jcenter.bintray.com/com/google/guava/guava-parent/22.0/guava-parent-22.0" = {
    host = repositories.jcenter;
    path = "com/google/guava/guava-parent/22.0/guava-parent-22.0";
    type = "jar";
    pom = {
      sha1 = "52822d0abaa6bc42a26ea0d26a83abad05d938a8";
      sha256 = "0f8m410r12g9y34szyhbk5l8qf9n0pvzpnqflx81qz4pw6193bqy";
    };
  };
  "https://jcenter.bintray.com/com/google/j2objc/j2objc-annotations/1.1/j2objc-annotations-1.1" = {
    host = repositories.jcenter;
    path = "com/google/j2objc/j2objc-annotations/1.1/j2objc-annotations-1.1";
    type = "jar";
    pom = {
      sha1 = "b964a9414771661bdf35a3f10692a2fb0dd2c866";
      sha256 = "1gnn7b80krv19qjd9hhacahffqq9iwqgmw4ds56wp9wk3rbqrjgh";
    };
    jar = {
      sha1 = "ed28ded51a8b1c6b112568def5f4b455e6809019";
      sha256 = "1xpcvmnw2y3fa56hhk8dmknrq8afr6r3kdmzsg9hnwgjg3msg519";
    };
  };
  "https://jcenter.bintray.com/com/google/jimfs/jimfs/1.1/jimfs-1.1" = {
    host = repositories.jcenter;
    path = "com/google/jimfs/jimfs/1.1/jimfs-1.1";
    type = "jar";
    pom = {
      sha1 = "380866e1e495f899631b6e1d437e4b0a69e4faa3";
      sha256 = "0i3sgapm9r7wgmrm0qlb2hzarm6q6irfbjnz5x3ppw92v5f6xa7g";
    };
    jar = {
      sha1 = "8fbd0579dc68aba6186935cc1bee21d2f3e7ec1c";
      sha256 = "1pbx4lf1y24bgdfaf9bw9p0abnm7mlxhnlc7jfpk1af0swl8x0n4";
    };
  };
  "https://jcenter.bintray.com/com/google/jimfs/jimfs-parent/1.1/jimfs-parent-1.1" = {
    host = repositories.jcenter;
    path = "com/google/jimfs/jimfs-parent/1.1/jimfs-parent-1.1";
    type = "jar";
    pom = {
      sha1 = "2283f99a6aa73205190a20cfd35078e9f7d6cec9";
      sha256 = "1g96idyskcl3ryfc3fd5lq12ay5f4nbars3h528yzq2p3rsma5f7";
    };
  };
  "https://jcenter.bintray.com/com/google/protobuf/protobuf-java/3.4.0/protobuf-java-3.4.0" = {
    host = repositories.jcenter;
    path = "com/google/protobuf/protobuf-java/3.4.0/protobuf-java-3.4.0";
    type = "jar";
    pom = {
      sha1 = "100272b91d96ed5b41df4bb11ba543140c36bd30";
      sha256 = "01llqnrfxa04q1ndnrcvsg0j3vs2rva3101w79da38azdjl7pwc3";
    };
    jar = {
      sha1 = "b32aba0cbe737a4ca953f71688725972e3ee927c";
      sha256 = "194hchg28sckqycfg4c3cm41bdxcm3rsy36sk08insj569mydryw";
    };
  };
  "https://jcenter.bintray.com/com/google/protobuf/protobuf-java-util/3.4.0/protobuf-java-util-3.4.0" = {
    host = repositories.jcenter;
    path = "com/google/protobuf/protobuf-java-util/3.4.0/protobuf-java-util-3.4.0";
    type = "jar";
    pom = {
      sha1 = "72b93eb17c1d5337ec0f4497313a14b315b9e76c";
      sha256 = "1f1wvrr4lpp0mrbf3l5r3gcfbpxznvhnm8x4faxfm87awxrk1i49";
    };
    jar = {
      sha1 = "96aba8ab71c16018c6adf66771ce15c6491bc0fe";
      sha256 = "0ll0lslidkl0hp78yf48y4a7b8swqyylzckh1wrz4p5ibazf12a1";
    };
  };
  "https://jcenter.bintray.com/com/google/protobuf/protobuf-parent/3.4.0/protobuf-parent-3.4.0" = {
    host = repositories.jcenter;
    path = "com/google/protobuf/protobuf-parent/3.4.0/protobuf-parent-3.4.0";
    type = "jar";
    pom = {
      sha1 = "5d9f2b22310a535c4597b4ed3691e000221b3a17";
      sha256 = "0irsayf19snivcmhyr6122d5mvyb8cd677bn9ixfph2251arr414";
    };
  };
  "https://jcenter.bintray.com/commons-codec/commons-codec/1.6/commons-codec-1.6" = {
    host = repositories.jcenter;
    path = "commons-codec/commons-codec/1.6/commons-codec-1.6";
    type = "jar";
    pom = {
      sha1 = "9499f0c87ab43a74c456b9847acbcb5e67fe9f32";
      sha256 = "1298qykf61rrg2p3jnschq659ycqwkryp528v49vi9pkzz9kavm0";
    };
    jar = {
      sha1 = "b7f0fc8f61ecadeb3695f0b9464755eee44374d4";
      sha256 = "11ix43vckkj5mbv9ccnv4vf745s8sgpkdms07syi854f3fa4xcsl";
    };
  };
  "https://jcenter.bintray.com/commons-io/commons-io/2.4/commons-io-2.4" = {
    host = repositories.jcenter;
    path = "commons-io/commons-io/2.4/commons-io-2.4";
    type = "jar";
    pom = {
      sha1 = "9ece23effe8bce3904f3797a76b1ba6ab681e1b9";
      sha256 = "1wiikf78kr9k4pk68hb9jb9whrv19w8ir2kgxckad3wrrx3dvddj";
    };
    jar = {
      sha1 = "b1b6ea3b7e4aa4f492509a4952029cd8e48019ad";
      sha256 = "108mw2v8ncig29kjvzh8wi76plr01f4x5l3b1929xk5a7vf42snc";
    };
  };
  "https://jcenter.bintray.com/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1" = {
    host = repositories.jcenter;
    path = "commons-logging/commons-logging/1.1.1/commons-logging-1.1.1";
    type = "jar";
    pom = {
      sha1 = "76672afb562b9e903674ad3a544cdf2092f1faa3";
      sha256 = "1s2yqfrwxa3xg0l2mkczh29gcii3xcjnb8lwvmxbk2sf0mny3wnh";
    };
    jar = {
      sha1 = "5043bfebc3db072ed80fbd362e7caf00e885d8ae";
      sha256 = "0brngjgq24kk2c5qxzp3k6dcrzy7bdfdd1h1symb638zmly92vyf";
    };
  };
  "https://jcenter.bintray.com/com/squareup/javapoet/1.8.0/javapoet-1.8.0" = {
    host = repositories.jcenter;
    path = "com/squareup/javapoet/1.8.0/javapoet-1.8.0";
    type = "jar";
    pom = {
      sha1 = "60f3a32fabfe6c4b7572d8e2d94010ea44af4843";
      sha256 = "0ixnvd7bd5cn3hm9h41y87cx29nr6minbxqqshn5nwwyy500yxmk";
    };
    jar = {
      sha1 = "e858dc62ef484048540d27d36f3ec2177a3fa9b1";
      sha256 = "12fpvxgkhy92cmnh3wkai9jgg2g5zg7i3yhhdwcjid3v0a98q44f";
    };
  };
  "https://jcenter.bintray.com/com/squareup/javawriter/2.5.0/javawriter-2.5.0" = {
    host = repositories.jcenter;
    path = "com/squareup/javawriter/2.5.0/javawriter-2.5.0";
    type = "jar";
    pom = {
      sha1 = "d932f2476f65ecd95dcd6fd8c568b3f466f6a482";
      sha256 = "1c57k79i2dcyjm63k8xjjr1ck3i0i4hkwsa7k72y1xbc27qxgaz1";
    };
    jar = {
      sha1 = "81241ff7078ef14f42ea2a8995fa09c096256e6b";
      sha256 = "1w4p04j3z05k7ihb69pid3j4h4q8k0ipksp7rz9rgam01vxhkyzw";
    };
  };
  "https://jcenter.bintray.com/com/sun/activation/all/1.2.0/all-1.2.0" = {
    host = repositories.jcenter;
    path = "com/sun/activation/all/1.2.0/all-1.2.0";
    type = "jar";
    pom = {
      sha1 = "9b1023e38195ea19d1a0ac79192d486da1904f97";
      sha256 = "1i62n3icq23pssrvvii30x9jx63wygg7ggppwh2a2ckmmkiii18x";
    };
  };
  "https://jcenter.bintray.com/com/sun/activation/javax.activation/1.2.0/javax.activation-1.2.0" = {
    host = repositories.jcenter;
    path = "com/sun/activation/javax.activation/1.2.0/javax.activation-1.2.0";
    type = "jar";
    pom = {
      sha1 = "bdb776ae9b888b7ad8f9f424b9e67837eae916c5";
      sha256 = "0piadm0mqh1p9747mzapw7kkvayphj1irvnvn006jk458plvcygq";
    };
    jar = {
      sha1 = "bf744c1e2776ed1de3c55c8dac1057ec331ef744";
      sha256 = "1km9if90zdgjzgc3rxqfj2s0p0as2xymgk3rwwhny1fpdjqh4cwr";
    };
  };
  "https://jcenter.bintray.com/com/sun/istack/istack-commons/2.21/istack-commons-2.21" = {
    host = repositories.jcenter;
    path = "com/sun/istack/istack-commons/2.21/istack-commons-2.21";
    type = "jar";
    pom = {
      sha1 = "125168cc27946f32374cef253dbe607486aa3919";
      sha256 = "1341mibhpgaibhvdq6xzdkxjw8bp434nakkbc212j5lvz1vi41y3";
    };
  };
  "https://jcenter.bintray.com/com/sun/istack/istack-commons-runtime/2.21/istack-commons-runtime-2.21" = {
    host = repositories.jcenter;
    path = "com/sun/istack/istack-commons-runtime/2.21/istack-commons-runtime-2.21";
    type = "jar";
    pom = {
      sha1 = "04c234cf684a202c5c9bb7f0a198ba97e958f8f4";
      sha256 = "073dc9605ak2zns72l3mac5ynnz5k8rkyzwsbxa51l5zbxxi7rzb";
    };
    jar = {
      sha1 = "c969d8f15c467f0ef7d7b04889afbe7b5d48e22f";
      sha256 = "1x2hm4dq75jg8cz4n1ac3b6gki6p5m0kk89d1qmg15bhh2h6fgn3";
    };
  };
  "https://jcenter.bintray.com/com/sun/xml/bind/jaxb-bom-ext/2.2.11/jaxb-bom-ext-2.2.11" = {
    host = repositories.jcenter;
    path = "com/sun/xml/bind/jaxb-bom-ext/2.2.11/jaxb-bom-ext-2.2.11";
    type = "jar";
    pom = {
      sha1 = "158223fd61f720cf172e1984147b62aa8f2bdf4e";
      sha256 = "1sav7gq6a54zvkb113qhff3zp435767n1r5276q95jr1vs9hcpmj";
    };
  };
  "https://jcenter.bintray.com/com/sun/xml/bind/mvn/jaxb-parent/2.2.11/jaxb-parent-2.2.11" = {
    host = repositories.jcenter;
    path = "com/sun/xml/bind/mvn/jaxb-parent/2.2.11/jaxb-parent-2.2.11";
    type = "jar";
    pom = {
      sha1 = "9496f6747e6d5ab5da869941dea4143969122b91";
      sha256 = "10041gr7ra0777sp4cyflhs5slpf6849lpv13dbpwm013iqinc5m";
    };
  };
  "https://jcenter.bintray.com/com/sun/xml/bind/mvn/jaxb-runtime-parent/2.2.11/jaxb-runtime-parent-2.2.11" = {
    host = repositories.jcenter;
    path = "com/sun/xml/bind/mvn/jaxb-runtime-parent/2.2.11/jaxb-runtime-parent-2.2.11";
    type = "jar";
    pom = {
      sha1 = "dd7834f63d08408fde8fbb58f1ea557bbb31d444";
      sha256 = "144fllvdhajj6fzzzi046vch28k7h5frm40y4lj7z9pdwjw8r491";
    };
  };
  "https://jcenter.bintray.com/com/sun/xml/bind/mvn/jaxb-txw-parent/2.2.11/jaxb-txw-parent-2.2.11" = {
    host = repositories.jcenter;
    path = "com/sun/xml/bind/mvn/jaxb-txw-parent/2.2.11/jaxb-txw-parent-2.2.11";
    type = "jar";
    pom = {
      sha1 = "3fdc8adc054c5418bd76858dce64350bb8655ac5";
      sha256 = "0b1nn9m3wwvklk1ap3nr295dj9fy1s4nhv05y5b3ngsxk9lqqfcs";
    };
  };
  "https://jcenter.bintray.com/com/sun/xml/fastinfoset/FastInfoset/1.2.13/FastInfoset-1.2.13" = {
    host = repositories.jcenter;
    path = "com/sun/xml/fastinfoset/FastInfoset/1.2.13/FastInfoset-1.2.13";
    type = "jar";
    pom = {
      sha1 = "bc1ac953addb710ec08dcca6465bb1f6fcfd7ee9";
      sha256 = "1lsm4vzj4n82la9bs72kvj4sgl8i2vvnjr9ym96mnjbxrw75wl5p";
    };
    jar = {
      sha1 = "098f56b9354e27bd2941cc5d461344e240ae51ae";
      sha256 = "0f70phr6cysnrsbfsbmd318h81nvy5dcadqs1cy87hpk16wpv9r7";
    };
  };
  "https://jcenter.bintray.com/com/sun/xml/fastinfoset/fastinfoset-project/1.2.13/fastinfoset-project-1.2.13" = {
    host = repositories.jcenter;
    path = "com/sun/xml/fastinfoset/fastinfoset-project/1.2.13/fastinfoset-project-1.2.13";
    type = "jar";
    pom = {
      sha1 = "db60407ed97748ffda8b69aee0dd10a82851640d";
      sha256 = "0qf2kzp2qx62a13a70sv82yjcylnizir3z9gghlf0rqhky4mf27x";
    };
  };
  "https://jcenter.bintray.com/it/unimi/dsi/fastutil/7.2.0/fastutil-7.2.0" = {
    host = repositories.jcenter;
    path = "it/unimi/dsi/fastutil/7.2.0/fastutil-7.2.0";
    type = "jar";
    pom = {
      sha1 = "e068a0be19991231f5020d2748e709325bb745f2";
      sha256 = "1xry05xcp4r1r0kk16idpf4b0bw9db1z5qwhx7p7add745ji2fwm";
    };
    jar = {
      sha1 = "5ad3a2bb04143f70aa0765fc29fc29571a7d6b34";
      sha256 = "072r9dp1605ixwh31kjh5ynihlln2nxgl2gbwvvl41kl8f021ykl";
    };
  };
  "https://jcenter.bintray.com/javax/xml/bind/jaxb-api/2.2.12-b140109.1041/jaxb-api-2.2.12-b140109.1041" = {
    host = repositories.jcenter;
    path = "javax/xml/bind/jaxb-api/2.2.12-b140109.1041/jaxb-api-2.2.12-b140109.1041";
    type = "jar";
    pom = {
      sha1 = "a400fbd62fa68fae267b5641c3e4bb740a0f7335";
      sha256 = "0nqm2szwfjfmb9dnvrisr145r492csjdwjq9kg2rhmmwv7cag4i0";
    };
    jar = {
      sha1 = "7ed0e0d01198614194d56dfb03d9d95aa311824c";
      sha256 = "1whi48cdrzjwp13hnpa9sg719gagiw0dvibl9b703zxmnzc0rrmm";
    };
  };
  "https://jcenter.bintray.com/net/java/jvnet-parent/1/jvnet-parent-1" = {
    host = repositories.jcenter;
    path = "net/java/jvnet-parent/1/jvnet-parent-1";
    type = "jar";
    pom = {
      sha1 = "b55a1b046dbe82acdee8edde7476eebcba1e57d8";
      sha256 = "1gv37n9aid7fdhwd0h4py024w8by56cchg3b4sg5vrk82a0l0518";
    };
  };
  "https://jcenter.bintray.com/net/java/jvnet-parent/3/jvnet-parent-3" = {
    host = repositories.jcenter;
    path = "net/java/jvnet-parent/3/jvnet-parent-3";
    type = "jar";
    pom = {
      sha1 = "f8f3be3e980551a39b5679411e171aeb6931aaec";
      sha256 = "0nj7958drckwf634cw9gmwgmdi302bya7bas16bbzp9rzag7ix9h";
    };
  };
  "https://jcenter.bintray.com/net/java/jvnet-parent/4/jvnet-parent-4" = {
    host = repositories.jcenter;
    path = "net/java/jvnet-parent/4/jvnet-parent-4";
    type = "jar";
    pom = {
      sha1 = "a80cde31667f91784a6c68a06b5c6a77418f7822";
      sha256 = "1fwgpdx4jznjhqspgzr040q932z06ad9p4zzr2bm4ja9amrra4s7";
    };
  };
  "https://jcenter.bintray.com/net/sf/jopt-simple/jopt-simple/4.9/jopt-simple-4.9" = {
    host = repositories.jcenter;
    path = "net/sf/jopt-simple/jopt-simple/4.9/jopt-simple-4.9";
    type = "jar";
    pom = {
      sha1 = "ea3cd0a93e4e8adc1cdadd544c9168bc5aa985a8";
      sha256 = "14lh0wb5jml18h2w45z0nibpa6xxkx6a4z9b9kq9hisbnbcf5xvs";
    };
    jar = {
      sha1 = "ee9e9eaa0a35360dcfeac129ff4923215fd65904";
      sha256 = "1xgjp8k4d258pab0p4zxz7n6x75m35lvh4vgnx6qcpsbjmp8bi96";
    };
  };
  "https://jcenter.bintray.com/net/sf/kxml/kxml2/2.3.0/kxml2-2.3.0" = {
    host = repositories.jcenter;
    path = "net/sf/kxml/kxml2/2.3.0/kxml2-2.3.0";
    type = "jar";
    pom = {
      sha1 = "8efa75f9cdc57687076b2125b1a098e6f42e737d";
      sha256 = "11d66hzaang99y3wkrqxzn2y2qgsg34jf3dvk5i9664m9rpn1kii";
    };
    jar = {
      sha1 = "ccbc77a5fd907ef863c29f3596c6f54ffa4e9442";
      sha256 = "1qixcdxqmw7ja9yhp0qw6g4y8jzjxwhk5igcwl6f3zd1g6gxsr7j";
    };
  };
  "https://jcenter.bintray.com/net/sf/proguard/proguard-base/5.3.3/proguard-base-5.3.3" = {
    host = repositories.jcenter;
    path = "net/sf/proguard/proguard-base/5.3.3/proguard-base-5.3.3";
    type = "jar";
    pom = {
      sha1 = "6216930869e6faab2954ce7075727f64c606f3a8";
      sha256 = "1jnr6zsxfimb8wglqlwa6rrdc3g3nqf1dyw0k2dq9cj0q4pgn7p5";
    };
    jar = {
      sha1 = "988b6b0636ce343d4962b3b37f6319dcc6e99a61";
      sha256 = "11nwdb9y84cghcx319nsjjf9m035s4s1184zrhzpvaxq2wvqhbhx";
    };
  };
  "https://jcenter.bintray.com/net/sf/proguard/proguard-gradle/5.3.3/proguard-gradle-5.3.3" = {
    host = repositories.jcenter;
    path = "net/sf/proguard/proguard-gradle/5.3.3/proguard-gradle-5.3.3";
    type = "jar";
    pom = {
      sha1 = "57a3eda3d39f004a8cfc724f1a98af89b91f79c2";
      sha256 = "03v9zm3ykfkyb5cs5ald07ph103fh68d5c33rv070r29p71dwszj";
    };
    jar = {
      sha1 = "ad23a0505f58d0dfc95bb1472decc397460406c9";
      sha256 = "0shhpsjfc5gam15jnv1hk718v5c7vi7dwdc3gvmnid6dc85kljzk";
    };
  };
  "https://jcenter.bintray.com/net/sf/proguard/proguard-parent/5.3.3/proguard-parent-5.3.3" = {
    host = repositories.jcenter;
    path = "net/sf/proguard/proguard-parent/5.3.3/proguard-parent-5.3.3";
    type = "jar";
    pom = {
      sha1 = "45c24fb869b3c809c0a1a00081fc353184c2472c";
      sha256 = "0mv0zbwyw8xa4mkc5kw69y5xqashkz9gp123akfvh9f6152l3202";
    };
  };
  "https://jcenter.bintray.com/org/antlr/antlr4/4.5.3/antlr4-4.5.3" = {
    host = repositories.jcenter;
    path = "org/antlr/antlr4/4.5.3/antlr4-4.5.3";
    type = "jar";
    pom = {
      sha1 = "9ecf07c69a057cb13cea8a153d242007f5cc8003";
      sha256 = "11334fj7p4yxfvqincdpn1fp4hp7vzqjrqaplxv2k9ysxqr4nkla";
    };
    jar = {
      sha1 = "f35db7e4b2446e4174ba6a73db7bd6b3e6bb5da1";
      sha256 = "1d2g3f5pyrabib54al6bwlqpfbkxd6limycnwrs5flfzrwwyfbd3";
    };
  };
  "https://jcenter.bintray.com/org/antlr/antlr4-master/4.5.3/antlr4-master-4.5.3" = {
    host = repositories.jcenter;
    path = "org/antlr/antlr4-master/4.5.3/antlr4-master-4.5.3";
    type = "jar";
    pom = {
      sha1 = "c7e4123f86c15b492adba2fc5377949c4ea43946";
      sha256 = "195jkdpq6v34aa1wd3hznlvzcch3x8s89wfgnvlrkm8awzapf620";
    };
  };
  "https://jcenter.bintray.com/org/apache/apache/13/apache-13" = {
    host = repositories.jcenter;
    path = "org/apache/apache/13/apache-13";
    type = "jar";
    pom = {
      sha1 = "15aff1faaec4963617f07dbe8e603f0adabc3a12";
      sha256 = "07c4yg52q1qiz2b982pcsiwf9ahmpil4jy7lpqvi5m0z6sq3slgz";
    };
  };
  "https://jcenter.bintray.com/org/apache/apache/16/apache-16" = {
    host = repositories.jcenter;
    path = "org/apache/apache/16/apache-16";
    type = "jar";
    pom = {
      sha1 = "8a90e31780e5cd0685ccaf25836c66e3b4e163b7";
      sha256 = "03m4fjgg98zcyjlsp64z21lyiszhwyg43ys7mabk1jynswpzz1cz";
    };
  };
  "https://jcenter.bintray.com/org/apache/apache/4/apache-4" = {
    host = repositories.jcenter;
    path = "org/apache/apache/4/apache-4";
    type = "jar";
    pom = {
      sha1 = "602b647986c1d24301bc3d70e5923696bc7f1401";
      sha256 = "152iri0kbrxir93w23b31045gpvh3g9rc37gxya27sx8dfi274wy";
    };
  };
  "https://jcenter.bintray.com/org/apache/apache/9/apache-9" = {
    host = repositories.jcenter;
    path = "org/apache/apache/9/apache-9";
    type = "jar";
    pom = {
      sha1 = "de55d73a30c7521f3d55e8141d360ffbdfd88caa";
      sha256 = "1p8qrz7swd6ylwfiv6x4kr3gip6sy2vca8xwydlxm3kwah5fcij9";
    };
  };
  "https://jcenter.bintray.com/org/apache/commons/commons-compress/1.12/commons-compress-1.12" = {
    host = repositories.jcenter;
    path = "org/apache/commons/commons-compress/1.12/commons-compress-1.12";
    type = "jar";
    pom = {
      sha1 = "d4ba952b054eef846e7255cc3ac6d4ca76ead72c";
      sha256 = "0fi1am0cs09axqn5lzzg9a07ksj12spbjs1945v5wl2ir1sdb1xp";
    };
    jar = {
      sha1 = "84caa68576e345eb5e7ae61a0e5a9229eb100d7b";
      sha256 = "1dn09ncg5ggxvr57m26kjp8dcwalmv45agcwmdy5n623ygx4459c";
    };
  };
  "https://jcenter.bintray.com/org/apache/commons/commons-parent/22/commons-parent-22" = {
    host = repositories.jcenter;
    path = "org/apache/commons/commons-parent/22/commons-parent-22";
    type = "jar";
    pom = {
      sha1 = "0e895fa7ed472b3b2081ef77e2d5ece78c139d54";
      sha256 = "1frwdic537d95l0ikgkvfpb4wjfjx2h5h211zysdsyhawdamx37v";
    };
  };
  "https://jcenter.bintray.com/org/apache/commons/commons-parent/25/commons-parent-25" = {
    host = repositories.jcenter;
    path = "org/apache/commons/commons-parent/25/commons-parent-25";
    type = "jar";
    pom = {
      sha1 = "67b84199ca4acf0d8fbc5256d90b80f746737e94";
      sha256 = "1flhjyg2b14ch0wvsbimqli7vmpxim8yg54h6xkni1rf8i8fcyj6";
    };
  };
  "https://jcenter.bintray.com/org/apache/commons/commons-parent/39/commons-parent-39" = {
    host = repositories.jcenter;
    path = "org/apache/commons/commons-parent/39/commons-parent-39";
    type = "jar";
    pom = {
      sha1 = "4bc32d3cda9f07814c548492af7bf19b21798d46";
      sha256 = "19qxlq7zcvf8cw2hyrcb5d6b9cbbd6ccwnahv2v3wp1al3hjgkc7";
    };
  };
  "https://jcenter.bintray.com/org/apache/commons/commons-parent/5/commons-parent-5" = {
    host = repositories.jcenter;
    path = "org/apache/commons/commons-parent/5/commons-parent-5";
    type = "jar";
    pom = {
      sha1 = "a0a168281558e7ae972f113fa128bc46b4973edd";
      sha256 = "0am0vbkyp6b6srwhvw52xkc4ghaj4kqn0ay26vgag06z1g035mlb";
    };
  };
  "https://jcenter.bintray.com/org/apache/httpcomponents/httpclient/4.2.6/httpclient-4.2.6" = {
    host = repositories.jcenter;
    path = "org/apache/httpcomponents/httpclient/4.2.6/httpclient-4.2.6";
    type = "jar";
    pom = {
      sha1 = "fc51b4b649a2f9ab2588e9c1703288479591ade8";
      sha256 = "0a03lbcyjia7vavlvd4qbh29nzmvblnmdjiym1md63hhmbpa387m";
    };
    jar = {
      sha1 = "e4ca30a6a3a075053a61c6fc850d2432dc012ba7";
      sha256 = "0l2m2ijv8d5dwnmsghdjy7rxwzbka9xhf84y4whpwsbwxqj96bin";
    };
  };
  "https://jcenter.bintray.com/org/apache/httpcomponents/httpcomponents-client/4.1/httpcomponents-client-4.1" = {
    host = repositories.jcenter;
    path = "org/apache/httpcomponents/httpcomponents-client/4.1/httpcomponents-client-4.1";
    type = "jar";
    pom = {
      sha1 = "ac363bbcf41af1153745f561aa0feac2b373a017";
      sha256 = "09wq25fxxrsj8c01313w9f4wr95mpz9l4dnykjdqsv4cg54bc5aj";
    };
  };
  "https://jcenter.bintray.com/org/apache/httpcomponents/httpcomponents-client/4.2.6/httpcomponents-client-4.2.6" = {
    host = repositories.jcenter;
    path = "org/apache/httpcomponents/httpcomponents-client/4.2.6/httpcomponents-client-4.2.6";
    type = "jar";
    pom = {
      sha1 = "e40911efc7a573f049475a2beeaf83690bf5ad62";
      sha256 = "0s9d2yl36q2zyvkyhl7ksrlcc317hjl1ybvmpr6y2h12mwpgvdjj";
    };
  };
  "https://jcenter.bintray.com/org/apache/httpcomponents/httpcomponents-core/4.2.5/httpcomponents-core-4.2.5" = {
    host = repositories.jcenter;
    path = "org/apache/httpcomponents/httpcomponents-core/4.2.5/httpcomponents-core-4.2.5";
    type = "jar";
    pom = {
      sha1 = "1230a8404ed1cb3710ac59734fa2bcad69c166d9";
      sha256 = "1943dz9r27v4961ahq06f62xclsxjryxpy31r6xn6kisyaf7lkhn";
    };
  };
  "https://jcenter.bintray.com/org/apache/httpcomponents/httpcore/4.1/httpcore-4.1" = {
    host = repositories.jcenter;
    path = "org/apache/httpcomponents/httpcore/4.1/httpcore-4.1";
    type = "jar";
    pom = {
      sha1 = "28b423b7882a5c0d5b383903c6ea05d19b3c7c91";
      sha256 = "09vk7if9fwc6zsmr0912mgk57m23qwmmrx6ck6qgmjg973x6mj2g";
    };
    jar = {
      sha1 = "33fc26c02f8043ab0ede19eadc8c9885386b255c";
      sha256 = "1kr95c4q7w32yk81klyj2plgjhc5s2l5fh0qdn66c92f3zjqvqrw";
    };
  };
  "https://jcenter.bintray.com/org/apache/httpcomponents/httpcore/4.2.5/httpcore-4.2.5" = {
    host = repositories.jcenter;
    path = "org/apache/httpcomponents/httpcore/4.2.5/httpcore-4.2.5";
    type = "jar";
    pom = {
      sha1 = "cbae058677f9e1abfd9060223eb68224f96a7559";
      sha256 = "1ijb7yalv7c7vd7k1vix7zr08dcyqhspmm80ak5490rb6vqrksxn";
    };
    jar = {
      sha1 = "472f0f5f8dba5d1962cb9d7739feed739a31c30d";
      sha256 = "1sfgh7mcqnxnvpdwjzsyfci8bziffp0f6hzppcbxkj36rjj2vs75";
    };
  };
  "https://jcenter.bintray.com/org/apache/httpcomponents/httpmime/4.1/httpmime-4.1" = {
    host = repositories.jcenter;
    path = "org/apache/httpcomponents/httpmime/4.1/httpmime-4.1";
    type = "jar";
    pom = {
      sha1 = "a9e269c38cd5736d1db3a0e50adf87fafa8504a8";
      sha256 = "1lbkfv2qdkhsijfgswmn5gx15rs2hlz89wjk2rg6008hxidxjg6v";
    };
    jar = {
      sha1 = "9ba2dcdf94ce35c8a8e9bff242db0618ca932e92";
      sha256 = "1ahmkd6g4jw202ybwcsvs4z7ik9yph544fz4i9l4g2lf2ik9aqii";
    };
  };
  "https://jcenter.bintray.com/org/apache/httpcomponents/project/4.1.1/project-4.1.1" = {
    host = repositories.jcenter;
    path = "org/apache/httpcomponents/project/4.1.1/project-4.1.1";
    type = "jar";
    pom = {
      sha1 = "34c04480e3e97bccf10777c94651479b5ff55278";
      sha256 = "1v7qi1k2g9zbadaap6ln02p04hkika2nkbqigjik6kpmvx24vfr1";
    };
  };
  "https://jcenter.bintray.com/org/apache/httpcomponents/project/7/project-7" = {
    host = repositories.jcenter;
    path = "org/apache/httpcomponents/project/7/project-7";
    type = "jar";
    pom = {
      sha1 = "c486760d8e0eafe8d4932450e386c2805364f782";
      sha256 = "1hs8m8cgyypd6vb882zjyns58nhzrkm7cpbb0kg5i9amhm1blvix";
    };
  };
  "https://jcenter.bintray.com/org/bouncycastle/bcpkix-jdk15on/1.56/bcpkix-jdk15on-1.56" = {
    host = repositories.jcenter;
    path = "org/bouncycastle/bcpkix-jdk15on/1.56/bcpkix-jdk15on-1.56";
    type = "jar";
    pom = {
      sha1 = "2e2e47a19e0c53e7d204a6ad071c9e64c7c4c43f";
      sha256 = "0n82rzpyr0p0vvnkppma904zdfgby5wwfwycp4718wsa8zy6h5ij";
    };
    jar = {
      sha1 = "4648af70268b6fdb24674fb1fd7c1fcc73db1231";
      sha256 = "1jn60798vsqnp7l6fmkmbwy8kjqyxjqlavxkw29mw5z7x7jdwhvh";
    };
  };
  "https://jcenter.bintray.com/org/bouncycastle/bcprov-jdk15on/1.56/bcprov-jdk15on-1.56" = {
    host = repositories.jcenter;
    path = "org/bouncycastle/bcprov-jdk15on/1.56/bcprov-jdk15on-1.56";
    type = "jar";
    pom = {
      sha1 = "16220ab4e1b41786b0396e908ed91437c620ee3c";
      sha256 = "0vjw9dx654i469fb87jdjp08sy3xvs3qpi597ccp665hwwv37p4g";
    };
    jar = {
      sha1 = "a153c6f9744a3e9dd6feab5e210e1c9861362ec7";
      sha256 = "0jc3hy7p50iy626v2zl6vbfr3yi8vgf8v13xi6czp3w09zhiwgln";
    };
  };
  "https://jcenter.bintray.com/org/codehaus/codehaus-parent/4/codehaus-parent-4" = {
    host = repositories.jcenter;
    path = "org/codehaus/codehaus-parent/4/codehaus-parent-4";
    type = "jar";
    pom = {
      sha1 = "8b133202d50bec1e59bddc9392cb44d1fe5facc8";
      sha256 = "1pqlw2ilzagcl5ahq9dv60cxw59yrvrwf9q6z0679qf2x1yj71vb";
    };
  };
  "https://jcenter.bintray.com/org/codehaus/mojo/animal-sniffer-annotations/1.14/animal-sniffer-annotations-1.14" = {
    host = repositories.jcenter;
    path = "org/codehaus/mojo/animal-sniffer-annotations/1.14/animal-sniffer-annotations-1.14";
    type = "jar";
    pom = {
      sha1 = "99a56e3312f8ece1d457c8ca0a3c4b69d173d000";
      sha256 = "09ianw2880ch3x6xq5d2cz2b15ik6f4ndf8hb7ckw7lr0ndg2y8q";
    };
    jar = {
      sha1 = "775b7e22fb10026eed3f86e8dc556dfafe35f2d5";
      sha256 = "0pchd4360mim0f0a6vwr33szigihgvv4ic1scz1l9mxssq5k4s10";
    };
  };
  "https://jcenter.bintray.com/org/codehaus/mojo/animal-sniffer-parent/1.14/animal-sniffer-parent-1.14" = {
    host = repositories.jcenter;
    path = "org/codehaus/mojo/animal-sniffer-parent/1.14/animal-sniffer-parent-1.14";
    type = "jar";
    pom = {
      sha1 = "c1e91a9c2f36d9e6d3c7087242d8d9ec56052e5d";
      sha256 = "1skf65rbw52shb2akgs7xykn06lj1ggp23nbc94vs40ldfh505gm";
    };
  };
  "https://jcenter.bintray.com/org/codehaus/mojo/mojo-parent/34/mojo-parent-34" = {
    host = repositories.jcenter;
    path = "org/codehaus/mojo/mojo-parent/34/mojo-parent-34";
    type = "jar";
    pom = {
      sha1 = "803dc5cf36e504c5a48aa9a321f7fba1d6396733";
      sha256 = "171a71yz4np2h0nlkm9zx82q6f97wm66kj6afhvrmh23pipmsf9y";
    };
  };
  "https://jcenter.bintray.com/org/glassfish/jaxb/jaxb-bom/2.2.11/jaxb-bom-2.2.11" = {
    host = repositories.jcenter;
    path = "org/glassfish/jaxb/jaxb-bom/2.2.11/jaxb-bom-2.2.11";
    type = "jar";
    pom = {
      sha1 = "eed2bcd59f35f07507c553bbd7da20415cc7f63e";
      sha256 = "0f4d9p4vgidkq2v6s6gqkc5rpm5gz9fv5l2i59x9zp3hy186hbm5";
    };
  };
  "https://jcenter.bintray.com/org/glassfish/jaxb/jaxb-core/2.2.11/jaxb-core-2.2.11" = {
    host = repositories.jcenter;
    path = "org/glassfish/jaxb/jaxb-core/2.2.11/jaxb-core-2.2.11";
    type = "jar";
    pom = {
      sha1 = "f3208abdc61be827cf28838c3881213648807821";
      sha256 = "094v2z4ai9v6jnq4jwsb9mfqfvapq0g26nagafcvzjiv42gl0cgc";
    };
    jar = {
      sha1 = "f5745049f5fb9cb9d9b5f513c207727f475983e9";
      sha256 = "1amjhysjp6hbn6bccr2img6px5l63cigcnra6p464hxhxglaxg1p";
    };
  };
  "https://jcenter.bintray.com/org/glassfish/jaxb/jaxb-runtime/2.2.11/jaxb-runtime-2.2.11" = {
    host = repositories.jcenter;
    path = "org/glassfish/jaxb/jaxb-runtime/2.2.11/jaxb-runtime-2.2.11";
    type = "jar";
    pom = {
      sha1 = "6a1651361e4c2392aff30da0df648187f670f8cb";
      sha256 = "1am4rkx34dli4rxnyrpmgwgbkzl5vz6dadkqx51q3awmnlqpncp5";
    };
    jar = {
      sha1 = "0065510afc78679e347b0d774617a97fedac94f8";
      sha256 = "0w7d41amvf7jab7jmfjj3grahvcaq482s073dfaf5a7v3hsz4x58";
    };
  };
  "https://jcenter.bintray.com/org/glassfish/jaxb/txw2/2.2.11/txw2-2.2.11" = {
    host = repositories.jcenter;
    path = "org/glassfish/jaxb/txw2/2.2.11/txw2-2.2.11";
    type = "jar";
    pom = {
      sha1 = "4be03527dbf2428f7ea99fb9c2f50f089dffad5e";
      sha256 = "1n3b8233l5qa5l44866grbrs1l4vacp66ar7ryjmkjjg9drcn545";
    };
    jar = {
      sha1 = "2df047d8c187a62f2177bf6013f1f9786cdfc8a2";
      sha256 = "1smgbsxjcmfsahlskir0aa6sng656f32mk9034si2iassk53qai7";
    };
  };
  "https://jcenter.bintray.com/org/jetbrains/annotations/13.0/annotations-13.0" = {
    host = repositories.jcenter;
    path = "org/jetbrains/annotations/13.0/annotations-13.0";
    type = "jar";
    pom = {
      sha1 = "fa7d3d07cc80547e2d15bf4839d3267c637c642f";
      sha256 = "15y3p0xicxjx6y38pj39vm3q56xqnfhgf6yyplcrhdpzxlmynnln";
    };
    jar = {
      sha1 = "919f0dfe192fb4e063e7dacadee7f8bb9a2672a9";
      sha256 = "0y0l26ys36zlrsw98335a7wc1cl894zc1jjyj8sgvmg2r06s3qmc";
    };
  };
  "https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-reflect/1.2.0/kotlin-reflect-1.2.0" = {
    host = repositories.jcenter;
    path = "org/jetbrains/kotlin/kotlin-reflect/1.2.0/kotlin-reflect-1.2.0";
    type = "jar";
    pom = {
      sha1 = "2db5145a230bda2fc15d38707f202315efdf6a2f";
      sha256 = "1pdlcfjas68p8bvzcc0apjjx2b01swhn5mrm0zbf6sgd3gd1alpk";
    };
    jar = {
      sha1 = "4bbda3b5425aa38a9f6960468a29c5ef3e8a28c9";
      sha256 = "1pb9c3ri3f2yvl1rmhcdwpbjl0g4246n3bglag0dkr6np9rahj2g";
    };
  };
  "https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-stdlib/1.2.0/kotlin-stdlib-1.2.0" = {
    host = repositories.jcenter;
    path = "org/jetbrains/kotlin/kotlin-stdlib/1.2.0/kotlin-stdlib-1.2.0";
    type = "jar";
    pom = {
      sha1 = "3135147249f1ab93c33c5bce2bf952b4e8ebbba6";
      sha256 = "083s6ddd4a4j43h6b4awxh562zz4kmy2ajrq14dl5kgv9bd7i5ya";
    };
    jar = {
      sha1 = "25eb440d6eeb9fc60299121020fe726eb2100d03";
      sha256 = "1m7wxad6iw86a4fdvzx24ydr15d425r5z4m80c3r2h8bmksxkkq5";
    };
  };
  "https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-stdlib-jre7/1.2.0/kotlin-stdlib-jre7-1.2.0" = {
    host = repositories.jcenter;
    path = "org/jetbrains/kotlin/kotlin-stdlib-jre7/1.2.0/kotlin-stdlib-jre7-1.2.0";
    type = "jar";
    pom = {
      sha1 = "52d689e2aecf9c5ee2ca40c9512069ea77b4eb06";
      sha256 = "0j3ka2lfxqxb37dmx4nzm07q88a77yf5wf1mrqs7gayk49y42xr0";
    };
    jar = {
      sha1 = "ec8b969e26fbcf2265a4d1a1539c4d1d4c5af380";
      sha256 = "09i91z5r1ynll65sa6v61hqkz875q7vaz049zrx7jdyla6whz8n7";
    };
  };
  "https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-stdlib-jre8/1.2.0/kotlin-stdlib-jre8-1.2.0" = {
    host = repositories.jcenter;
    path = "org/jetbrains/kotlin/kotlin-stdlib-jre8/1.2.0/kotlin-stdlib-jre8-1.2.0";
    type = "jar";
    pom = {
      sha1 = "dd37e31bef41f48317214e93134ff54372bad406";
      sha256 = "0f5c4jjw8rs5jgyjb2d9j6h1nf5nqcj6aq61s7p5cw6546z78ykb";
    };
    jar = {
      sha1 = "505f55b9619bbc5f5e26c77427dd24a6a441eef1";
      sha256 = "0an8j2wwpx0mapmpl179xqf242kvjbipxaqxrgvl26ggwvp28db3";
    };
  };
  "https://jcenter.bintray.com/org/jvnet/staxex/stax-ex/1.7.7/stax-ex-1.7.7" = {
    host = repositories.jcenter;
    path = "org/jvnet/staxex/stax-ex/1.7.7/stax-ex-1.7.7";
    type = "jar";
    pom = {
      sha1 = "797e24598297af973b622e9a41662d0bbc497658";
      sha256 = "1b9yhymk6zp9sva68v0829xsrvsdz03rjlb2hfyh0yindh5lbjr7";
    };
    jar = {
      sha1 = "18bed5a0da27a6b43efe01282f2dc911b1cb3a72";
      sha256 = "1d1zh4ymilfc2shm51fcwb7c4i5f6nnmkvkzksqdxh33f7bzf7x3";
    };
  };
  "https://jcenter.bintray.com/org/ow2/asm/asm/5.1/asm-5.1" = {
    host = repositories.jcenter;
    path = "org/ow2/asm/asm/5.1/asm-5.1";
    type = "jar";
    pom = {
      sha1 = "87afb3c6d9329d889ef8dc7bded4a5482cb15e99";
      sha256 = "01dj1vq56rz9k9sdsczkfjajxkzmxqxlcs6cmjx27wrrpxd9n1vd";
    };
    jar = {
      sha1 = "5ef31c4fe953b1fd00b8a88fa1d6820e8785bb45";
      sha256 = "0m2bfr224dqpvk5cm0ih48n2516jg7x5d4kk4459zik7k6d3knnj";
    };
  };
  "https://jcenter.bintray.com/org/ow2/asm/asm-analysis/5.1/asm-analysis-5.1" = {
    host = repositories.jcenter;
    path = "org/ow2/asm/asm-analysis/5.1/asm-analysis-5.1";
    type = "jar";
    pom = {
      sha1 = "529d264690bf03a432e29ae546fdc960a176839c";
      sha256 = "16yma32h7zzniq7xi2v1yb7iy8xc5f6igqc9jw74y329sns0s4l1";
    };
    jar = {
      sha1 = "6d1bf8989fc7901f868bee3863c44f21aa63d110";
      sha256 = "1a8zpdmfbhlfn89g6i3r81k7npy25k1iq4r1xwz5fjyyqpsmhim3";
    };
  };
  "https://jcenter.bintray.com/org/ow2/asm/asm-commons/5.1/asm-commons-5.1" = {
    host = repositories.jcenter;
    path = "org/ow2/asm/asm-commons/5.1/asm-commons-5.1";
    type = "jar";
    pom = {
      sha1 = "99b522fe5920cdfddee2ce51053ba9b4ba2748ac";
      sha256 = "0l2psg8h5i04b8i4ji87z3hlbndxg9h01p9nm5azxx4m2hgv6dnd";
    };
    jar = {
      sha1 = "25d8a575034dd9cfcb375a39b5334f0ba9c8474e";
      sha256 = "1gl1976jbfxvy0v7pzdpyv0wpfrk1vsjn45dz3flprsm3xp7icwp";
    };
  };
  "https://jcenter.bintray.com/org/ow2/asm/asm-parent/5.1/asm-parent-5.1" = {
    host = repositories.jcenter;
    path = "org/ow2/asm/asm-parent/5.1/asm-parent-5.1";
    type = "jar";
    pom = {
      sha1 = "2768685ec9f3a387a328e4851c36716de2b34720";
      sha256 = "01qh2la7mkwyfx8gbz5n3p0j22490js12skycihkya7wz9c85v45";
    };
  };
  "https://jcenter.bintray.com/org/ow2/asm/asm-tree/5.1/asm-tree-5.1" = {
    host = repositories.jcenter;
    path = "org/ow2/asm/asm-tree/5.1/asm-tree-5.1";
    type = "jar";
    pom = {
      sha1 = "09e0a8798bb85ba11a36f21f2a0888bdd87d4ba4";
      sha256 = "088sg1xdmlfvv2f1g2w1px0i7y4p3lzj883gip7y7cm4gvy6jlzv";
    };
    jar = {
      sha1 = "87b38c12a0ea645791ead9d3e74ae5268d1d6c34";
      sha256 = "042cx29y8hsiri25a7swvp8pw1qxxpafq4wqclcp8adq9jy2ppn0";
    };
  };
  "https://jcenter.bintray.com/org/ow2/asm/asm-util/5.1/asm-util-5.1" = {
    host = repositories.jcenter;
    path = "org/ow2/asm/asm-util/5.1/asm-util-5.1";
    type = "jar";
    pom = {
      sha1 = "f5b08655a7056cdf8573524347706bae44f6707f";
      sha256 = "03i4sxdsws79pc9hva8rfigfbbr9rjwffssw3gbx2l62awc9s3hc";
    };
    jar = {
      sha1 = "b60e33a6bd0d71831e0c249816d01e6c1dd90a47";
      sha256 = "0h206v70i27sw0zf14ybwl9xd7jg2aiakfwg2jcx0g2ymqwjq0zf";
    };
  };
  "https://jcenter.bintray.com/org/ow2/ow2/1.3/ow2-1.3" = {
    host = repositories.jcenter;
    path = "org/ow2/ow2/1.3/ow2-1.3";
    type = "jar";
    pom = {
      sha1 = "f679d6639bfb209b0836a5e7cf09bfbcc1a41f06";
      sha256 = "1yr8hfx8gffpppa4ii6cvrsq029a6x8hzy7nsavxhs60s9kmq8ai";
    };
  };
  "https://jcenter.bintray.com/org/sonatype/oss/oss-parent/7/oss-parent-7" = {
    host = repositories.jcenter;
    path = "org/sonatype/oss/oss-parent/7/oss-parent-7";
    type = "jar";
    pom = {
      sha1 = "46b8a785b60a2767095b8611613b58577e96d4c9";
      sha256 = "0m4lallnlhyfj3z24ispxzwvsxzaznhw6zsmk4j74sibr5kqh7xm";
    };
  };
  "https://jcenter.bintray.com/org/sonatype/oss/oss-parent/9/oss-parent-9" = {
    host = repositories.jcenter;
    path = "org/sonatype/oss/oss-parent/9/oss-parent-9";
    type = "jar";
    pom = {
      sha1 = "e5cdc4d23b86d79c436f16fed20853284e868f65";
      sha256 = "0yl2hbwz2kn1hll1i00ddzn8f89bfdcjwdifz0pj2j15k1gjch7v";
    };
  };
  "https://maven.fabric.io/public/io/fabric/tools/gradle/1.25.4/gradle-1.25.4" = {
    host = repositories.fabric-io;
    path = "io/fabric/tools/gradle/1.25.4/gradle-1.25.4";
    type = "jar";
    pom = {
      sha1 = "85a74be37d7a790a05f8d31ea63dc341e04c6b75";
      sha256 = "08xr1zhb50n6n08hc0vbwxqjfsdhmxp0z0b5py39vmsa9vwq2rfw";
    };
    jar = {
      sha1 = "e1475d609b53783d837c84cc3ec0abcfb5c9a898";
      sha256 = "0xkfv4py1mpwvz4bc2zsi4vzz0g81n6zhgkpfxx9j0f429ndwpqs";
    };
  };
}
