# Auto-generated by ../../../../tools/maven/maven-inputs2nix.sh
{}:

let
  repositories = {
    apache = "https://repo1.maven.org/maven2";
    clojars = "https://repo.clojars.org";
    fabric-io = "https://maven.fabric.io/public";
    google = "https://dl.google.com/dl/android/maven2";
    jcenter = "https://jcenter.bintray.com";
    maven = "https://repo1.maven.org/maven2";
  };

in {
  "https://jcenter.bintray.com/com/android/tools/annotations/24.1.3/annotations-24.1.3" = {
    host = repositories.jcenter;
    path = "com/android/tools/annotations/24.1.3/annotations-24.1.3";
    type = "jar";
    pom = {
      sha1 = "96be923aa65cf1398c081aef3283f6316b7e7872";
      sha256 = "1dsivp9xz98lw6pfn7rgak7sbx39x12fsgs49yplfv2vcmbnr0ks";
    };
    jar = {
      sha1 = "50057fe6aa0834b11e35f9723414c793022b30e4";
      sha256 = "1a1plgmrrxykyb3b91ccqz9wkg3k01fs3rkwvsbdg8iaw90xsdy3";
    };
  };
  "https://jcenter.bintray.com/com/android/tools/build/builder/1.1.3/builder-1.1.3" = {
    host = repositories.jcenter;
    path = "com/android/tools/build/builder/1.1.3/builder-1.1.3";
    type = "jar";
    pom = {
      sha1 = "5106e4e65ebd5ffeadf245c4c41da76938cd24bf";
      sha256 = "1zk2hh69xsk9gx01lcbpvza0if83wx8y626g5xlwqp6fwzmisv56";
    };
    jar = {
      sha1 = "44e9cc678b260278b39349f7f13c305d68d17c8c";
      sha256 = "0kxdvscdyail6ykcp07hnd2sw5kikz4cq83vdafqqmycbh4wfkhl";
    };
  };
  "https://jcenter.bintray.com/com/android/tools/build/builder-model/1.1.3/builder-model-1.1.3" = {
    host = repositories.jcenter;
    path = "com/android/tools/build/builder-model/1.1.3/builder-model-1.1.3";
    type = "jar";
    pom = {
      sha1 = "77113aabbd852756ee84d5e4b84bdd828b150366";
      sha256 = "0c5vd5ca3v7d7rsbzijv5rh7ibv8sryfh8pdl46hzkr7r7321jsr";
    };
    jar = {
      sha1 = "1bff7ac9edd904720fde8a0a0978818e39a04e73";
      sha256 = "1pww8x60m0r8safpr6ncf4h0zyzx26dflxyx7h6zs5ahvls7vqwi";
    };
  };
  "https://jcenter.bintray.com/com/android/tools/build/builder-test-api/1.1.3/builder-test-api-1.1.3" = {
    host = repositories.jcenter;
    path = "com/android/tools/build/builder-test-api/1.1.3/builder-test-api-1.1.3";
    type = "jar";
    pom = {
      sha1 = "c5ac16a8a61af39c3f849314536187144e09c63d";
      sha256 = "1scfz6dw29imr2689f8bki3xa3q89q34npl2q1cakrgdkjx9vm64";
    };
    jar = {
      sha1 = "cd1aebe463d911774829a144a48c5b88f13513e0";
      sha256 = "1vi1sigcwkcx6hmi2ylprbj72fn6yh6jihwm4ks1c0chwpiwmyzc";
    };
  };
  "https://jcenter.bintray.com/com/android/tools/build/gradle/1.1.3/gradle-1.1.3" = {
    host = repositories.jcenter;
    path = "com/android/tools/build/gradle/1.1.3/gradle-1.1.3";
    type = "jar";
    pom = {
      sha1 = "4af09990348139fa57d4a3e92a2285544b0d4b7b";
      sha256 = "1yhrjnnm6mpqi76fknbc6f68n14ls8sc6gchnmx3hhacnhl29swm";
    };
    jar = {
      sha1 = "c6f66d30006cebbaf8c1c7f8675e955223bf64e6";
      sha256 = "1rpa2plnz2znkszgg77fsm7zmcjiv77kh95r1s8x9nynf5ys0am6";
    };
  };
  "https://jcenter.bintray.com/com/android/tools/build/gradle-core/1.1.3/gradle-core-1.1.3" = {
    host = repositories.jcenter;
    path = "com/android/tools/build/gradle-core/1.1.3/gradle-core-1.1.3";
    type = "jar";
    pom = {
      sha1 = "83d5be34609ab59c923f5b9fb70e52c1242335ad";
      sha256 = "1w14j2y6dvm8ak2rhz6lp9wnqbi14q095k9m39rw69gnp9p6nazz";
    };
    jar = {
      sha1 = "94d5817bc8d445c5b2cfd44e8035afb6879c1bae";
      sha256 = "0yd0bmpg5qx1zpmlcfna0fk52fmsrllrfm17ll06176qsbnl5dxj";
    };
  };
  "https://jcenter.bintray.com/com/android/tools/build/manifest-merger/24.1.3/manifest-merger-24.1.3" = {
    host = repositories.jcenter;
    path = "com/android/tools/build/manifest-merger/24.1.3/manifest-merger-24.1.3";
    type = "jar";
    pom = {
      sha1 = "d8c0c2eca527da981410a446c21a965c0e6ccb73";
      sha256 = "114rz6xnnb9h9zywabqs0pl57w968x9h6cxw84nyf1255mvay2af";
    };
    jar = {
      sha1 = "bceca436ab72301a3add739dbffb747ebb19ddc8";
      sha256 = "0by5zjrkaapg5cyzq8vv66pzfxnan524nh11l49vi4xakkajkh2l";
    };
  };
  "https://jcenter.bintray.com/com/android/tools/common/24.1.3/common-24.1.3" = {
    host = repositories.jcenter;
    path = "com/android/tools/common/24.1.3/common-24.1.3";
    type = "jar";
    pom = {
      sha1 = "c457b4538f57ec5de8303c1bc571086588263be8";
      sha256 = "1bxd8nnjzhkb8zakfil2sf8jmi8xshhhwyvyjbf814rw20223xdf";
    };
    jar = {
      sha1 = "84b5eaf800d08899fa7d3f7daf971a0d02ea80f0";
      sha256 = "0cdhgvmlwbrc233l4c9pzif3i8qhqgyhikm1zf055jiawrmb9nch";
    };
  };
  "https://jcenter.bintray.com/com/android/tools/ddms/ddmlib/24.1.3/ddmlib-24.1.3" = {
    host = repositories.jcenter;
    path = "com/android/tools/ddms/ddmlib/24.1.3/ddmlib-24.1.3";
    type = "jar";
    pom = {
      sha1 = "73deb8a552731dd29742446b61e6b9e1726e2f88";
      sha256 = "0c50xbjl0ygipmy2jpxla95ihr6kr4hq9f4dn62bb9s7wp2jn0la";
    };
    jar = {
      sha1 = "666d2e62661eccf89033ea1433e3a8f3622b5078";
      sha256 = "0vxq71zz8v32sgr3qpa2rg04ibg55wdbkhsib3q0ljbgnmiw4xlp";
    };
  };
  "https://jcenter.bintray.com/com/android/tools/dvlib/24.1.3/dvlib-24.1.3" = {
    host = repositories.jcenter;
    path = "com/android/tools/dvlib/24.1.3/dvlib-24.1.3";
    type = "jar";
    pom = {
      sha1 = "922082f0d944cd196d68003500a398d2446a563b";
      sha256 = "175lyn7gl84y47ix9igxi7llaywv60hqjji95k5w7v0snh6cqfsb";
    };
    jar = {
      sha1 = "637a1a657b190ee8abbbf2298f09ed6e90c3b8ef";
      sha256 = "1a8jib0h7l83vw2cd3akp4h4rnns3j0rw920x9sfd0r1zb1ya345";
    };
  };
  "https://jcenter.bintray.com/com/android/tools/external/lombok/lombok-ast/0.2.3/lombok-ast-0.2.3" = {
    host = repositories.jcenter;
    path = "com/android/tools/external/lombok/lombok-ast/0.2.3/lombok-ast-0.2.3";
    type = "jar";
    pom = {
      sha1 = "ac2e013f1621e1456de3ac77aeae0437237c736c";
      sha256 = "1gbljyqw5r2vc31dl1flclsvdias3049pdrc6dicizcbvph92qcc";
    };
    jar = {
      sha1 = "0528b6f8bde3157f17530aa366631f2aad2a6cf9";
      sha256 = "0vg8w757n8a8v6lafrg4xb9nl7dqw3x56p1qzfsp20j395p0vss5";
    };
  };
  "https://jcenter.bintray.com/com/android/tools/layoutlib/layoutlib-api/24.1.3/layoutlib-api-24.1.3" = {
    host = repositories.jcenter;
    path = "com/android/tools/layoutlib/layoutlib-api/24.1.3/layoutlib-api-24.1.3";
    type = "jar";
    pom = {
      sha1 = "349988c1cd90e600314c3187b0e3a908bcb91391";
      sha256 = "11pxp107dam6xcbam2garn2adb51lcr1yjvx8a79mlhy1mg44gbz";
    };
    jar = {
      sha1 = "2160ac4c4d9795cf8a8130149a2ea0557ba02283";
      sha256 = "1swfzjpbnrf0wqiakjpgym06ndjyig8wkv93crllfiiw21klxppg";
    };
  };
  "https://jcenter.bintray.com/com/android/tools/lint/lint/24.1.3/lint-24.1.3" = {
    host = repositories.jcenter;
    path = "com/android/tools/lint/lint/24.1.3/lint-24.1.3";
    type = "jar";
    pom = {
      sha1 = "2ce3cc74bd843616dda1d84a5bc7bfdc8fbae54f";
      sha256 = "1qbdmj9lq3pg93cwfg3fi6fbsrqvwirg7zvv4hdk5zfx755fqwas";
    };
    jar = {
      sha1 = "7f120107f7cce494650581e345070818713eb433";
      sha256 = "1rknkfg0vbl6wxdfkqhrqs42xhhwrkwsb5i9ng429l3bizkafv08";
    };
  };
  "https://jcenter.bintray.com/com/android/tools/lint/lint-api/24.1.3/lint-api-24.1.3" = {
    host = repositories.jcenter;
    path = "com/android/tools/lint/lint-api/24.1.3/lint-api-24.1.3";
    type = "jar";
    pom = {
      sha1 = "c741c76fb890f09637e77eec63bf550c6a9bcb00";
      sha256 = "1286shvlk9nd7wp9zbcxayaggd76x42r8lqjbbisnqbqa5q7l4gf";
    };
    jar = {
      sha1 = "0a75b3dfb9104e09fef100fce9feb18b7fe30c2e";
      sha256 = "18g2dq6q8dfzkcbxwkhjzzwgqx83ymdqvpw6rw34h85sq2q3yzwj";
    };
  };
  "https://jcenter.bintray.com/com/android/tools/lint/lint-checks/24.1.3/lint-checks-24.1.3" = {
    host = repositories.jcenter;
    path = "com/android/tools/lint/lint-checks/24.1.3/lint-checks-24.1.3";
    type = "jar";
    pom = {
      sha1 = "70d5799c43e94c5414434b36792f578f60013c73";
      sha256 = "0r10k23vsrscnmvc4w9rr3kcp3x0vsi5q7dvip2450jnbrwcyf0d";
    };
    jar = {
      sha1 = "077820b72a4390e2d640932106588de4dfa5ed67";
      sha256 = "0gaf3hm0bhjnbzqyy0i69l17a0d14qkgm2wy7j1qnwsffli6vk1a";
    };
  };
  "https://jcenter.bintray.com/com/android/tools/sdk-common/24.1.3/sdk-common-24.1.3" = {
    host = repositories.jcenter;
    path = "com/android/tools/sdk-common/24.1.3/sdk-common-24.1.3";
    type = "jar";
    pom = {
      sha1 = "4743b690b9c5358f254277bae367faed8be54221";
      sha256 = "0b3kcjwri58p9nibrmpahhg1l5wnc0b0zgmalfmn34cfszzhqq89";
    };
    jar = {
      sha1 = "318e9d8ea2bbf481096e409c366795a6302498e5";
      sha256 = "1m32bl87w7f34f8clfpzpv4q3d68km2bbv3fx0s26h2xkipl0610";
    };
  };
  "https://jcenter.bintray.com/com/android/tools/sdklib/24.1.3/sdklib-24.1.3" = {
    host = repositories.jcenter;
    path = "com/android/tools/sdklib/24.1.3/sdklib-24.1.3";
    type = "jar";
    pom = {
      sha1 = "69fbae0fdd5a847d8eeee0e2bcf0970dbc06438d";
      sha256 = "1zs3mfspi3lwvddpy43dx0nksml5sv5hrng68ha1b7wyc1kiffmb";
    };
    jar = {
      sha1 = "7b2e09d45db370f3219c3da2d2e82493bdb9069f";
      sha256 = "16dkz0ql5zfxhfhvcir8jyqhagsab4ivwcgdmllbr89h4m0h60wa";
    };
  };
  "https://jcenter.bintray.com/com/google/code/gson/gson/2.2.4/gson-2.2.4" = {
    host = repositories.jcenter;
    path = "com/google/code/gson/gson/2.2.4/gson-2.2.4";
    type = "jar";
    pom = {
      sha1 = "06252c690921ee1dc719594a5d4da1829194f8b3";
      sha256 = "106k9ynbhls8nkihxrhkj5033z7q2am6x1l98vffck4935flv65f";
    };
    jar = {
      sha1 = "a60a5e993c98c864010053cb901b7eab25306568";
      sha256 = "1yw7qszcw1dsh54q6wyksr5mbkz8mzs1q36hmjjn7qx9gk88qcn0";
    };
  };
  "https://jcenter.bintray.com/com/google/guava/guava/17.0/guava-17.0" = {
    host = repositories.jcenter;
    path = "com/google/guava/guava/17.0/guava-17.0";
    type = "jar";
    pom = {
      sha1 = "0f534dabee0b40b25715869c5e1287e38c7e1e4a";
      sha256 = "0nxpdkb27m770j0c4xlg7l34aj87h7qja7dbmqrcf99q1l0ic39a";
    };
    jar = {
      sha1 = "9c6ef172e8de35fd8d4d8783e4821e57cdef7445";
      sha256 = "1g7bhyvzsx61lrca01hvpivkdgjvgj1wy5qa0jwbdl0klq7ahdlc";
    };
  };
  "https://jcenter.bintray.com/com/google/guava/guava-parent/17.0/guava-parent-17.0" = {
    host = repositories.jcenter;
    path = "com/google/guava/guava-parent/17.0/guava-parent-17.0";
    type = "jar";
    pom = {
      sha1 = "f8ba48b925d1c925d0fc0379ffa14a06e44eb464";
      sha256 = "0ajka1xsh28sammy3zbx82mvxi3k19v5ks4x2xswglsiamc57flz";
    };
  };
  "https://jcenter.bintray.com/commons-codec/commons-codec/1.4/commons-codec-1.4" = {
    host = repositories.jcenter;
    path = "commons-codec/commons-codec/1.4/commons-codec-1.4";
    type = "jar";
    pom = {
      sha1 = "393db4ae967c6e831025d432632d1f72f7108b01";
      sha256 = "13s0k9nv1zbmppf5b5fwc4j0506cgm061rzcdgki780v89lh1wzm";
    };
    jar = {
      sha1 = "4216af16d38465bbab0f3dff8efa14204f7a399a";
      sha256 = "06v3ccc5srj9w2v459i5f5rc7j37b1a24n52a5bh78gkfi62793a";
    };
  };
  "https://jcenter.bintray.com/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1" = {
    host = repositories.jcenter;
    path = "commons-logging/commons-logging/1.1.1/commons-logging-1.1.1";
    type = "jar";
    pom = {
      sha1 = "76672afb562b9e903674ad3a544cdf2092f1faa3";
      sha256 = "1s2yqfrwxa3xg0l2mkczh29gcii3xcjnb8lwvmxbk2sf0mny3wnh";
    };
    jar = {
      sha1 = "5043bfebc3db072ed80fbd362e7caf00e885d8ae";
      sha256 = "0brngjgq24kk2c5qxzp3k6dcrzy7bdfdd1h1symb638zmly92vyf";
    };
  };
  "https://jcenter.bintray.com/com/squareup/javawriter/2.5.0/javawriter-2.5.0" = {
    host = repositories.jcenter;
    path = "com/squareup/javawriter/2.5.0/javawriter-2.5.0";
    type = "jar";
    pom = {
      sha1 = "d932f2476f65ecd95dcd6fd8c568b3f466f6a482";
      sha256 = "1c57k79i2dcyjm63k8xjjr1ck3i0i4hkwsa7k72y1xbc27qxgaz1";
    };
    jar = {
      sha1 = "81241ff7078ef14f42ea2a8995fa09c096256e6b";
      sha256 = "1w4p04j3z05k7ihb69pid3j4h4q8k0ipksp7rz9rgam01vxhkyzw";
    };
  };
  "https://jcenter.bintray.com/net/sf/kxml/kxml2/2.3.0/kxml2-2.3.0" = {
    host = repositories.jcenter;
    path = "net/sf/kxml/kxml2/2.3.0/kxml2-2.3.0";
    type = "jar";
    pom = {
      sha1 = "8efa75f9cdc57687076b2125b1a098e6f42e737d";
      sha256 = "11d66hzaang99y3wkrqxzn2y2qgsg34jf3dvk5i9664m9rpn1kii";
    };
    jar = {
      sha1 = "ccbc77a5fd907ef863c29f3596c6f54ffa4e9442";
      sha256 = "1qixcdxqmw7ja9yhp0qw6g4y8jzjxwhk5igcwl6f3zd1g6gxsr7j";
    };
  };
  "https://jcenter.bintray.com/net/sf/proguard/proguard-base/5.1/proguard-base-5.1" = {
    host = repositories.jcenter;
    path = "net/sf/proguard/proguard-base/5.1/proguard-base-5.1";
    type = "jar";
    pom = {
      sha1 = "a6348683c2a61ce93afd3715ce29075cdeb8b07e";
      sha256 = "01j9i5akzpdxm66s0b6s3fzwmf38dz9jvx40yyz4afb0hwa920hb";
    };
    jar = {
      sha1 = "dc606dd778fe4685be16d5a171782ccfe0ef5637";
      sha256 = "1cjmzwg2is2lm79ay4pmgb4qkij01sxjwq28kjysiys5wl6c3gpy";
    };
  };
  "https://jcenter.bintray.com/net/sf/proguard/proguard-gradle/5.1/proguard-gradle-5.1" = {
    host = repositories.jcenter;
    path = "net/sf/proguard/proguard-gradle/5.1/proguard-gradle-5.1";
    type = "jar";
    pom = {
      sha1 = "9e149e6d2dea6f6cb582b17d1c444a30bd3945be";
      sha256 = "0a1sz8idwsa3rasjhcfcxnj5wk60vmvimjs1g907gpcc92vn0aqm";
    };
    jar = {
      sha1 = "0672d43cbfde4765080e5bea19c51a2cc45dfc00";
      sha256 = "0yrqzqbxf9jhf04d2mmjsmcj7cac7bg53kgz95hzcs7xxyg7iymh";
    };
  };
  "https://jcenter.bintray.com/net/sf/proguard/proguard-parent/5.1/proguard-parent-5.1" = {
    host = repositories.jcenter;
    path = "net/sf/proguard/proguard-parent/5.1/proguard-parent-5.1";
    type = "jar";
    pom = {
      sha1 = "c65dbd15e3b2300d94ecdae09a6ad61611024ee7";
      sha256 = "1piwkby3x60jb4z1xkzsfs98h1yd5j313ci6i2ywrx2hkkd7v2ga";
    };
  };
  "https://jcenter.bintray.com/org/apache/apache/13/apache-13" = {
    host = repositories.jcenter;
    path = "org/apache/apache/13/apache-13";
    type = "jar";
    pom = {
      sha1 = "15aff1faaec4963617f07dbe8e603f0adabc3a12";
      sha256 = "07c4yg52q1qiz2b982pcsiwf9ahmpil4jy7lpqvi5m0z6sq3slgz";
    };
  };
  "https://jcenter.bintray.com/org/apache/apache/4/apache-4" = {
    host = repositories.jcenter;
    path = "org/apache/apache/4/apache-4";
    type = "jar";
    pom = {
      sha1 = "602b647986c1d24301bc3d70e5923696bc7f1401";
      sha256 = "152iri0kbrxir93w23b31045gpvh3g9rc37gxya27sx8dfi274wy";
    };
  };
  "https://jcenter.bintray.com/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1" = {
    host = repositories.jcenter;
    path = "org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1";
    type = "jar";
    pom = {
      sha1 = "2fb3ea9182911315ee79aa2fb4853c7bdd347407";
      sha256 = "1f4z7dc667b0d07s1yfiqhvbhbj37q00ihyxphm0nlp82kdpl4qh";
    };
    jar = {
      sha1 = "a698750c16740fd5b3871425f4cb3bbaa87f529d";
      sha256 = "1gbzd7aang7xp3k98m3sbjs5d7nm6yqigg8znrncqvpq0dji7jjz";
    };
  };
  "https://jcenter.bintray.com/org/apache/commons/commons-parent/11/commons-parent-11" = {
    host = repositories.jcenter;
    path = "org/apache/commons/commons-parent/11/commons-parent-11";
    type = "jar";
    pom = {
      sha1 = "3f29657e1e3d6856344728ddbcf696477e943d59";
      sha256 = "0am014qph77cw2n596d9z8g1naf5a191199zi9di0q1l75pk1q5r";
    };
  };
  "https://jcenter.bintray.com/org/apache/commons/commons-parent/33/commons-parent-33" = {
    host = repositories.jcenter;
    path = "org/apache/commons/commons-parent/33/commons-parent-33";
    type = "jar";
    pom = {
      sha1 = "a9bd6ae1e11cb313ec4a4c9bcd58c7a9ea60a5cd";
      sha256 = "1yzqvnngasa9bqqc0hw2yzqcckkmqzdcrbwx6xpi1rg2a89h3l2k";
    };
  };
  "https://jcenter.bintray.com/org/apache/commons/commons-parent/5/commons-parent-5" = {
    host = repositories.jcenter;
    path = "org/apache/commons/commons-parent/5/commons-parent-5";
    type = "jar";
    pom = {
      sha1 = "a0a168281558e7ae972f113fa128bc46b4973edd";
      sha256 = "0am0vbkyp6b6srwhvw52xkc4ghaj4kqn0ay26vgag06z1g035mlb";
    };
  };
  "https://jcenter.bintray.com/org/apache/httpcomponents/httpclient/4.1.1/httpclient-4.1.1" = {
    host = repositories.jcenter;
    path = "org/apache/httpcomponents/httpclient/4.1.1/httpclient-4.1.1";
    type = "jar";
    pom = {
      sha1 = "1468927fa5fbea4d3037422f45eb12cef173ba16";
      sha256 = "19z21zvaypyi1mg6vc3clmhmq6fq1ybng0pj0p7d95wa6kcigfmd";
    };
    jar = {
      sha1 = "3d1d918f32709e33ba7ddb2c4e8d1c543ebe713e";
      sha256 = "0la7iqy72w09h6z8h9s09bnac2xj0l05mm1ql5nbyyb6ib82drga";
    };
  };
  "https://jcenter.bintray.com/org/apache/httpcomponents/httpcomponents-client/4.1.1/httpcomponents-client-4.1.1" = {
    host = repositories.jcenter;
    path = "org/apache/httpcomponents/httpcomponents-client/4.1.1/httpcomponents-client-4.1.1";
    type = "jar";
    pom = {
      sha1 = "3e1c598ddde5619cc602d32fffdf34668be071a3";
      sha256 = "0lra0a51ir2x7ww44qq4hmcjvrrc843ll4qmfxz6sllmx7jq8lj7";
    };
  };
  "https://jcenter.bintray.com/org/apache/httpcomponents/httpcomponents-client/4.1/httpcomponents-client-4.1" = {
    host = repositories.jcenter;
    path = "org/apache/httpcomponents/httpcomponents-client/4.1/httpcomponents-client-4.1";
    type = "jar";
    pom = {
      sha1 = "ac363bbcf41af1153745f561aa0feac2b373a017";
      sha256 = "09wq25fxxrsj8c01313w9f4wr95mpz9l4dnykjdqsv4cg54bc5aj";
    };
  };
  "https://jcenter.bintray.com/org/apache/httpcomponents/httpcomponents-core/4.1/httpcomponents-core-4.1" = {
    host = repositories.jcenter;
    path = "org/apache/httpcomponents/httpcomponents-core/4.1/httpcomponents-core-4.1";
    type = "jar";
    pom = {
      sha1 = "166e36966c2cbd6c1867a6eded3f56d70958338c";
      sha256 = "1r2dyq3bgz1xamv3a167jd55in4z7vkd27zcvgh6s59xkkypyyag";
    };
  };
  "https://jcenter.bintray.com/org/apache/httpcomponents/httpcore/4.1/httpcore-4.1" = {
    host = repositories.jcenter;
    path = "org/apache/httpcomponents/httpcore/4.1/httpcore-4.1";
    type = "jar";
    pom = {
      sha1 = "28b423b7882a5c0d5b383903c6ea05d19b3c7c91";
      sha256 = "09vk7if9fwc6zsmr0912mgk57m23qwmmrx6ck6qgmjg973x6mj2g";
    };
    jar = {
      sha1 = "33fc26c02f8043ab0ede19eadc8c9885386b255c";
      sha256 = "1kr95c4q7w32yk81klyj2plgjhc5s2l5fh0qdn66c92f3zjqvqrw";
    };
  };
  "https://jcenter.bintray.com/org/apache/httpcomponents/httpmime/4.1/httpmime-4.1" = {
    host = repositories.jcenter;
    path = "org/apache/httpcomponents/httpmime/4.1/httpmime-4.1";
    type = "jar";
    pom = {
      sha1 = "a9e269c38cd5736d1db3a0e50adf87fafa8504a8";
      sha256 = "1lbkfv2qdkhsijfgswmn5gx15rs2hlz89wjk2rg6008hxidxjg6v";
    };
    jar = {
      sha1 = "9ba2dcdf94ce35c8a8e9bff242db0618ca932e92";
      sha256 = "1ahmkd6g4jw202ybwcsvs4z7ik9yph544fz4i9l4g2lf2ik9aqii";
    };
  };
  "https://jcenter.bintray.com/org/apache/httpcomponents/project/4.1.1/project-4.1.1" = {
    host = repositories.jcenter;
    path = "org/apache/httpcomponents/project/4.1.1/project-4.1.1";
    type = "jar";
    pom = {
      sha1 = "34c04480e3e97bccf10777c94651479b5ff55278";
      sha256 = "1v7qi1k2g9zbadaap6ln02p04hkika2nkbqigjik6kpmvx24vfr1";
    };
  };
  "https://jcenter.bintray.com/org/bouncycastle/bcpkix-jdk15on/1.48/bcpkix-jdk15on-1.48" = {
    host = repositories.jcenter;
    path = "org/bouncycastle/bcpkix-jdk15on/1.48/bcpkix-jdk15on-1.48";
    type = "jar";
    pom = {
      sha1 = "8fc7cecdba5ea3df0e29b659613dc21222a910fa";
      sha256 = "0z91vn29rq51r1p14kndr1p47kb7xc01smd1p2p44ba8mjdgyz5z";
    };
    jar = {
      sha1 = "28b7614b908a47844bb27e3c94b45b6893656265";
      sha256 = "0dxss10nkpwyg5w1hyp5yd1vrk8m9p2id2x1d1wxgap5nhv36isk";
    };
  };
  "https://jcenter.bintray.com/org/bouncycastle/bcprov-jdk15on/1.48/bcprov-jdk15on-1.48" = {
    host = repositories.jcenter;
    path = "org/bouncycastle/bcprov-jdk15on/1.48/bcprov-jdk15on-1.48";
    type = "jar";
    pom = {
      sha1 = "645352132b8d239bcc737c3c164f435af97cd9bb";
      sha256 = "10krh8bnjf2rypqqpfh4ik1jnqpbifcs4g8yakyb9hcf9bkjn4i9";
    };
    jar = {
      sha1 = "960dea7c9181ba0b17e8bab0c06a43f0a5f04e65";
      sha256 = "12129q8rmqwlvj6z4j0gc3w0hq5ccrkf2gdlsggp3iws7cp7wjw0";
    };
  };
  "https://jcenter.bintray.com/org/eclipse/jdt/core/compiler/ecj/4.4/ecj-4.4" = {
    host = repositories.jcenter;
    path = "org/eclipse/jdt/core/compiler/ecj/4.4/ecj-4.4";
    type = "jar";
    pom = {
      sha1 = "9dff19e8900783b7e6c520c3e1b44e09523cb0a0";
      sha256 = "1rdp3hfdn8ra0v2vff5wyb6va65q05m2lcm57k6i72f8jnn6y1ca";
    };
    jar = {
      sha1 = "fe0a961ce7cca03dd3c9b3775c0133229e8231a6";
      sha256 = "1g7ys82plhprp0lv73grfnb463v59klny9zvkd0hjjz10824n5hn";
    };
  };
  "https://jcenter.bintray.com/org/ow2/asm/asm/5.0.3/asm-5.0.3" = {
    host = repositories.jcenter;
    path = "org/ow2/asm/asm/5.0.3/asm-5.0.3";
    type = "jar";
    pom = {
      sha1 = "7d9570aceff0131a35a87d37b53452be33cf3cd9";
      sha256 = "18565g4264fv0d7hq9fq34dyrybxl5h9d5pis8a7ggk2zqznad3x";
    };
    jar = {
      sha1 = "dcc2193db20e19e1feca8b1240dbbc4e190824fa";
      sha256 = "1k265g2nq810yg7sb9h5f1kyp2f0m2z2mz8drkcxr3vv8f7ggi3i";
    };
  };
  "https://jcenter.bintray.com/org/ow2/asm/asm-analysis/5.0.3/asm-analysis-5.0.3" = {
    host = repositories.jcenter;
    path = "org/ow2/asm/asm-analysis/5.0.3/asm-analysis-5.0.3";
    type = "jar";
    pom = {
      sha1 = "2270e3099f178e9562a92c6eb27a7ad12e3fa850";
      sha256 = "1l570la07zr6ay1c9i5caglj029dyjwrv24zmn9n511xpjhh5z4z";
    };
    jar = {
      sha1 = "c7126aded0e8e13fed5f913559a0dd7b770a10f3";
      sha256 = "17c4j2r94xgbjh5wylgqdwv7fjr6w4jmbhinrmymb5ic8rijmyp8";
    };
  };
  "https://jcenter.bintray.com/org/ow2/asm/asm-parent/5.0.3/asm-parent-5.0.3" = {
    host = repositories.jcenter;
    path = "org/ow2/asm/asm-parent/5.0.3/asm-parent-5.0.3";
    type = "jar";
    pom = {
      sha1 = "f2b915adcf47fab0e17bccf47390aa206eba7937";
      sha256 = "0clf3252nhw52k34vhjsm4mj8kz9casvkc5lp3s4slwa2bsapvf2";
    };
  };
  "https://jcenter.bintray.com/org/ow2/asm/asm-tree/5.0.3/asm-tree-5.0.3" = {
    host = repositories.jcenter;
    path = "org/ow2/asm/asm-tree/5.0.3/asm-tree-5.0.3";
    type = "jar";
    pom = {
      sha1 = "67e01f0d7339cdeaf709be24a7c333f396005e8e";
      sha256 = "0djjrxa10ny1mv0sq5yh6zqq371174xjzrzbz14zy652qnkrr0b5";
    };
    jar = {
      sha1 = "287749b48ba7162fb67c93a026d690b29f410bed";
      sha256 = "0755acl6d70q49znzcy39c18vp7bivj80f8xr63lx5pr02a7lyil";
    };
  };
  "https://jcenter.bintray.com/org/ow2/ow2/1.3/ow2-1.3" = {
    host = repositories.jcenter;
    path = "org/ow2/ow2/1.3/ow2-1.3";
    type = "jar";
    pom = {
      sha1 = "f679d6639bfb209b0836a5e7cf09bfbcc1a41f06";
      sha256 = "1yr8hfx8gffpppa4ii6cvrsq029a6x8hzy7nsavxhs60s9kmq8ai";
    };
  };
  "https://jcenter.bintray.com/org/sonatype/oss/oss-parent/7/oss-parent-7" = {
    host = repositories.jcenter;
    path = "org/sonatype/oss/oss-parent/7/oss-parent-7";
    type = "jar";
    pom = {
      sha1 = "46b8a785b60a2767095b8611613b58577e96d4c9";
      sha256 = "0m4lallnlhyfj3z24ispxzwvsxzaznhw6zsmk4j74sibr5kqh7xm";
    };
  };
}
