# Auto-generated by ../../../../tools/maven/maven-inputs2nix.sh
{}:

let
  repositories = {
    apache = "https://repo1.maven.org/maven2";
    clojars = "https://repo.clojars.org";
    fabric-io = "https://maven.fabric.io/public";
    google = "https://dl.google.com/dl/android/maven2";
    jcenter = "https://jcenter.bintray.com";
    maven = "https://repo1.maven.org/maven2";
  };

in {
  "https://dl.google.com/dl/android/maven2/android/arch/core/common/1.1.1/common-1.1.1" = {
    host = repositories.google;
    path = "android/arch/core/common/1.1.1/common-1.1.1";
    type = "jar";
    pom = {
      sha1 = "5cc390dbeaacc19fe0965f74409118d2dfacce9e";
      sha256 = "0p0ayl1vfry0j38gxf5vcm333pzdsli2mc485wwgmiycxazar4gb";
    };
    jar = {
      sha1 = "e55b70d1f5620db124b3e85a7f4bdc7bd48d9f95";
      sha256 = "06hm9hgzw9bn7ck0clp878yn24xh65f5ff3balzy5s9kyhr6lq9s";
    };
  };
  "https://dl.google.com/dl/android/maven2/android/arch/core/runtime/1.1.1/runtime-1.1.1" = {
    host = repositories.google;
    path = "android/arch/core/runtime/1.1.1/runtime-1.1.1";
    type = "aar";
    pom = {
      sha1 = "cc16795b4f119cce855c9b0c3898cc99d1c7677a";
      sha256 = "1ack26gzb0r0nsp9x1rq880d7x5309z0v8k02j05s21d2jck0i9h";
    };
    jar = {
      sha1 = "a7e27caf787e14c0d8417be907f4a31f0306acb2";
      sha256 = "0fawl29pzici28z8rpi7q4drg2dd4ly4lkkgibwb649khyjml8f3";
    };
  };
  "https://dl.google.com/dl/android/maven2/android/arch/lifecycle/common/1.1.1/common-1.1.1" = {
    host = repositories.google;
    path = "android/arch/lifecycle/common/1.1.1/common-1.1.1";
    type = "jar";
    pom = {
      sha1 = "92d7cbcfe8e43586172bf0ffe809fff9c57cf556";
      sha256 = "10jf7gl280lk1mfkypkq7chp9jz433gil68iz0kfl1id497yfhhp";
    };
    jar = {
      sha1 = "207a6efae6a3555e326de41f76bdadd9a239cbce";
      sha256 = "0mpz3jwbh7riw9h637aima8gss68294428znxq4rw66mxf48wdwd";
    };
  };
  "https://dl.google.com/dl/android/maven2/android/arch/lifecycle/livedata/1.1.1/livedata-1.1.1" = {
    host = repositories.google;
    path = "android/arch/lifecycle/livedata/1.1.1/livedata-1.1.1";
    type = "aar";
    pom = {
      sha1 = "b4b4d001ca961adb29783cfcdb61c36f877c51bf";
      sha256 = "0vl53g5ycr4130pljpyl9wcywrn03jlk71f3fim636kk71kk1nz8";
    };
    jar = {
      sha1 = "82e0b1bf2dc8ce23898cf433cc150df7b3dba952";
      sha256 = "0l6ppjhw9vq0k7rj9m0ddna8h208ifck4h2m9vxpq6pzq6809ash";
    };
  };
  "https://dl.google.com/dl/android/maven2/android/arch/lifecycle/livedata-core/1.1.1/livedata-core-1.1.1" = {
    host = repositories.google;
    path = "android/arch/lifecycle/livedata-core/1.1.1/livedata-core-1.1.1";
    type = "aar";
    pom = {
      sha1 = "7df0f1b6e3af11086bbc1e803560483c6c817c8a";
      sha256 = "18g29x8wn7pk8fcxjdkx1qh5kgnpb3my2f25p36nxjfmbzc1r8b7";
    };
    jar = {
      sha1 = "30ede25cb577323f039c2e3d72b3b56526a2b2e6";
      sha256 = "0l1cq4y8vq39ghb46kdp6vlvxwc39si8csgil9z8s5ynhnwxizfn";
    };
  };
  "https://dl.google.com/dl/android/maven2/android/arch/lifecycle/runtime/1.1.1/runtime-1.1.1" = {
    host = repositories.google;
    path = "android/arch/lifecycle/runtime/1.1.1/runtime-1.1.1";
    type = "aar";
    pom = {
      sha1 = "a03da450cdabd1a202c603bd7476a2e06b1320c0";
      sha256 = "14p5qzqss25nh4h71zxkk53klwrc8ywk62a7dn5ivhnnm71d79y7";
    };
    jar = {
      sha1 = "4286e1ae9364b485cb2ff7a370e355b7c570015b";
      sha256 = "0l75r941m4qjyalz4szrw3vi6h713m74aw9mb7napw5jq5kbxr64";
    };
  };
  "https://dl.google.com/dl/android/maven2/android/arch/lifecycle/viewmodel/1.1.1/viewmodel-1.1.1" = {
    host = repositories.google;
    path = "android/arch/lifecycle/viewmodel/1.1.1/viewmodel-1.1.1";
    type = "aar";
    pom = {
      sha1 = "12c7545bef90f1f99fa58d76c7883f98aa566d86";
      sha256 = "0m85hkqkqcld7pawm77bd62xb4fm69g0bx5skwqxn5qxxqc2bbny";
    };
    jar = {
      sha1 = "897b6e22c8357b23ab0c7600c961549c098f5ccf";
      sha256 = "0sn95f71y7ds4apl2fg6hz85009dh7v5fk13pvavbmkppbx9rqkx";
    };
  };
  "https://dl.google.com/dl/android/maven2/com/android/support/animated-vector-drawable/28.0.0/animated-vector-drawable-28.0.0" = {
    host = repositories.google;
    path = "com/android/support/animated-vector-drawable/28.0.0/animated-vector-drawable-28.0.0";
    type = "aar";
    pom = {
      sha1 = "c22c9ae3b30ed1d7098aca477c5ccc7679e69f4e";
      sha256 = "1jpcjm59larpmd7p99frsbj8z0kfy3crzyl6jjskq6avrsf3yy6l";
    };
    jar = {
      sha1 = "e2d41c2a032145313f42ab38a2d9757c5d1ebc19";
      sha256 = "1dxkiz8nz3ipdihnz04w32j0hd4w29rh9fjmwvcxra6d0v4wn7i7";
    };
  };
  "https://dl.google.com/dl/android/maven2/com/android/support/appcompat-v7/28.0.0/appcompat-v7-28.0.0" = {
    host = repositories.google;
    path = "com/android/support/appcompat-v7/28.0.0/appcompat-v7-28.0.0";
    type = "aar";
    pom = {
      sha1 = "ab02e68f7b1362ef629f5e25bc412db5b92d1cc2";
      sha256 = "05syijvlcpdvzgzsmgvhmr0v7icyx8njj3acd58vdcga6ziapwnr";
    };
    jar = {
      sha1 = "132586ec59604a86703796851a063a0ac61f697b";
      sha256 = "0lhp66q8rxf8cxylr8g6qjqy6s26prgrnmq133cnwx2r0ciyba53";
    };
  };
  "https://dl.google.com/dl/android/maven2/com/android/support/asynclayoutinflater/28.0.0/asynclayoutinflater-28.0.0" = {
    host = repositories.google;
    path = "com/android/support/asynclayoutinflater/28.0.0/asynclayoutinflater-28.0.0";
    type = "aar";
    pom = {
      sha1 = "e773fa88d9f5ae46f3e71bb942a97bdc3531c275";
      sha256 = "0y3f3jqqn35fjcqpz94hdwzid8rz8aszbfj0zdd5v9n1lw61s3vr";
    };
    jar = {
      sha1 = "3ae7643d120e6da3adbe2d698de923f48c904d1f";
      sha256 = "18hs6pf9afsmn32i0h7knwdsz63wvmh5ywqckdbk8wqzfa3xwnqi";
    };
  };
  "https://dl.google.com/dl/android/maven2/com/android/support/collections/28.0.0/collections-28.0.0" = {
    host = repositories.google;
    path = "com/android/support/collections/28.0.0/collections-28.0.0";
    type = "jar";
    pom = {
      sha1 = "24fa6fc0c382f329fd572c9dd6ca30598aec1679";
      sha256 = "1fi7rz03l8s4dy7fycxb9y5skljrxlliqba0f4lyaa90idmi9i7n";
    };
    jar = {
      sha1 = "c1bcdade4d3cc2836130424a3f3e4182c666a745";
      sha256 = "1w6ly8l5d1dhan3cn4cb6h7dmxpqq119g0jkfqk1llwzl345ihlk";
    };
  };
  "https://dl.google.com/dl/android/maven2/com/android/support/coordinatorlayout/28.0.0/coordinatorlayout-28.0.0" = {
    host = repositories.google;
    path = "com/android/support/coordinatorlayout/28.0.0/coordinatorlayout-28.0.0";
    type = "aar";
    pom = {
      sha1 = "3f90fe50dd83481187803d7b7f295eca55e2cd9f";
      sha256 = "0kqs6r9mf5r0pca9v9h2pgsz8gmq31d9cgnlnbvxm09gd16ng0yb";
    };
    jar = {
      sha1 = "7a708aac3443762e58e84368040a6a23b2c63545";
      sha256 = "14iqin45d9krgqvif97bkwjlcg2lxv087vdsiw27kj9x8a0cvylx";
    };
  };
  "https://dl.google.com/dl/android/maven2/com/android/support/cursoradapter/28.0.0/cursoradapter-28.0.0" = {
    host = repositories.google;
    path = "com/android/support/cursoradapter/28.0.0/cursoradapter-28.0.0";
    type = "aar";
    pom = {
      sha1 = "ee60adb53344c2479c57078be8e7351efcd35504";
      sha256 = "0nr7bzjpyghhl3xxmily1w35vm888ncw0ma6yzlbqmw3w8y109sp";
    };
    jar = {
      sha1 = "d803f573799e6cd2db8839e2a70fe6ad67e86b79";
      sha256 = "088dz6nhch7c0q9sviri5rknmgrq91bbwfl3m6l2rmmq8bkzzzl7";
    };
  };
  "https://dl.google.com/dl/android/maven2/com/android/support/customview/28.0.0/customview-28.0.0" = {
    host = repositories.google;
    path = "com/android/support/customview/28.0.0/customview-28.0.0";
    type = "aar";
    pom = {
      sha1 = "89f073c97f9d118561f36badc59d05c1e73a5939";
      sha256 = "1r8hf0r4jhh4hbrm4lpank7dbfk7v8a8snb3b7dzh7nmvwljfz0q";
    };
    jar = {
      sha1 = "423fe0f417f2f8d9c718c2cf73f9253da43f1f11";
      sha256 = "0aq79rlhy3whfa9fqla2z5q2x8fa1kzw20gpicj0hklrby207nwq";
    };
  };
  "https://dl.google.com/dl/android/maven2/com/android/support/documentfile/28.0.0/documentfile-28.0.0" = {
    host = repositories.google;
    path = "com/android/support/documentfile/28.0.0/documentfile-28.0.0";
    type = "aar";
    pom = {
      sha1 = "b4e17b5306710bef527eb999b74cd1596f722e78";
      sha256 = "1flw7ynsp1x2hbh7ihki49x784gv0w2c19m9z1ij85adwf9sdzaz";
    };
    jar = {
      sha1 = "1187e4a23ff6250b096249c734bdabf5403c6ba9";
      sha256 = "0ya7bnmiyycp3svjciyspgcvpfh3bix4h19zj9jb1dq2jczcvka7";
    };
  };
  "https://dl.google.com/dl/android/maven2/com/android/support/drawerlayout/28.0.0/drawerlayout-28.0.0" = {
    host = repositories.google;
    path = "com/android/support/drawerlayout/28.0.0/drawerlayout-28.0.0";
    type = "aar";
    pom = {
      sha1 = "c19f2e1d602083cb79044be5b7d3763b84d7d727";
      sha256 = "0dpy7imd231311x7d4gd235vzh6d1snr549lsl56xi1s985jsks2";
    };
    jar = {
      sha1 = "4de65d42b8e1b7f0ba40b5f35e5d4bafcd70019f";
      sha256 = "02hmy66i865z6d9kxlmlvcinmbjlx489h7266w65b4s7msphjs4g";
    };
  };
  "https://dl.google.com/dl/android/maven2/com/android/support/interpolator/28.0.0/interpolator-28.0.0" = {
    host = repositories.google;
    path = "com/android/support/interpolator/28.0.0/interpolator-28.0.0";
    type = "aar";
    pom = {
      sha1 = "d1c6242ef62233247c5f9810e8d7dfa926da594d";
      sha256 = "16wzc0nzaqgqfyiq3k87m89kmlpndgssm4m0pikqzcswm9g5ysr9";
    };
    jar = {
      sha1 = "5d501569c8f7b667c47333a0b873aa529e0a0b9c";
      sha256 = "1skp0sx38szdnsg7fzfm30hrdgfj8acfiwsn36ss8ffvl23fxivv";
    };
  };
  "https://dl.google.com/dl/android/maven2/com/android/support/loader/28.0.0/loader-28.0.0" = {
    host = repositories.google;
    path = "com/android/support/loader/28.0.0/loader-28.0.0";
    type = "aar";
    pom = {
      sha1 = "f8c23ac6d03e41ae08a8f1324d5464dac43167d2";
      sha256 = "1pz8ayarpf2magxz91ifchg3dnjny4d7b6zy0canv52bgxhav6ws";
    };
    jar = {
      sha1 = "49a297a4635e01ed55f31b5d4a718ba3416fde3d";
      sha256 = "0h838vr12xp186km31yzqs1q9f3kzs1si20gbf8kxhrdszpqa2wj";
    };
  };
  "https://dl.google.com/dl/android/maven2/com/android/support/localbroadcastmanager/28.0.0/localbroadcastmanager-28.0.0" = {
    host = repositories.google;
    path = "com/android/support/localbroadcastmanager/28.0.0/localbroadcastmanager-28.0.0";
    type = "aar";
    pom = {
      sha1 = "f078013fe477c3468b16d39296f719a8fc5cd3e2";
      sha256 = "149h64rmb37i763gq20mzn9v1g4bc7agj7vby7gi64a26l9r86im";
    };
    jar = {
      sha1 = "5c498cb7e2fa5910d6c50e28531c55b77d6bf0f6";
      sha256 = "01m8r0rdx4pxwqx38559yxx6isgg63vcbkwz14nfgpazmwiwi1yj";
    };
  };
  "https://dl.google.com/dl/android/maven2/com/android/support/print/28.0.0/print-28.0.0" = {
    host = repositories.google;
    path = "com/android/support/print/28.0.0/print-28.0.0";
    type = "aar";
    pom = {
      sha1 = "b24c49ea877ee5fb066f53c5f20d23aecfd6a324";
      sha256 = "0y3fkj22rlaxjnj73q963713kbbfzlhvkcdfj6yzqp2gwqadjpg1";
    };
    jar = {
      sha1 = "d2c60bfbbdc2eadd4ff7c8f65743fab830339743";
      sha256 = "0a2p7x883k50k91vrwvbfawhngzggl9axklibgiq0jiysw9ais2b";
    };
  };
  "https://dl.google.com/dl/android/maven2/com/android/support/slidingpanelayout/28.0.0/slidingpanelayout-28.0.0" = {
    host = repositories.google;
    path = "com/android/support/slidingpanelayout/28.0.0/slidingpanelayout-28.0.0";
    type = "aar";
    pom = {
      sha1 = "a643e0ed2f476b766e863c05ecd1797361ad3d9e";
      sha256 = "0696s0x8bl916j6gp0nja93lhqhk4zmcb5hm0y1xggfqiw6sqixy";
    };
    jar = {
      sha1 = "20468e3ec8f36dc84846ddd99ff30516f4ffd05a";
      sha256 = "006nij4yqdwhks48x3075048q4lpdz3ackxrx6pajdhvdbv39lni";
    };
  };
  "https://dl.google.com/dl/android/maven2/com/android/support/support-annotations/28.0.0/support-annotations-28.0.0" = {
    host = repositories.google;
    path = "com/android/support/support-annotations/28.0.0/support-annotations-28.0.0";
    type = "jar";
    pom = {
      sha1 = "f3de3ef854e72e9b4491b0f8b9097455704f3054";
      sha256 = "06h9y2fy4bi16rc242wg4l0s4w4abf3mji2z9lxgv4j404g4i1m0";
    };
    jar = {
      sha1 = "ed73f5337a002d1fd24339d5fb08c2c9d9ca60d8";
      sha256 = "09xrjf54i4fglvzn6kccrj77r9hdmvfxbf16fppa0grdy0a98nsx";
    };
  };
  "https://dl.google.com/dl/android/maven2/com/android/support/support-compat/28.0.0/support-compat-28.0.0" = {
    host = repositories.google;
    path = "com/android/support/support-compat/28.0.0/support-compat-28.0.0";
    type = "aar";
    pom = {
      sha1 = "ededbbdbfc461c09f992371624bf7fa564748c36";
      sha256 = "06ln7psm2gm6nskdj48cgd2mrzs1mlk6m0px3jb0zz4249na0ybb";
    };
    jar = {
      sha1 = "d252b640ed832cf8addc35ef0a9f9186dc7738a5";
      sha256 = "12hi2xc9qshbdr2jw96664i3va9wj0pjjhv9r2hrwgzavc0knzp1";
    };
  };
  "https://dl.google.com/dl/android/maven2/com/android/support/support-core-ui/28.0.0/support-core-ui-28.0.0" = {
    host = repositories.google;
    path = "com/android/support/support-core-ui/28.0.0/support-core-ui-28.0.0";
    type = "aar";
    pom = {
      sha1 = "92fb72fc4b7dcf8ed19311acb519a8aa9ff1abbd";
      sha256 = "0i5mg7k6bxq3cr062n72y3lgwhalmqjhdzcmwfp2brlcljkd92kh";
    };
    jar = {
      sha1 = "96035b1030d7c3a81903966c2fa52117d36aa5b7";
      sha256 = "0vvc9dbpxwmvlbdbmhs9nzrzkd9aadhk6dxg6d3lcjanr5gzdixv";
    };
  };
  "https://dl.google.com/dl/android/maven2/com/android/support/support-core-utils/28.0.0/support-core-utils-28.0.0" = {
    host = repositories.google;
    path = "com/android/support/support-core-utils/28.0.0/support-core-utils-28.0.0";
    type = "aar";
    pom = {
      sha1 = "3c7f20edba570e68230a0dda8b1973d2fbd3963e";
      sha256 = "1xzalj9zr15k3sf3lsi9y1k9msixjkfkbv6a1r6kb2wyffw499w6";
    };
    jar = {
      sha1 = "29b1bb783f1a86eba7f1618bad58842bde72892a";
      sha256 = "0hdcj1byn1p2jwn09wdjii5kdv1an8swys9c02pfvciwrac1w7n8";
    };
  };
  "https://dl.google.com/dl/android/maven2/com/android/support/support-fragment/28.0.0/support-fragment-28.0.0" = {
    host = repositories.google;
    path = "com/android/support/support-fragment/28.0.0/support-fragment-28.0.0";
    type = "aar";
    pom = {
      sha1 = "68f1c70d7d3a075c2f4dcbfe908dd112068bc11c";
      sha256 = "01wvhrvkzpnzdp3a6qanrdhxzg221zxakvcvsf16pckpbggdljyj";
    };
    jar = {
      sha1 = "f21c8a8700b30dc57cb6277ae3c4c168a94a4e81";
      sha256 = "05d9hws2xvwmvsqrsb7yviyppmnvqfbz3cx4l55q51nsi9rzqwip";
    };
  };
  "https://dl.google.com/dl/android/maven2/com/android/support/support-vector-drawable/28.0.0/support-vector-drawable-28.0.0" = {
    host = repositories.google;
    path = "com/android/support/support-vector-drawable/28.0.0/support-vector-drawable-28.0.0";
    type = "aar";
    pom = {
      sha1 = "c591e6355f4f464473cc389544840b9426623dcb";
      sha256 = "1p5a698pp2m1v95dic2vi4f33yawiy0a3glvn16jgwdh89hl2m0y";
    };
    jar = {
      sha1 = "80387886ef55af284d8253e52d321f93b3f923dd";
      sha256 = "0k9z6z66j41k9lg8ccz1wl7phl30r5qq8mr8xp7vqwl1jrnrhn7n";
    };
  };
  "https://dl.google.com/dl/android/maven2/com/android/support/swiperefreshlayout/28.0.0/swiperefreshlayout-28.0.0" = {
    host = repositories.google;
    path = "com/android/support/swiperefreshlayout/28.0.0/swiperefreshlayout-28.0.0";
    type = "aar";
    pom = {
      sha1 = "38d38af71b3f552cb2daefcc1fce37682d22b048";
      sha256 = "0bw7vicqv28a4zr7m4347ysybxrhr082bq0by92ai62xnwr8vq62";
    };
    jar = {
      sha1 = "bfa669303f0ac8a83d9c878fafadc2936625f781";
      sha256 = "04p74n9mzzxj1wq39xb5jxlmhj4dk2gy91jyhr4np1ihcxzizd53";
    };
  };
  "https://dl.google.com/dl/android/maven2/com/android/support/versionedparcelable/28.0.0/versionedparcelable-28.0.0" = {
    host = repositories.google;
    path = "com/android/support/versionedparcelable/28.0.0/versionedparcelable-28.0.0";
    type = "aar";
    pom = {
      sha1 = "c95ed52768492e6352cce0d2c63f71b25a636729";
      sha256 = "0ys472g4y9yir0vysg10z76mm7sh5zgq8qmbiyciid02wwkggmp7";
    };
    jar = {
      sha1 = "90432a1e322e0e0bad2116dff0e64c708514808f";
      sha256 = "00lxij88dcwimjrfbq96w6sk0ngbxc1mw4r3c4zmrdkiiyq1rsv0";
    };
  };
  "https://dl.google.com/dl/android/maven2/com/android/support/viewpager/28.0.0/viewpager-28.0.0" = {
    host = repositories.google;
    path = "com/android/support/viewpager/28.0.0/viewpager-28.0.0";
    type = "aar";
    pom = {
      sha1 = "706d9194dbaeb893abd58110396e980375e2d282";
      sha256 = "03j317s53pczpz4lq9r7l0147b57nbng8fs4myrak97nfdjvl2q8";
    };
    jar = {
      sha1 = "f513ecf69dfea8b60987bd3e869970300ba7c0eb";
      sha256 = "1z2zwf155zqmgn9qpfj2wggpb7qmb2z71sds9l8fqn470m9lqg01";
    };
  };
  "https://dl.google.com/dl/android/maven2/com/android/tools/build/aapt2/3.3.1-5013011/aapt2-3.3.1-5013011" = {
    host = repositories.google;
    path = "com/android/tools/build/aapt2/3.3.1-5013011/aapt2-3.3.1-5013011";
    type = "jar";
    pom = {
      sha1 = "3bbcac529ba134f2342f7a674b1f520c9cde0e71";
      sha256 = "0ywd47jrv6n1f4skl0ag1761zr27p3grgfkyqn62pb4s4mxvzjyp";
    };
  };
  "https://dl.google.com/dl/android/maven2/com/android/tools/build/aapt2/3.3.1-5013011/aapt2-3.3.1-5013011-linux" = {
    host = repositories.google;
    path = "com/android/tools/build/aapt2/3.3.1-5013011/aapt2-3.3.1-5013011-linux";
    type = "jar";
    jar = {
      sha1 = "164e9e0449d28f0eaa5c4e42644ee231373fea35";
      sha256 = "1y9yn71a28ak793y71kid8jhidgj37ngz1q765ky1ml0l69a00ll";
    };
  };
  "https://dl.google.com/dl/android/maven2/com/android/tools/build/aapt2/3.3.2-5309881/aapt2-3.3.2-5309881-osx" = {
    host = repositories.google;
    path = "com/android/tools/build/aapt2/3.3.2-5309881/aapt2-3.3.2-5309881-osx";
    type = "jar";
    jar = {
      sha1 = "2418fe55f78b4ce533d9debf6ee2d494db19c910";
      sha256 = "0k5liykzcblq5h5n0qsp547plaj508dc1y7gkg8703153cb3q9z0";
    };
  };
  "https://dl.google.com/dl/android/maven2/com/android/tools/external/com-intellij/intellij-core/26.3.1/intellij-core-26.3.1" = {
    host = repositories.google;
    path = "com/android/tools/external/com-intellij/intellij-core/26.3.1/intellij-core-26.3.1";
    type = "jar";
    pom = {
      sha1 = "b956b36c6a188ceb0945efdf866b514fd1b86203";
      sha256 = "114r13ccddrvskfrwj7kvfrx3x403cadzqdapl8r26s986vdr8gq";
    };
    jar = {
      sha1 = "73ba0f88dc5c5cdcc9839a4c3bfa50cdd6899bb8";
      sha256 = "0znpq920409968a7pgn65882axaxid4m2hnihhzgbp0r4wf6gdnd";
    };
  };
  "https://dl.google.com/dl/android/maven2/com/android/tools/external/com-intellij/intellij-core/26.3.2/intellij-core-26.3.2" = {
    host = repositories.google;
    path = "com/android/tools/external/com-intellij/intellij-core/26.3.2/intellij-core-26.3.2";
    type = "jar";
    pom = {
      sha1 = "b73b794ff827596d94dcaa8c9ceaac58a6365390";
      sha256 = "0qdp8v4k2kf8y9nndqcgs6d88ilqsz6731y083pwc6hsx0vw83zl";
    };
    jar = {
      sha1 = "1cc3c8681a465cbc8dcc89bc3f73eafede576c08";
      sha256 = "1wwv2f39qr0xyvk0s4yq1hgwxslz6y2qiwpys3fg9s9hhabcqpkc";
    };
  };
  "https://dl.google.com/dl/android/maven2/com/android/tools/external/com-intellij/kotlin-compiler/26.3.1/kotlin-compiler-26.3.1" = {
    host = repositories.google;
    path = "com/android/tools/external/com-intellij/kotlin-compiler/26.3.1/kotlin-compiler-26.3.1";
    type = "jar";
    pom = {
      sha1 = "c24acb40f1969596ead7841456decda8ff41fea3";
      sha256 = "1247h7zwvjhkiadl7q1aihd8p8839kjy0g1bxjsx4nkq509w0dh3";
    };
    jar = {
      sha1 = "57b2192f22cc8c38c09a0a24032af3164b1853a6";
      sha256 = "0vrsa46iwy7lsrl8c1554i5gyjx68p0wqr1k93rd60nj9yxf2b04";
    };
  };
  "https://dl.google.com/dl/android/maven2/com/android/tools/external/com-intellij/kotlin-compiler/26.3.2/kotlin-compiler-26.3.2" = {
    host = repositories.google;
    path = "com/android/tools/external/com-intellij/kotlin-compiler/26.3.2/kotlin-compiler-26.3.2";
    type = "jar";
    pom = {
      sha1 = "4d99a349d4abcdda4a90c47562c9b4785e8d73ff";
      sha256 = "1y8xsbsqq5ld7h1w01h5568438pq2l89iiyy7wgm2c1k4di6920p";
    };
    jar = {
      sha1 = "dd065a40564758b854a212c1caae199e7ed77927";
      sha256 = "1ghvqnf56klvlg6jxazry8a4f7b8sh7a3z9hmy7csjfbgjqdj1qh";
    };
  };
  "https://dl.google.com/dl/android/maven2/com/android/tools/external/org-jetbrains/uast/26.3.1/uast-26.3.1" = {
    host = repositories.google;
    path = "com/android/tools/external/org-jetbrains/uast/26.3.1/uast-26.3.1";
    type = "jar";
    pom = {
      sha1 = "5de83eeee23786f7044eb684cac57d39bfcccb44";
      sha256 = "124z1si7gqzxif26d90wm5kd9dhc5j0dijhh4mf85qq574yvz45m";
    };
    jar = {
      sha1 = "113330d8c05c4a8576ae20d69c4fe8a82c73d6e1";
      sha256 = "0jlq6l5h42y6i2hr4pfpzig6aif2l6865v1h7n8zg2jvgybkdv6n";
    };
  };
  "https://dl.google.com/dl/android/maven2/com/android/tools/external/org-jetbrains/uast/26.3.2/uast-26.3.2" = {
    host = repositories.google;
    path = "com/android/tools/external/org-jetbrains/uast/26.3.2/uast-26.3.2";
    type = "jar";
    pom = {
      sha1 = "337b1931e846702e8ab799e51bc79169434fe653";
      sha256 = "05nc6n18cl2pd3vflqg28jn6c54sm4rvnvp7s2sbc22dbk4d672q";
    };
    jar = {
      sha1 = "dbef8f8cb9e6b38eb921c8359605898a5f0e5ec8";
      sha256 = "05skn31gvhqqx3fx60yh76yjq5habxlxxpq8jyl3hkzacbjk662x";
    };
  };
  "https://dl.google.com/dl/android/maven2/com/android/tools/lint/lint/26.3.1/lint-26.3.1" = {
    host = repositories.google;
    path = "com/android/tools/lint/lint/26.3.1/lint-26.3.1";
    type = "jar";
    pom = {
      sha1 = "acd5fab066fe3bcaf43a5ca546546645aefe42ad";
      sha256 = "1yx3a2s9r473q2934y4hpwnfgi3v4l7vccaw5034qdshr61720qq";
    };
    jar = {
      sha1 = "32358ac77a47d454399ff487b08892931ade0814";
      sha256 = "0akwvz5pixx0ywy69dffax8k10qisc0m8hycpygr44l9k31n8shy";
    };
  };
  "https://dl.google.com/dl/android/maven2/com/android/tools/lint/lint/26.3.2/lint-26.3.2" = {
    host = repositories.google;
    path = "com/android/tools/lint/lint/26.3.2/lint-26.3.2";
    type = "jar";
    pom = {
      sha1 = "76f540e842fcf0f396f357b4d3878b7503410106";
      sha256 = "1vina16akymcbyxjrk4f61nrqh952xjpmjnhhjar2zaz0rjjqx5i";
    };
    jar = {
      sha1 = "7743aa777bad9a6dbcc6954f35ee6ed6a185014e";
      sha256 = "0kpydis42r24gms8978sf559wcxrcrv3a72c1z5jraaniagkcyzg";
    };
  };
  "https://dl.google.com/dl/android/maven2/com/android/tools/lint/lint-api/26.3.1/lint-api-26.3.1" = {
    host = repositories.google;
    path = "com/android/tools/lint/lint-api/26.3.1/lint-api-26.3.1";
    type = "jar";
    pom = {
      sha1 = "2ff787ccc34858ccf33df5f4f7850a8fc96acbbd";
      sha256 = "18xd7vs8bzb8f181p5a6h7s8vhdbr9wa65p5m539c6z41blxlm4h";
    };
    jar = {
      sha1 = "b630e36ffd4511d9e01d606aa3868cfce6f18b9f";
      sha256 = "1jrgy1b9prggdc4wvdpr725inhpyndlzv124f4f9plk563vhby28";
    };
  };
  "https://dl.google.com/dl/android/maven2/com/android/tools/lint/lint-api/26.3.2/lint-api-26.3.2" = {
    host = repositories.google;
    path = "com/android/tools/lint/lint-api/26.3.2/lint-api-26.3.2";
    type = "jar";
    pom = {
      sha1 = "a1bd85b1eaa3673e36bfd33fd4e3e82efab0c5ff";
      sha256 = "1il4znx8vwi4rwx53laqbnjvslvrdsx714ikax9776nm0gxw13fg";
    };
    jar = {
      sha1 = "992995e7e4c1d183cc0b0e71382b53235c54084c";
      sha256 = "0cqh1v6v8vy4zqg0mh4l8p9l5dgr8p82jpbah4d1ckjazgbxyrsq";
    };
  };
  "https://dl.google.com/dl/android/maven2/com/android/tools/lint/lint-checks/26.3.1/lint-checks-26.3.1" = {
    host = repositories.google;
    path = "com/android/tools/lint/lint-checks/26.3.1/lint-checks-26.3.1";
    type = "jar";
    pom = {
      sha1 = "f54efe8486908173bccca1130a2382410d0cc85a";
      sha256 = "1gi6hadqvdqka8gv43rs60myd9ph2xgxihrsdq1fkqms47787ybs";
    };
    jar = {
      sha1 = "188bfd4ed5bfe45af94e2bd3359c6c9aed121841";
      sha256 = "1284ff0i2ggr5c48g8hbd4lcdhdmsz4cwl4wbivn9g3cjmar61hh";
    };
  };
  "https://dl.google.com/dl/android/maven2/com/android/tools/lint/lint-checks/26.3.2/lint-checks-26.3.2" = {
    host = repositories.google;
    path = "com/android/tools/lint/lint-checks/26.3.2/lint-checks-26.3.2";
    type = "jar";
    pom = {
      sha1 = "7fead10a712464366da9582f1d749d4587c3f95e";
      sha256 = "1zgs13i94svxa8l9mrxf5nhinclhjxlf4485n6klx70fid8545nw";
    };
    jar = {
      sha1 = "05b545a7f2ca1325bf470847eca6118f6f143497";
      sha256 = "05vmw91d9vwnyhyfzk7jzhgngq6rl1cdxa1bx5qjf3brjff3n5jb";
    };
  };
  "https://dl.google.com/dl/android/maven2/com/android/tools/lint/lint-gradle/26.3.1/lint-gradle-26.3.1" = {
    host = repositories.google;
    path = "com/android/tools/lint/lint-gradle/26.3.1/lint-gradle-26.3.1";
    type = "jar";
    pom = {
      sha1 = "3f486ef1e8cdaca9177ed3274889558179dac220";
      sha256 = "04krgh9rqkxdaw012bn02k8qh3szk5ivrkwc50gsq03k4fd2vizl";
    };
    jar = {
      sha1 = "18909bd9dcf095d02df647f68f2d2e4a1422d316";
      sha256 = "0a0c52wnxlpiib7dp9pw9maiydbgmx0mq8sfzdcgqyhdj6m4jvpg";
    };
  };
  "https://dl.google.com/dl/android/maven2/com/android/tools/lint/lint-gradle/26.3.2/lint-gradle-26.3.2" = {
    host = repositories.google;
    path = "com/android/tools/lint/lint-gradle/26.3.2/lint-gradle-26.3.2";
    type = "jar";
    pom = {
      sha1 = "44a588754f2e968ff8a222cd085675cee98d2cf5";
      sha256 = "118cvnqcvb37n0l2qmwg67li7vmgcc3v6dfp3w0v4a2yk6bf6r4w";
    };
    jar = {
      sha1 = "9e88bd5de70ef99d3d5f265c72b3f10f4095a6f9";
      sha256 = "04wha4xm94994xfmly76bfw6wsmp96dkifclqcnd95yfyharc4xv";
    };
  };
  "https://jcenter.bintray.com/com/facebook/fresco/drawee/1.10.0/drawee-1.10.0" = {
    host = repositories.jcenter;
    path = "com/facebook/fresco/drawee/1.10.0/drawee-1.10.0";
    type = "aar";
    pom = {
      sha1 = "f960dd453f106eccec26b6992c7c069b20c4ddf4";
      sha256 = "1nwpfmazw6nwrdvryv14vbf7q2sq913g9s0xpzhf9mccy1gbf2rl";
    };
    jar = {
      sha1 = "c1fef7cdc5f6e4fd7d7c58522075c6b66f46a52b";
      sha256 = "1jla9n8h5bmlkc5zck0yzrrgl53zdpj6rnb99fddj56kwswlwraz";
    };
  };
  "https://jcenter.bintray.com/com/facebook/fresco/fbcore/1.10.0/fbcore-1.10.0" = {
    host = repositories.jcenter;
    path = "com/facebook/fresco/fbcore/1.10.0/fbcore-1.10.0";
    type = "aar";
    pom = {
      sha1 = "787a9c976a2e65aef850ca3b47a201cd038f7504";
      sha256 = "041zsrfvdj2380k51fv7h4bbyx8hv97wyxbiviy3x5mia1kzvv43";
    };
    jar = {
      sha1 = "d79dbf5e47d6e528dd1f90170e0299c14d835ab8";
      sha256 = "0vjhpg4rqpksq3gy7kmjcccxmbjgfzhjzxp8ig05i9jiwch7kfav";
    };
  };
  "https://jcenter.bintray.com/com/facebook/fresco/fresco/1.10.0/fresco-1.10.0" = {
    host = repositories.jcenter;
    path = "com/facebook/fresco/fresco/1.10.0/fresco-1.10.0";
    type = "aar";
    pom = {
      sha1 = "d24ce1a0d9cb5ce0928d8f84f6be962f1d5a6294";
      sha256 = "0jzmr47i4975h6bkzkgvma0dgdsyydfrm494x7jbh27v1n4bhvdm";
    };
    jar = {
      sha1 = "076812472879be341f392c4aab469b8fdf8c6759";
      sha256 = "1pi3yz0liwdsxcwwxzy6p8hqzq0ry51zv9gw236sjwm1sxif1mii";
    };
  };
  "https://jcenter.bintray.com/com/facebook/fresco/imagepipeline/1.10.0/imagepipeline-1.10.0" = {
    host = repositories.jcenter;
    path = "com/facebook/fresco/imagepipeline/1.10.0/imagepipeline-1.10.0";
    type = "aar";
    pom = {
      sha1 = "b3ac436624b81d801e299b8ea9f627f1b4a7318f";
      sha256 = "04hhpv2b2v8983z94gn992rk9rl8yi1gdv43xxdnnqp6z5qhcz5g";
    };
    jar = {
      sha1 = "e317bdb7f18f0f4ac4f3ab5d3edb49fd09290a6f";
      sha256 = "13nf1cwjmjjhai3pk0z3ahdjx3qbg66kigm9rnysi7pkg84c684s";
    };
  };
  "https://jcenter.bintray.com/com/facebook/fresco/imagepipeline-base/1.10.0/imagepipeline-base-1.10.0" = {
    host = repositories.jcenter;
    path = "com/facebook/fresco/imagepipeline-base/1.10.0/imagepipeline-base-1.10.0";
    type = "aar";
    pom = {
      sha1 = "1a7699e330105a7214dcccf0e306ca1e5fc481c0";
      sha256 = "14b4g7c03np8wms8c47bn1g0imv2jaixmmnrzhsaqwjh0qgch9w6";
    };
    jar = {
      sha1 = "56672fa5fa46bf4962adecc7c88a1544f5a20225";
      sha256 = "0jgj2gg4vaj685lzpjlkmyi1yrj5qqmn43r9slg2ry1pd06scz7m";
    };
  };
  "https://jcenter.bintray.com/com/facebook/fresco/imagepipeline-okhttp3/1.10.0/imagepipeline-okhttp3-1.10.0" = {
    host = repositories.jcenter;
    path = "com/facebook/fresco/imagepipeline-okhttp3/1.10.0/imagepipeline-okhttp3-1.10.0";
    type = "aar";
    pom = {
      sha1 = "ccf174ac1bb0d0807a3a931b5c63374a73df6b2e";
      sha256 = "18pc4i509km84wpif21i9c6p4pgfhr3fj124l25pqbwx0c9cgc8j";
    };
    jar = {
      sha1 = "3429ffb776d7511d0f911fbe9efda4c73179d416";
      sha256 = "008ry73mwrd0a671mqwglkrzcb54qp9f8xzpr11pg6j8l4l1lz8k";
    };
  };
  "https://jcenter.bintray.com/com/facebook/infer/annotation/infer-annotation/0.11.2/infer-annotation-0.11.2" = {
    host = repositories.jcenter;
    path = "com/facebook/infer/annotation/infer-annotation/0.11.2/infer-annotation-0.11.2";
    type = "jar";
    pom = {
      sha1 = "7438ce677964a0745b4bf71a1ee1b3c9dc9a5f78";
      sha256 = "0760d2q476scm3fg63s0pam1l6hllfcadqsz0cpcy94kzcqb99vr";
    };
    jar = {
      sha1 = "f514ff4ca022a579d9cf7524846988b646ae4491";
      sha256 = "02fm111rcqqcp7avlvcv53n438g0nb5paxk75c15g90k1bx34y79";
    };
  };
  "https://jcenter.bintray.com/com/facebook/soloader/soloader/0.6.0/soloader-0.6.0" = {
    host = repositories.jcenter;
    path = "com/facebook/soloader/soloader/0.6.0/soloader-0.6.0";
    type = "aar";
    pom = {
      sha1 = "53cb6e74ea402df0db7b87d27b6d977e3b20d18e";
      sha256 = "17mb6v4vbb9mvs6zmwjacn244px7w4q5pnrmmymq9s3bcsivs6da";
    };
    jar = {
      sha1 = "4de8f64830aff60beb52fb27dffb2fcbe54c39df";
      sha256 = "0bnrcda0pfivhzd2x514p7qfdpkz65fwgz0jgskrkjh45175rqnc";
    };
  };
  "https://jcenter.bintray.com/com/google/errorprone/error_prone_annotations/2.1.3/error_prone_annotations-2.1.3" = {
    host = repositories.jcenter;
    path = "com/google/errorprone/error_prone_annotations/2.1.3/error_prone_annotations-2.1.3";
    type = "jar";
    pom = {
      sha1 = "02d1529fa92342313d1c98beb8ca261e36a2d319";
      sha256 = "1x9pfan53fjf9sg2lrwi6g2dvs2b99x8d7ka7in9kciw74fbi34m";
    };
    jar = {
      sha1 = "39b109f2cd352b2d71b52a3b5a1a9850e1dc304b";
      sha256 = "1y3zzjqxckrn39z5d4724lwhkb9fx94i0kb3gkhsjgf18yak5l03";
    };
  };
  "https://jcenter.bintray.com/com/google/errorprone/error_prone_parent/2.1.3/error_prone_parent-2.1.3" = {
    host = repositories.jcenter;
    path = "com/google/errorprone/error_prone_parent/2.1.3/error_prone_parent-2.1.3";
    type = "jar";
    pom = {
      sha1 = "fa65cf11b2b7e955eb3862eb01d5bae721e458c0";
      sha256 = "16r3zfxxcz6ldykibcs7r7qbvwc81dw7msg03nawx7rql4b2canm";
    };
  };
  "https://jcenter.bintray.com/com/parse/bolts/bolts-tasks/1.4.0/bolts-tasks-1.4.0" = {
    host = repositories.jcenter;
    path = "com/parse/bolts/bolts-tasks/1.4.0/bolts-tasks-1.4.0";
    type = "jar";
    pom = {
      sha1 = "db60026ffef8aae5e2bac952e74a106a784ea5ae";
      sha256 = "1q0jhg5wv0gdii0aq1vfwy7ymzvsrsvhgv6q1pjvkhb22630gc4c";
    };
    jar = {
      sha1 = "d85884acf6810a3bbbecb587f239005cbc846dc4";
      sha256 = "1qnfmkd460j460f57dcmkdhymjdjglqw4qmczgr9sfl5r8z1xicv";
    };
  };
  "https://jcenter.bintray.com/com/squareup/okhttp3/okhttp/3.12.1/okhttp-3.12.1" = {
    host = repositories.jcenter;
    path = "com/squareup/okhttp3/okhttp/3.12.1/okhttp-3.12.1";
    type = "jar";
    pom = {
      sha1 = "975e0606bfccdffb6dcf5ccb6a823f70be6be18d";
      sha256 = "19lrms9hq7q86rd8kbahwdzxrmw25h3vxybnfnnsivm84jqpc1ll";
    };
    jar = {
      sha1 = "dc6d02e4e68514eff5631963e28ca7742ac69efe";
      sha256 = "0ihai288y8a0bp7yvkv0mrln23w6qxyq1nmj00pp5x7alwndihq7";
    };
  };
  "https://jcenter.bintray.com/com/squareup/okhttp3/okhttp-urlconnection/3.12.1/okhttp-urlconnection-3.12.1" = {
    host = repositories.jcenter;
    path = "com/squareup/okhttp3/okhttp-urlconnection/3.12.1/okhttp-urlconnection-3.12.1";
    type = "jar";
    pom = {
      sha1 = "3f28e0830ddf8977e67961c8993313c257e91a32";
      sha256 = "025ysyw0cj3sn1nfhrpaf06n38g7yv9j3z12p307ahfi28j7q79r";
    };
    jar = {
      sha1 = "f689d3657c3f1fdbde4877bcddc668491a4ad46f";
      sha256 = "0np5vmg40961mwk0664yy64m4rhrwcs4fxayc0biz7fs2s5i7rrs";
    };
  };
  "https://jcenter.bintray.com/com/squareup/okhttp3/parent/3.12.1/parent-3.12.1" = {
    host = repositories.jcenter;
    path = "com/squareup/okhttp3/parent/3.12.1/parent-3.12.1";
    type = "jar";
    pom = {
      sha1 = "a118bcb30283e6df0fa33574d3eeb69804e0f3dd";
      sha256 = "1g7lzfqfpq3jrpm9lgcsmq2lbrwck5kp3jns7jvvbvgfkc46yz7m";
    };
  };
  "https://jcenter.bintray.com/com/squareup/okio/okio/1.15.0/okio-1.15.0" = {
    host = repositories.jcenter;
    path = "com/squareup/okio/okio/1.15.0/okio-1.15.0";
    type = "jar";
    pom = {
      sha1 = "87f1520a39a954a9aa185c7fe8f144fa7d597690";
      sha256 = "1kmzw5q3p0z6hgp0f5kyx4jjbnkwwdrv41qs0pxpbayih0a0phgi";
    };
    jar = {
      sha1 = "bc28b5a964c8f5721eb58ee3f3c47a9bcbf4f4d8";
      sha256 = "1llb25k2n887b3fz4xxmpip10kv7nwil081bc0037178lwcs6gv9";
    };
  };
  "https://jcenter.bintray.com/com/squareup/okio/okio-parent/1.15.0/okio-parent-1.15.0" = {
    host = repositories.jcenter;
    path = "com/squareup/okio/okio-parent/1.15.0/okio-parent-1.15.0";
    type = "jar";
    pom = {
      sha1 = "5eb9d8103fd3e21923bcf157066957337d6ca71e";
      sha256 = "1ckd0lhrvgzzjlhj36i607cdmv3slh2hsiwrycfp5kdal8z9mq1l";
    };
  };
  "https://jcenter.bintray.com/org/codehaus/groovy/groovy-all/2.4.15/groovy-all-2.4.15" = {
    host = repositories.jcenter;
    path = "org/codehaus/groovy/groovy-all/2.4.15/groovy-all-2.4.15";
    type = "jar";
    pom = {
      sha1 = "c67938b8f20e75a4c025b9519b78c138bd17a758";
      sha256 = "0yinfr31ybi8c8h0ppf62gqpghrm5a72w71jc82sjz6vgdfm63gw";
    };
    jar = {
      sha1 = "423a17aeb2f64bc6f76e8e44265a548bec80fd42";
      sha256 = "1w2siawsbap3aqvp06jynw7ki79majc4k2ci4ds5ds422zkw9mji";
    };
  };
  "https://jcenter.bintray.com/org/jetbrains/trove4j/trove4j/20160824/trove4j-20160824" = {
    host = repositories.jcenter;
    path = "org/jetbrains/trove4j/trove4j/20160824/trove4j-20160824";
    type = "jar";
    pom = {
      sha1 = "c1859aeb2e27070713ee124c01265ce69199faa6";
      sha256 = "03q95m5jv8lybigkfjb2n2czayfcj59f2iqrpvj0s845hnfmlhaw";
    };
    jar = {
      sha1 = "33c3e174a9c8368d93761d3d12712db18e903959";
      sha256 = "1ryvjrjzixf0gwwnv35rn2lgawj5lj3hqs44ll3q6ipbilf8f5qr";
    };
  };
}
