# Auto-generated by ../../../../tools/maven/maven-inputs2nix.sh
{}:

let
  repositories = {
    apache = "https://repo1.maven.org/maven2";
    clojars = "https://repo.clojars.org";
    fabric-io = "https://maven.fabric.io/public";
    google = "https://dl.google.com/dl/android/maven2";
    jcenter = "https://jcenter.bintray.com";
    maven = "https://repo1.maven.org/maven2";
  };

in {
  "https://jcenter.bintray.com/com/android/databinding/baseLibrary/2.2.3/baseLibrary-2.2.3" = {
    host = repositories.jcenter;
    path = "com/android/databinding/baseLibrary/2.2.3/baseLibrary-2.2.3";
    type = "jar";
    pom = {
      sha1 = "ace51773bfc2fff1e8a51b52007476f8d5512996";
      sha256 = "0jbcdi7b4n5w65s10d4lpclm4krh2535bprdqlmjfsi56qykv35c";
    };
    jar = {
      sha1 = "b4b51d1925cdfda98fd861230c1ecb5855500129";
      sha256 = "1sv4gs06aw7kshhc4p2nf4jqxip7dl0a6d6ci7fgv6zfjpn3wd2i";
    };
  };
  "https://jcenter.bintray.com/com/android/databinding/compilerCommon/2.2.3/compilerCommon-2.2.3" = {
    host = repositories.jcenter;
    path = "com/android/databinding/compilerCommon/2.2.3/compilerCommon-2.2.3";
    type = "jar";
    pom = {
      sha1 = "823213efa8cefa2a10de4f9f7d2f0e79fdc8958b";
      sha256 = "16c41n7lv97dy8agg7478m2zvsrcscy4z7dzhda2ksgqr3hm3rgj";
    };
    jar = {
      sha1 = "8c3829022a54acd042b5382a4a873ee2d64c29ee";
      sha256 = "1dmkhpih05bf27zb9rcfhphc6q27y1bjjfdbw5bp3325d7h63ddm";
    };
  };
  "https://jcenter.bintray.com/com/android/tools/analytics-library/protos/25.2.3/protos-25.2.3" = {
    host = repositories.jcenter;
    path = "com/android/tools/analytics-library/protos/25.2.3/protos-25.2.3";
    type = "jar";
    pom = {
      sha1 = "01c42f8c9f0e524acab9da11f2ee23c592a2ce1c";
      sha256 = "1kgb73nna3g3xx8ppcljnvkw5pcjicawfm3m8zkm8xw4xlpk7kri";
    };
    jar = {
      sha1 = "821098054f9667d0f2536d7f2d0200d8bdd9c898";
      sha256 = "0scy1laly7qra41w6wvh4svrg4j1r9mpdsdp1755ajw2vif0wy8v";
    };
  };
  "https://jcenter.bintray.com/com/android/tools/analytics-library/shared/25.2.3/shared-25.2.3" = {
    host = repositories.jcenter;
    path = "com/android/tools/analytics-library/shared/25.2.3/shared-25.2.3";
    type = "jar";
    pom = {
      sha1 = "d673abd9f13cbc2ddd1471e0c4fcd3fe6ea9d41d";
      sha256 = "0z9w8fnjzvp08kpmh18mgjviwds0z40w1my02mcjczkh0apa1qqf";
    };
    jar = {
      sha1 = "785426dac20cfe596e4cf36d01aad930ffdcb05c";
      sha256 = "13gqv286zh5pbcf6f2b1d0vki247yfgmwqip4h759c70jm61d4sa";
    };
  };
  "https://jcenter.bintray.com/com/android/tools/analytics-library/tracker/25.2.3/tracker-25.2.3" = {
    host = repositories.jcenter;
    path = "com/android/tools/analytics-library/tracker/25.2.3/tracker-25.2.3";
    type = "jar";
    pom = {
      sha1 = "abed2b7d3e076606bc55b70615997e56e4d235f3";
      sha256 = "0fvcp5i61kzkppj5j6q5dx4w72qi5ln1ihpqhq89566xxxws962k";
    };
    jar = {
      sha1 = "c807f7b3d9aa3cee795ecac620d22c5ca7dd92e1";
      sha256 = "062y6gcaanbz8cmzmbnvpmd3c08jggpbg7czk38fqfh6cxb6gxm1";
    };
  };
  "https://jcenter.bintray.com/com/android/tools/annotations/24.5.0/annotations-24.5.0" = {
    host = repositories.jcenter;
    path = "com/android/tools/annotations/24.5.0/annotations-24.5.0";
    type = "jar";
    pom = {
      sha1 = "16ae9945d5f0ed5fb1aff1d9aaa627b82096b56e";
      sha256 = "0m2wj96mar7cij4yzvcx1da9ab7ffcaa1s8mcgl9z242h7srpjf3";
    };
    jar = {
      sha1 = "7f2bcdf40b008f15481324327b7f9e377b0b1697";
      sha256 = "08nrgm8j7q49ds9r0k1cbn1jsxdv0if9bhi37szxpjz7ks7azyr9";
    };
  };
  "https://jcenter.bintray.com/com/android/tools/annotations/25.2.3/annotations-25.2.3" = {
    host = repositories.jcenter;
    path = "com/android/tools/annotations/25.2.3/annotations-25.2.3";
    type = "jar";
    pom = {
      sha1 = "109d6940f65b17f5281d6bc3f2462b8f304c8417";
      sha256 = "0smwn3m7xy8blg3glng7720vh47bfjnkhhzz4hq6qbh0nik4pdmf";
    };
    jar = {
      sha1 = "a9970f79003cbf4aaaf26a5590aca7066f209347";
      sha256 = "01mr9q7hg91rcbvn7kqz0g6cbm0krra76kiswf7s0jv94frjh5xz";
    };
  };
  "https://jcenter.bintray.com/com/android/tools/build/builder/2.2.3/builder-2.2.3" = {
    host = repositories.jcenter;
    path = "com/android/tools/build/builder/2.2.3/builder-2.2.3";
    type = "jar";
    pom = {
      sha1 = "92c46a19c24188825fb0517cd6dedac7aabea70d";
      sha256 = "0838z1iwk5kjh7sa4mycj38cc1d38vzpw5kwxhwrhag148frdmf1";
    };
    jar = {
      sha1 = "13e7339544e824a3a5f8ecff42173c013791578b";
      sha256 = "026kxz8lf59k1vkd9da3vcn41rzcrgwdff0ai88j58jsg1p5k6x6";
    };
  };
  "https://jcenter.bintray.com/com/android/tools/build/builder-model/2.2.3/builder-model-2.2.3" = {
    host = repositories.jcenter;
    path = "com/android/tools/build/builder-model/2.2.3/builder-model-2.2.3";
    type = "jar";
    pom = {
      sha1 = "5466f88e090faec542c5b5ea0d25743921dc8346";
      sha256 = "0vpsmjqi6vl4limpf6kjvz0nmbdg81szp97wxbsadd4m7swmqkxd";
    };
    jar = {
      sha1 = "eddf6035ce0a31651527b4c3cc239428e877c43a";
      sha256 = "1k00s7zrhvrhiq88m3k4k0nqwnlg69hhfppf3vbijr6dibnjhqd3";
    };
  };
  "https://jcenter.bintray.com/com/android/tools/build/builder-test-api/2.2.3/builder-test-api-2.2.3" = {
    host = repositories.jcenter;
    path = "com/android/tools/build/builder-test-api/2.2.3/builder-test-api-2.2.3";
    type = "jar";
    pom = {
      sha1 = "6470cca7298566e5ad6951b0c8e61b52e126f46d";
      sha256 = "0mzah6h5i2hnf1fi7cbdixvh0wc6b73y49ff8xi4qp67ifiwqvvh";
    };
    jar = {
      sha1 = "700079fc243c217dbd6250ac01d2d6210ca8a0d6";
      sha256 = "17p19jn26wbdcn4dhjpcn4nrg0f9240kg2xyffml6rdrvkwccr7p";
    };
  };
  "https://jcenter.bintray.com/com/android/tools/build/gradle/2.2.3/gradle-2.2.3" = {
    host = repositories.jcenter;
    path = "com/android/tools/build/gradle/2.2.3/gradle-2.2.3";
    type = "jar";
    pom = {
      sha1 = "88b4934c958cfe74ff5559c1a33707a562af59d2";
      sha256 = "0n923gbykymnya9jlyfvwbqhjdi0dy18yhvazvh6jmx5rmwpn5kw";
    };
    jar = {
      sha1 = "7b8f79621d95e3ce1e95c0852db14d9d7e1d1951";
      sha256 = "1f5bmkgd54sgs4nma6vqmgvp2gnran8q58fpr8mbyr30jnpcvycl";
    };
  };
  "https://jcenter.bintray.com/com/android/tools/build/gradle-api/2.2.3/gradle-api-2.2.3" = {
    host = repositories.jcenter;
    path = "com/android/tools/build/gradle-api/2.2.3/gradle-api-2.2.3";
    type = "jar";
    pom = {
      sha1 = "e14dde249b5ecc91e522a20a0638e05f86731e70";
      sha256 = "0a342sd1nvzz81qadnaimrw3yx35scaxljqj8vy8a3jr2w8bmigp";
    };
    jar = {
      sha1 = "9a45614f789d4aab624d2a61983263885f42b615";
      sha256 = "0dv81kmr4nrjs65macr4k8j890g747aiq7c02ca7hfxnywmmmyrw";
    };
  };
  "https://jcenter.bintray.com/com/android/tools/build/gradle-core/2.2.3/gradle-core-2.2.3" = {
    host = repositories.jcenter;
    path = "com/android/tools/build/gradle-core/2.2.3/gradle-core-2.2.3";
    type = "jar";
    pom = {
      sha1 = "bffbd58c81511f05115ef7e62d5c8b835478ede0";
      sha256 = "1p2xckdbd4qjn3drmfvs0xypkhnnh4rl410b49y508lhj2fp6xm9";
    };
    jar = {
      sha1 = "3a777b0626810e0ccdced7d750ac4b60c279616c";
      sha256 = "107pwwxddwb63jp2lvz4lhggh48c2ycaahry85vsmiim696fyl9w";
    };
  };
  "https://jcenter.bintray.com/com/android/tools/build/manifest-merger/25.2.3/manifest-merger-25.2.3" = {
    host = repositories.jcenter;
    path = "com/android/tools/build/manifest-merger/25.2.3/manifest-merger-25.2.3";
    type = "jar";
    pom = {
      sha1 = "cb2f6b4c552d96bbe3ac70c8472b149323ffa8f6";
      sha256 = "05d357pc8pv8mczfai9f7pjflybxg9kphgss18prby5wfl18wl8l";
    };
    jar = {
      sha1 = "d0212c507be4c38c39f4ee06a7df5a44f500ed3b";
      sha256 = "0dqqshpb27ygdwlr6d933xlsgdgi2b9qvr81pcqc0y5kp2wv9s4z";
    };
  };
  "https://jcenter.bintray.com/com/android/tools/build/transform-api/2.0.0-deprecated-use-gradle-api/transform-api-2.0.0-deprecated-use-gradle-api" = {
    host = repositories.jcenter;
    path = "com/android/tools/build/transform-api/2.0.0-deprecated-use-gradle-api/transform-api-2.0.0-deprecated-use-gradle-api";
    type = "jar";
    pom = {
      sha1 = "d2a89c5569f53a8c8adfe599ede88cb6f38a8a6e";
      sha256 = "1sr2ksrjzr9gv0y70w17l97x9a2anlv63lx7n803lgvxf2gig7fl";
    };
    jar = {
      sha1 = "085bee1acea9e27152b920746c68133b30b11431";
      sha256 = "16nfz9w0zpbbb0ghsab3gfp53imkr4d3gvhlgaz1m7v7w4d1bd78";
    };
  };
  "https://jcenter.bintray.com/com/android/tools/common/25.2.3/common-25.2.3" = {
    host = repositories.jcenter;
    path = "com/android/tools/common/25.2.3/common-25.2.3";
    type = "jar";
    pom = {
      sha1 = "962421b95641105a86edfffe0c60d40a1a7714e0";
      sha256 = "0gc2fk3frcfm3b8amnyymywzyq36cj80gg7i28cg9hh3ywd16vy8";
    };
    jar = {
      sha1 = "255aa01048bebb511d828c6a5fc668df13b8f39d";
      sha256 = "0prpydayr8acblgi2z1ib200i4bv7fjza8lfc3hxzb9vnlapli7a";
    };
  };
  "https://jcenter.bintray.com/com/android/tools/ddms/ddmlib/25.2.3/ddmlib-25.2.3" = {
    host = repositories.jcenter;
    path = "com/android/tools/ddms/ddmlib/25.2.3/ddmlib-25.2.3";
    type = "jar";
    pom = {
      sha1 = "4eaaa9c14e243bf3eab794fa85631a338b66bf74";
      sha256 = "1mi46px82jk0252nfsrvr95g90prn8xz328a6j8z2csgsnxldxa1";
    };
    jar = {
      sha1 = "2b66df9156f476b0ccee44b378cd09073118ff59";
      sha256 = "1nkjvsqbssy43c2x1v2g9v3flrjbaanli8zkym3gzlvjykz5pw11";
    };
  };
  "https://jcenter.bintray.com/com/android/tools/dvlib/25.2.3/dvlib-25.2.3" = {
    host = repositories.jcenter;
    path = "com/android/tools/dvlib/25.2.3/dvlib-25.2.3";
    type = "jar";
    pom = {
      sha1 = "2912069ba44d818d51a2b1bdef44974ffda4069c";
      sha256 = "099hb2p87nilb7pgpw8mvfhkvzr4ccr72zp380bg7ynkl2y76n6w";
    };
    jar = {
      sha1 = "5afd79f645811a98c0519141cc13900c659091a8";
      sha256 = "17lfq22x2d4sc2shg8yljadw2rsd4pfhygsnj94f7sb15a9aai15";
    };
  };
  "https://jcenter.bintray.com/com/android/tools/external/com-intellij/uast/145.597.4/uast-145.597.4" = {
    host = repositories.jcenter;
    path = "com/android/tools/external/com-intellij/uast/145.597.4/uast-145.597.4";
    type = "jar";
    pom = {
      sha1 = "dce2707f5ff2efca9c7f67de24e670322699590b";
      sha256 = "046zmm0fvxskb9vwa5rsd0k1hsxv1j5jgy31ys72dr8jpmqwpcs0";
    };
    jar = {
      sha1 = "6b430796bdb6563146affb34fb840c64e8d1d3b1";
      sha256 = "1k3vd204dmpa69cxws3lkxa158x169f6rd40yk1nbir0ylahxb8h";
    };
  };
  "https://jcenter.bintray.com/com/android/tools/external/lombok/lombok-ast/0.2.3/lombok-ast-0.2.3" = {
    host = repositories.jcenter;
    path = "com/android/tools/external/lombok/lombok-ast/0.2.3/lombok-ast-0.2.3";
    type = "jar";
    pom = {
      sha1 = "ac2e013f1621e1456de3ac77aeae0437237c736c";
      sha256 = "1gbljyqw5r2vc31dl1flclsvdias3049pdrc6dicizcbvph92qcc";
    };
    jar = {
      sha1 = "0528b6f8bde3157f17530aa366631f2aad2a6cf9";
      sha256 = "0vg8w757n8a8v6lafrg4xb9nl7dqw3x56p1qzfsp20j395p0vss5";
    };
  };
  "https://jcenter.bintray.com/com/android/tools/jack/jack-api/0.11.0/jack-api-0.11.0" = {
    host = repositories.jcenter;
    path = "com/android/tools/jack/jack-api/0.11.0/jack-api-0.11.0";
    type = "jar";
    pom = {
      sha1 = "ba7df9f0f474487a591dec42c58bee5b5c6b0075";
      sha256 = "170p7q6rbfjvs2avag290v1i560amqsyq2vswnqx1dh4fplld2vz";
    };
    jar = {
      sha1 = "ccda6afebd2b9cf60886c601ea561bba62c35c70";
      sha256 = "0v4a96vrsj6qsff6zdv18km3wqwvk9cyz7pgr4zrprxcnfnhvzra";
    };
  };
  "https://jcenter.bintray.com/com/android/tools/jill/jill-api/0.10.0/jill-api-0.10.0" = {
    host = repositories.jcenter;
    path = "com/android/tools/jill/jill-api/0.10.0/jill-api-0.10.0";
    type = "jar";
    pom = {
      sha1 = "19a922a794f06cee37cb49b19df12fe286d4a9a9";
      sha256 = "1k2pl81nx3175v1nhw8j4q59l5mvx59zzdwn3x8k2pr144ql794i";
    };
    jar = {
      sha1 = "7dfd6360ae4af1e171ec67b92e0cf065d59eef19";
      sha256 = "0vzn55g19plfx1bd3cn1kxdvzi88ra3j7bxgc08i667hymm918wq";
    };
  };
  "https://jcenter.bintray.com/com/android/tools/layoutlib/layoutlib-api/25.2.3/layoutlib-api-25.2.3" = {
    host = repositories.jcenter;
    path = "com/android/tools/layoutlib/layoutlib-api/25.2.3/layoutlib-api-25.2.3";
    type = "jar";
    pom = {
      sha1 = "e185d282ca20c45b5fd4309dc0849400b7457778";
      sha256 = "1fxa5hvpaxmhz3iiq583ix4p4f63za4b68k8cfzclmpwrzygmxj2";
    };
    jar = {
      sha1 = "ead9944caa7cba814184148efe69faf8896f4478";
      sha256 = "1a63n18l7fnmhydavmwyqxs1qjjvczzvngdc4rn3mqs3ni44jnv5";
    };
  };
  "https://jcenter.bintray.com/com/android/tools/lint/lint/25.2.3/lint-25.2.3" = {
    host = repositories.jcenter;
    path = "com/android/tools/lint/lint/25.2.3/lint-25.2.3";
    type = "jar";
    pom = {
      sha1 = "bf57cf10a46a4b0c8307f40bf11128958a9ef2c1";
      sha256 = "078rrpxrrljlp7dlmiypc1ff81gxh56yxr76h24p3as1db3rmv11";
    };
    jar = {
      sha1 = "aa03a3669f2913b9bc6f5f4fba4418f974e48cb7";
      sha256 = "0c95vndd4pq749hp4b8cg0rc2kib9a0m1ys704wpmg84pnapc3cy";
    };
  };
  "https://jcenter.bintray.com/com/android/tools/lint/lint-api/25.2.3/lint-api-25.2.3" = {
    host = repositories.jcenter;
    path = "com/android/tools/lint/lint-api/25.2.3/lint-api-25.2.3";
    type = "jar";
    pom = {
      sha1 = "a263b1dc3f7ce675b660634cdf0cb8a064503fcd";
      sha256 = "12cllgd4y7dmcxxbmmr4bm8rd52250kxr8iyy01azabmvswh1rk6";
    };
    jar = {
      sha1 = "fb7afa11dcda11d5bf0fcd3dcfec3e13ee921057";
      sha256 = "15hgxnknq77ys9j6sa6pg4aalwzwq943dlb9kmss4n51adc6a76b";
    };
  };
  "https://jcenter.bintray.com/com/android/tools/lint/lint-checks/25.2.3/lint-checks-25.2.3" = {
    host = repositories.jcenter;
    path = "com/android/tools/lint/lint-checks/25.2.3/lint-checks-25.2.3";
    type = "jar";
    pom = {
      sha1 = "79f5f3cd96eaefdbf80923e8771475472c9c57aa";
      sha256 = "1ygna0q6l84y51xssbilrkvwy081n14kdlhzkqskkkl3s2yny17d";
    };
    jar = {
      sha1 = "eae71c1f5ce54195dc821133e3a5df8145de8ff5";
      sha256 = "1vr4l9iafpz4bdy6k4s9cmzdsbxp74dqyskdl2ccflg8vswg383s";
    };
  };
  "https://jcenter.bintray.com/com/android/tools/repository/25.2.3/repository-25.2.3" = {
    host = repositories.jcenter;
    path = "com/android/tools/repository/25.2.3/repository-25.2.3";
    type = "jar";
    pom = {
      sha1 = "cd534aa93bce76ee719a81c7ad04cda432f774aa";
      sha256 = "190yrkr7lmzsnf0zpj4bs7yg6gdah541nbvdyzymjbg1n36mkxxj";
    };
    jar = {
      sha1 = "179dee8115834f40bd9b39675da3a0273174c3ca";
      sha256 = "0vqhlcv06kwfis6fqqjpzx12x56mnnqd9sy6sppmqnhphdvgjfh3";
    };
  };
  "https://jcenter.bintray.com/com/android/tools/sdk-common/25.2.3/sdk-common-25.2.3" = {
    host = repositories.jcenter;
    path = "com/android/tools/sdk-common/25.2.3/sdk-common-25.2.3";
    type = "jar";
    pom = {
      sha1 = "42ea7d181f07849b4e0a1ff4240ccd05c71c282c";
      sha256 = "1n4mrhy606723yyvkwy4kqcfqci9xlmjc9nynbyr57avkqia0kpi";
    };
    jar = {
      sha1 = "02c49ca3df5bb961473b096bab2a615a7cda50dc";
      sha256 = "1j35qhql8yiki0zgj0nw07kzfnzi9jw0vvb91jf02l6hmnx0k44f";
    };
  };
  "https://jcenter.bintray.com/com/android/tools/sdklib/25.2.3/sdklib-25.2.3" = {
    host = repositories.jcenter;
    path = "com/android/tools/sdklib/25.2.3/sdklib-25.2.3";
    type = "jar";
    pom = {
      sha1 = "3dd0fc724e8d9f0b7f45253ebcf7697461b12cb8";
      sha256 = "1dn0ri9a9p1zjcgjsj11d5avvn7avs6glj6fny5606aqwk258qax";
    };
    jar = {
      sha1 = "09f12cfc56b1df4e42fa2b73f9936b586b9a56a2";
      sha256 = "1l62x7c9n3zjwi5gar3scrb11yv6q4sbc7sh9pxsykwyn6dfs5zq";
    };
  };
  "https://jcenter.bintray.com/com/google/code/gson/gson/2.2.4/gson-2.2.4" = {
    host = repositories.jcenter;
    path = "com/google/code/gson/gson/2.2.4/gson-2.2.4";
    type = "jar";
    pom = {
      sha1 = "06252c690921ee1dc719594a5d4da1829194f8b3";
      sha256 = "106k9ynbhls8nkihxrhkj5033z7q2am6x1l98vffck4935flv65f";
    };
    jar = {
      sha1 = "a60a5e993c98c864010053cb901b7eab25306568";
      sha256 = "1yw7qszcw1dsh54q6wyksr5mbkz8mzs1q36hmjjn7qx9gk88qcn0";
    };
  };
  "https://jcenter.bintray.com/com/googlecode/juniversalchardet/juniversalchardet/1.0.3/juniversalchardet-1.0.3" = {
    host = repositories.jcenter;
    path = "com/googlecode/juniversalchardet/juniversalchardet/1.0.3/juniversalchardet-1.0.3";
    type = "jar";
    pom = {
      sha1 = "be6da8320adedafc712d645ddaaad00357b55408";
      sha256 = "0sq85z68pcf87j9vcis5garlxl325lz0q01skcm69kf76ndkjikq";
    };
    jar = {
      sha1 = "cd49678784c46aa8789c060538e0154013bb421b";
      sha256 = "0xjakmvlyl4i2lwb1prc19vx0mbbgpb6rhlxwx8vdf4kc68gwyvm";
    };
  };
  "https://jcenter.bintray.com/com/google/google/1/google-1" = {
    host = repositories.jcenter;
    path = "com/google/google/1/google-1";
    type = "jar";
    pom = {
      sha1 = "c35a5268151b7a1bbb77f7ee94a950f00e32db61";
      sha256 = "10by4ybrjnl8zwfg4ca74d0gcl4p9l7dzlfb9iwxw7m325xb2vfd";
    };
  };
  "https://jcenter.bintray.com/com/google/guava/guava/17.0/guava-17.0" = {
    host = repositories.jcenter;
    path = "com/google/guava/guava/17.0/guava-17.0";
    type = "jar";
    pom = {
      sha1 = "0f534dabee0b40b25715869c5e1287e38c7e1e4a";
      sha256 = "0nxpdkb27m770j0c4xlg7l34aj87h7qja7dbmqrcf99q1l0ic39a";
    };
    jar = {
      sha1 = "9c6ef172e8de35fd8d4d8783e4821e57cdef7445";
      sha256 = "1g7bhyvzsx61lrca01hvpivkdgjvgj1wy5qa0jwbdl0klq7ahdlc";
    };
  };
  "https://jcenter.bintray.com/com/google/guava/guava/18.0/guava-18.0" = {
    host = repositories.jcenter;
    path = "com/google/guava/guava/18.0/guava-18.0";
    type = "jar";
    pom = {
      sha1 = "2ec12f8d27a64e970b8be0fbd1d52dfec51cd41c";
      sha256 = "0dlqf4baf5h1j9b2a1i96n5l3i21vm7r3xync305sszpfqfxchz7";
    };
    jar = {
      sha1 = "cce0823396aa693798f8882e64213b1772032b09";
      sha256 = "16bgkzvk3sprn5rs9hfcpvz9vgyhy40zni1amffcxrfj0gygnr6n";
    };
  };
  "https://jcenter.bintray.com/com/google/guava/guava-parent/18.0/guava-parent-18.0" = {
    host = repositories.jcenter;
    path = "com/google/guava/guava-parent/18.0/guava-parent-18.0";
    type = "jar";
    pom = {
      sha1 = "5398932a9ef2828eb9fc4f01e8d6cac626c219d2";
      sha256 = "0rmia42xirzgk3r2h1syzs7n7ib1nv84yzh87yizcmz7jn4crb54";
    };
  };
  "https://jcenter.bintray.com/com/google/jimfs/jimfs/1.1/jimfs-1.1" = {
    host = repositories.jcenter;
    path = "com/google/jimfs/jimfs/1.1/jimfs-1.1";
    type = "jar";
    pom = {
      sha1 = "380866e1e495f899631b6e1d437e4b0a69e4faa3";
      sha256 = "0i3sgapm9r7wgmrm0qlb2hzarm6q6irfbjnz5x3ppw92v5f6xa7g";
    };
    jar = {
      sha1 = "8fbd0579dc68aba6186935cc1bee21d2f3e7ec1c";
      sha256 = "1pbx4lf1y24bgdfaf9bw9p0abnm7mlxhnlc7jfpk1af0swl8x0n4";
    };
  };
  "https://jcenter.bintray.com/com/google/jimfs/jimfs-parent/1.1/jimfs-parent-1.1" = {
    host = repositories.jcenter;
    path = "com/google/jimfs/jimfs-parent/1.1/jimfs-parent-1.1";
    type = "jar";
    pom = {
      sha1 = "2283f99a6aa73205190a20cfd35078e9f7d6cec9";
      sha256 = "1g96idyskcl3ryfc3fd5lq12ay5f4nbars3h528yzq2p3rsma5f7";
    };
  };
  "https://jcenter.bintray.com/com/google/protobuf/protobuf-java/2.5.0/protobuf-java-2.5.0" = {
    host = repositories.jcenter;
    path = "com/google/protobuf/protobuf-java/2.5.0/protobuf-java-2.5.0";
    type = "jar";
    pom = {
      sha1 = "d0b411e81d63761989f1329e8650ef27f6f77d25";
      sha256 = "0isgblny3w76jxiy7rdab3zg6d5f1sfw7vjal5y43al7mx97m0wx";
    };
    jar = {
      sha1 = "a10732c76bfacdbd633a7eb0f7968b1059a65dfa";
      sha256 = "0x6c4pbsizvk3lm6nxcgi1g2iqgrxcna1ip74lbn01f0fm2wdhg0";
    };
  };
  "https://jcenter.bintray.com/com/intellij/annotations/12.0/annotations-12.0" = {
    host = repositories.jcenter;
    path = "com/intellij/annotations/12.0/annotations-12.0";
    type = "jar";
    pom = {
      sha1 = "aaa1796465aa46f478176c06456397418b34d2b3";
      sha256 = "11lhm19lbcscmfrq1qpwacp6njamfbrm7mkw6apc1q02vkh2vy7s";
    };
    jar = {
      sha1 = "bbcf6448f6d40abe506e2c83b70a3e8bfd2b4539";
      sha256 = "0vgdfmihsggnbmcmrspf9ldll3knk5ayb43zc4pzx0709fqi7azq";
    };
  };
  "https://jcenter.bintray.com/commons-codec/commons-codec/1.4/commons-codec-1.4" = {
    host = repositories.jcenter;
    path = "commons-codec/commons-codec/1.4/commons-codec-1.4";
    type = "jar";
    pom = {
      sha1 = "393db4ae967c6e831025d432632d1f72f7108b01";
      sha256 = "13s0k9nv1zbmppf5b5fwc4j0506cgm061rzcdgki780v89lh1wzm";
    };
    jar = {
      sha1 = "4216af16d38465bbab0f3dff8efa14204f7a399a";
      sha256 = "06v3ccc5srj9w2v459i5f5rc7j37b1a24n52a5bh78gkfi62793a";
    };
  };
  "https://jcenter.bintray.com/commons-io/commons-io/2.4/commons-io-2.4" = {
    host = repositories.jcenter;
    path = "commons-io/commons-io/2.4/commons-io-2.4";
    type = "jar";
    pom = {
      sha1 = "9ece23effe8bce3904f3797a76b1ba6ab681e1b9";
      sha256 = "1wiikf78kr9k4pk68hb9jb9whrv19w8ir2kgxckad3wrrx3dvddj";
    };
    jar = {
      sha1 = "b1b6ea3b7e4aa4f492509a4952029cd8e48019ad";
      sha256 = "108mw2v8ncig29kjvzh8wi76plr01f4x5l3b1929xk5a7vf42snc";
    };
  };
  "https://jcenter.bintray.com/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1" = {
    host = repositories.jcenter;
    path = "commons-logging/commons-logging/1.1.1/commons-logging-1.1.1";
    type = "jar";
    pom = {
      sha1 = "76672afb562b9e903674ad3a544cdf2092f1faa3";
      sha256 = "1s2yqfrwxa3xg0l2mkczh29gcii3xcjnb8lwvmxbk2sf0mny3wnh";
    };
    jar = {
      sha1 = "5043bfebc3db072ed80fbd362e7caf00e885d8ae";
      sha256 = "0brngjgq24kk2c5qxzp3k6dcrzy7bdfdd1h1symb638zmly92vyf";
    };
  };
  "https://jcenter.bintray.com/com/squareup/javawriter/2.5.0/javawriter-2.5.0" = {
    host = repositories.jcenter;
    path = "com/squareup/javawriter/2.5.0/javawriter-2.5.0";
    type = "jar";
    pom = {
      sha1 = "d932f2476f65ecd95dcd6fd8c568b3f466f6a482";
      sha256 = "1c57k79i2dcyjm63k8xjjr1ck3i0i4hkwsa7k72y1xbc27qxgaz1";
    };
    jar = {
      sha1 = "81241ff7078ef14f42ea2a8995fa09c096256e6b";
      sha256 = "1w4p04j3z05k7ihb69pid3j4h4q8k0ipksp7rz9rgam01vxhkyzw";
    };
  };
  "https://jcenter.bintray.com/net/sf/jopt-simple/jopt-simple/4.9/jopt-simple-4.9" = {
    host = repositories.jcenter;
    path = "net/sf/jopt-simple/jopt-simple/4.9/jopt-simple-4.9";
    type = "jar";
    pom = {
      sha1 = "ea3cd0a93e4e8adc1cdadd544c9168bc5aa985a8";
      sha256 = "14lh0wb5jml18h2w45z0nibpa6xxkx6a4z9b9kq9hisbnbcf5xvs";
    };
    jar = {
      sha1 = "ee9e9eaa0a35360dcfeac129ff4923215fd65904";
      sha256 = "1xgjp8k4d258pab0p4zxz7n6x75m35lvh4vgnx6qcpsbjmp8bi96";
    };
  };
  "https://jcenter.bintray.com/net/sf/kxml/kxml2/2.3.0/kxml2-2.3.0" = {
    host = repositories.jcenter;
    path = "net/sf/kxml/kxml2/2.3.0/kxml2-2.3.0";
    type = "jar";
    pom = {
      sha1 = "8efa75f9cdc57687076b2125b1a098e6f42e737d";
      sha256 = "11d66hzaang99y3wkrqxzn2y2qgsg34jf3dvk5i9664m9rpn1kii";
    };
    jar = {
      sha1 = "ccbc77a5fd907ef863c29f3596c6f54ffa4e9442";
      sha256 = "1qixcdxqmw7ja9yhp0qw6g4y8jzjxwhk5igcwl6f3zd1g6gxsr7j";
    };
  };
  "https://jcenter.bintray.com/net/sf/proguard/proguard-base/5.2.1/proguard-base-5.2.1" = {
    host = repositories.jcenter;
    path = "net/sf/proguard/proguard-base/5.2.1/proguard-base-5.2.1";
    type = "jar";
    pom = {
      sha1 = "03e04f64ce189b9cfa7e08baae0d6f657a0204fd";
      sha256 = "1hrsv9fkjyn11sbrizqzlyppckr2hfc271j5vzlbx10ddrsfr0bg";
    };
    jar = {
      sha1 = "4f61348b4e7c943b85679dcb697f3a5fc3101921";
      sha256 = "1gzkcgg9aamxnda5vjzahaylv6dl0bbga55bi6vwkjsq7kbvsqzi";
    };
  };
  "https://jcenter.bintray.com/net/sf/proguard/proguard-gradle/5.2.1/proguard-gradle-5.2.1" = {
    host = repositories.jcenter;
    path = "net/sf/proguard/proguard-gradle/5.2.1/proguard-gradle-5.2.1";
    type = "jar";
    pom = {
      sha1 = "3f835379d233d3c8dc6076dcfc5e38d077b8ac4b";
      sha256 = "0q9d1ayqzcp1g7ypylk3xqnxii2q32dzq4km743f8cpaax7kspbg";
    };
    jar = {
      sha1 = "5e9956c050fd84fa043517e77c4c0ff175a6b002";
      sha256 = "1fy7i6ddbd1qjlkz9yahgnymx6ja6lg84sihiqagsrgk0m54rc7g";
    };
  };
  "https://jcenter.bintray.com/net/sf/proguard/proguard-parent/5.2.1/proguard-parent-5.2.1" = {
    host = repositories.jcenter;
    path = "net/sf/proguard/proguard-parent/5.2.1/proguard-parent-5.2.1";
    type = "jar";
    pom = {
      sha1 = "01bc4a2b3094f3e2112e61398e15bfb067841eed";
      sha256 = "01l30ijq5r8slw6jd9ya6v0lpyr09r3al1nd1a2wixfpmpd0499f";
    };
  };
  "https://jcenter.bintray.com/org/antlr/antlr/3.5.2/antlr-3.5.2" = {
    host = repositories.jcenter;
    path = "org/antlr/antlr/3.5.2/antlr-3.5.2";
    type = "jar";
    pom = {
      sha1 = "d6830744a9a30a9c0afebfb84a5fdd6cc7e9d4ab";
      sha256 = "1r12z9l1jjqs7ghmww2rjhqxsyr42ivizh6kjn3qbsrgcs05wph6";
    };
    jar = {
      sha1 = "c4a65c950bfc3e7d04309c515b2177c00baf7764";
      sha256 = "1ps3ws5p7hh38pa4iih0s3i469hgaxdhpqmggp9z785hrwm6rhss";
    };
  };
  "https://jcenter.bintray.com/org/antlr/antlr4/4.5.3/antlr4-4.5.3" = {
    host = repositories.jcenter;
    path = "org/antlr/antlr4/4.5.3/antlr4-4.5.3";
    type = "jar";
    pom = {
      sha1 = "9ecf07c69a057cb13cea8a153d242007f5cc8003";
      sha256 = "11334fj7p4yxfvqincdpn1fp4hp7vzqjrqaplxv2k9ysxqr4nkla";
    };
    jar = {
      sha1 = "f35db7e4b2446e4174ba6a73db7bd6b3e6bb5da1";
      sha256 = "1d2g3f5pyrabib54al6bwlqpfbkxd6limycnwrs5flfzrwwyfbd3";
    };
  };
  "https://jcenter.bintray.com/org/antlr/antlr4-master/4.5.3/antlr4-master-4.5.3" = {
    host = repositories.jcenter;
    path = "org/antlr/antlr4-master/4.5.3/antlr4-master-4.5.3";
    type = "jar";
    pom = {
      sha1 = "c7e4123f86c15b492adba2fc5377949c4ea43946";
      sha256 = "195jkdpq6v34aa1wd3hznlvzcch3x8s89wfgnvlrkm8awzapf620";
    };
  };
  "https://jcenter.bintray.com/org/antlr/antlr-master/3.5.2/antlr-master-3.5.2" = {
    host = repositories.jcenter;
    path = "org/antlr/antlr-master/3.5.2/antlr-master-3.5.2";
    type = "jar";
    pom = {
      sha1 = "0e9d18b3d8c228ff9786ee977f44800897fe15be";
      sha256 = "1mhv6gqiwdrgypibcwxxhbrfh25rqc1a06jlkfq0w4553r9imna2";
    };
  };
  "https://jcenter.bintray.com/org/antlr/antlr-runtime/3.5.2/antlr-runtime-3.5.2" = {
    host = repositories.jcenter;
    path = "org/antlr/antlr-runtime/3.5.2/antlr-runtime-3.5.2";
    type = "jar";
    pom = {
      sha1 = "af8ae5172f0c499d932d465673c9833c8777c1dd";
      sha256 = "09bzm8h181dj9jh53j19hf89k47lgw4sb9sa2bbjpcdq1chc5aa6";
    };
    jar = {
      sha1 = "cd9cd41361c155f3af0f653009dcecb08d8b4afd";
      sha256 = "0d47khwbkhvkzvk1h7hb7p6xjwnja3ijrfywrniyjf8gn7nchgyf";
    };
  };
  "https://jcenter.bintray.com/org/antlr/ST4/4.0.8/ST4-4.0.8" = {
    host = repositories.jcenter;
    path = "org/antlr/ST4/4.0.8/ST4-4.0.8";
    type = "jar";
    pom = {
      sha1 = "116663d33389525e932a4ff7adaf66eb06caf277";
      sha256 = "0z610q9vn39vf408p0110imzy08r6jgcl16llcxynx0iqzg9021w";
    };
    jar = {
      sha1 = "0a1c55e974f8a94d78e2348fa6ff63f4fa1fae64";
      sha256 = "0fvszknribdgm98s5rllj1sw0l2ayvh6in1zk6sv0x4z1k2apjjq";
    };
  };
  "https://jcenter.bintray.com/org/apache/apache/13/apache-13" = {
    host = repositories.jcenter;
    path = "org/apache/apache/13/apache-13";
    type = "jar";
    pom = {
      sha1 = "15aff1faaec4963617f07dbe8e603f0adabc3a12";
      sha256 = "07c4yg52q1qiz2b982pcsiwf9ahmpil4jy7lpqvi5m0z6sq3slgz";
    };
  };
  "https://jcenter.bintray.com/org/apache/apache/4/apache-4" = {
    host = repositories.jcenter;
    path = "org/apache/apache/4/apache-4";
    type = "jar";
    pom = {
      sha1 = "602b647986c1d24301bc3d70e5923696bc7f1401";
      sha256 = "152iri0kbrxir93w23b31045gpvh3g9rc37gxya27sx8dfi274wy";
    };
  };
  "https://jcenter.bintray.com/org/apache/apache/9/apache-9" = {
    host = repositories.jcenter;
    path = "org/apache/apache/9/apache-9";
    type = "jar";
    pom = {
      sha1 = "de55d73a30c7521f3d55e8141d360ffbdfd88caa";
      sha256 = "1p8qrz7swd6ylwfiv6x4kr3gip6sy2vca8xwydlxm3kwah5fcij9";
    };
  };
  "https://jcenter.bintray.com/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1" = {
    host = repositories.jcenter;
    path = "org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1";
    type = "jar";
    pom = {
      sha1 = "2fb3ea9182911315ee79aa2fb4853c7bdd347407";
      sha256 = "1f4z7dc667b0d07s1yfiqhvbhbj37q00ihyxphm0nlp82kdpl4qh";
    };
    jar = {
      sha1 = "a698750c16740fd5b3871425f4cb3bbaa87f529d";
      sha256 = "1gbzd7aang7xp3k98m3sbjs5d7nm6yqigg8znrncqvpq0dji7jjz";
    };
  };
  "https://jcenter.bintray.com/org/apache/commons/commons-parent/11/commons-parent-11" = {
    host = repositories.jcenter;
    path = "org/apache/commons/commons-parent/11/commons-parent-11";
    type = "jar";
    pom = {
      sha1 = "3f29657e1e3d6856344728ddbcf696477e943d59";
      sha256 = "0am014qph77cw2n596d9z8g1naf5a191199zi9di0q1l75pk1q5r";
    };
  };
  "https://jcenter.bintray.com/org/apache/commons/commons-parent/25/commons-parent-25" = {
    host = repositories.jcenter;
    path = "org/apache/commons/commons-parent/25/commons-parent-25";
    type = "jar";
    pom = {
      sha1 = "67b84199ca4acf0d8fbc5256d90b80f746737e94";
      sha256 = "1flhjyg2b14ch0wvsbimqli7vmpxim8yg54h6xkni1rf8i8fcyj6";
    };
  };
  "https://jcenter.bintray.com/org/apache/commons/commons-parent/33/commons-parent-33" = {
    host = repositories.jcenter;
    path = "org/apache/commons/commons-parent/33/commons-parent-33";
    type = "jar";
    pom = {
      sha1 = "a9bd6ae1e11cb313ec4a4c9bcd58c7a9ea60a5cd";
      sha256 = "1yzqvnngasa9bqqc0hw2yzqcckkmqzdcrbwx6xpi1rg2a89h3l2k";
    };
  };
  "https://jcenter.bintray.com/org/apache/commons/commons-parent/5/commons-parent-5" = {
    host = repositories.jcenter;
    path = "org/apache/commons/commons-parent/5/commons-parent-5";
    type = "jar";
    pom = {
      sha1 = "a0a168281558e7ae972f113fa128bc46b4973edd";
      sha256 = "0am0vbkyp6b6srwhvw52xkc4ghaj4kqn0ay26vgag06z1g035mlb";
    };
  };
  "https://jcenter.bintray.com/org/apache/httpcomponents/httpclient/4.1.1/httpclient-4.1.1" = {
    host = repositories.jcenter;
    path = "org/apache/httpcomponents/httpclient/4.1.1/httpclient-4.1.1";
    type = "jar";
    pom = {
      sha1 = "1468927fa5fbea4d3037422f45eb12cef173ba16";
      sha256 = "19z21zvaypyi1mg6vc3clmhmq6fq1ybng0pj0p7d95wa6kcigfmd";
    };
    jar = {
      sha1 = "3d1d918f32709e33ba7ddb2c4e8d1c543ebe713e";
      sha256 = "0la7iqy72w09h6z8h9s09bnac2xj0l05mm1ql5nbyyb6ib82drga";
    };
  };
  "https://jcenter.bintray.com/org/apache/httpcomponents/httpcomponents-client/4.1.1/httpcomponents-client-4.1.1" = {
    host = repositories.jcenter;
    path = "org/apache/httpcomponents/httpcomponents-client/4.1.1/httpcomponents-client-4.1.1";
    type = "jar";
    pom = {
      sha1 = "3e1c598ddde5619cc602d32fffdf34668be071a3";
      sha256 = "0lra0a51ir2x7ww44qq4hmcjvrrc843ll4qmfxz6sllmx7jq8lj7";
    };
  };
  "https://jcenter.bintray.com/org/apache/httpcomponents/httpcomponents-client/4.1/httpcomponents-client-4.1" = {
    host = repositories.jcenter;
    path = "org/apache/httpcomponents/httpcomponents-client/4.1/httpcomponents-client-4.1";
    type = "jar";
    pom = {
      sha1 = "ac363bbcf41af1153745f561aa0feac2b373a017";
      sha256 = "09wq25fxxrsj8c01313w9f4wr95mpz9l4dnykjdqsv4cg54bc5aj";
    };
  };
  "https://jcenter.bintray.com/org/apache/httpcomponents/httpcomponents-core/4.1/httpcomponents-core-4.1" = {
    host = repositories.jcenter;
    path = "org/apache/httpcomponents/httpcomponents-core/4.1/httpcomponents-core-4.1";
    type = "jar";
    pom = {
      sha1 = "166e36966c2cbd6c1867a6eded3f56d70958338c";
      sha256 = "1r2dyq3bgz1xamv3a167jd55in4z7vkd27zcvgh6s59xkkypyyag";
    };
  };
  "https://jcenter.bintray.com/org/apache/httpcomponents/httpcore/4.1/httpcore-4.1" = {
    host = repositories.jcenter;
    path = "org/apache/httpcomponents/httpcore/4.1/httpcore-4.1";
    type = "jar";
    pom = {
      sha1 = "28b423b7882a5c0d5b383903c6ea05d19b3c7c91";
      sha256 = "09vk7if9fwc6zsmr0912mgk57m23qwmmrx6ck6qgmjg973x6mj2g";
    };
    jar = {
      sha1 = "33fc26c02f8043ab0ede19eadc8c9885386b255c";
      sha256 = "1kr95c4q7w32yk81klyj2plgjhc5s2l5fh0qdn66c92f3zjqvqrw";
    };
  };
  "https://jcenter.bintray.com/org/apache/httpcomponents/httpmime/4.1/httpmime-4.1" = {
    host = repositories.jcenter;
    path = "org/apache/httpcomponents/httpmime/4.1/httpmime-4.1";
    type = "jar";
    pom = {
      sha1 = "a9e269c38cd5736d1db3a0e50adf87fafa8504a8";
      sha256 = "1lbkfv2qdkhsijfgswmn5gx15rs2hlz89wjk2rg6008hxidxjg6v";
    };
    jar = {
      sha1 = "9ba2dcdf94ce35c8a8e9bff242db0618ca932e92";
      sha256 = "1ahmkd6g4jw202ybwcsvs4z7ik9yph544fz4i9l4g2lf2ik9aqii";
    };
  };
  "https://jcenter.bintray.com/org/apache/httpcomponents/project/4.1.1/project-4.1.1" = {
    host = repositories.jcenter;
    path = "org/apache/httpcomponents/project/4.1.1/project-4.1.1";
    type = "jar";
    pom = {
      sha1 = "34c04480e3e97bccf10777c94651479b5ff55278";
      sha256 = "1v7qi1k2g9zbadaap6ln02p04hkika2nkbqigjik6kpmvx24vfr1";
    };
  };
  "https://jcenter.bintray.com/org/bouncycastle/bcpkix-jdk15on/1.48/bcpkix-jdk15on-1.48" = {
    host = repositories.jcenter;
    path = "org/bouncycastle/bcpkix-jdk15on/1.48/bcpkix-jdk15on-1.48";
    type = "jar";
    pom = {
      sha1 = "8fc7cecdba5ea3df0e29b659613dc21222a910fa";
      sha256 = "0z91vn29rq51r1p14kndr1p47kb7xc01smd1p2p44ba8mjdgyz5z";
    };
    jar = {
      sha1 = "28b7614b908a47844bb27e3c94b45b6893656265";
      sha256 = "0dxss10nkpwyg5w1hyp5yd1vrk8m9p2id2x1d1wxgap5nhv36isk";
    };
  };
  "https://jcenter.bintray.com/org/bouncycastle/bcprov-jdk15on/1.48/bcprov-jdk15on-1.48" = {
    host = repositories.jcenter;
    path = "org/bouncycastle/bcprov-jdk15on/1.48/bcprov-jdk15on-1.48";
    type = "jar";
    pom = {
      sha1 = "645352132b8d239bcc737c3c164f435af97cd9bb";
      sha256 = "10krh8bnjf2rypqqpfh4ik1jnqpbifcs4g8yakyb9hcf9bkjn4i9";
    };
    jar = {
      sha1 = "960dea7c9181ba0b17e8bab0c06a43f0a5f04e65";
      sha256 = "12129q8rmqwlvj6z4j0gc3w0hq5ccrkf2gdlsggp3iws7cp7wjw0";
    };
  };
  "https://jcenter.bintray.com/org/eclipse/jdt/core/compiler/ecj/4.5.1/ecj-4.5.1" = {
    host = repositories.jcenter;
    path = "org/eclipse/jdt/core/compiler/ecj/4.5.1/ecj-4.5.1";
    type = "jar";
    pom = {
      sha1 = "8d5f974f478c5861af01b7ec2ca9bc49e802b794";
      sha256 = "0irq5k7jsqaqvbvpnfg1f6vr8jzizp9hni5h0h3x53gjr0gr2d52";
    };
    jar = {
      sha1 = "bee1367ac12fb6a20b422ff8711ebeb4f0a42316";
      sha256 = "153jkqjiva6f31zzr7lp46vikvvg14pi9wg0qzkpf50r2gxi7wqr";
    };
  };
  "https://jcenter.bintray.com/org/jacoco/org.jacoco.build/0.7.5.201505241946/org.jacoco.build-0.7.5.201505241946" = {
    host = repositories.jcenter;
    path = "org/jacoco/org.jacoco.build/0.7.5.201505241946/org.jacoco.build-0.7.5.201505241946";
    type = "jar";
    pom = {
      sha1 = "623b238ca172a362ddfa78f09885cae6cfe95417";
      sha256 = "1f50lk9r5f9gq9asy1kx00clyymx35rwhcmiqwg4lqghm6l6xbv2";
    };
  };
  "https://jcenter.bintray.com/org/jacoco/org.jacoco.core/0.7.5.201505241946/org.jacoco.core-0.7.5.201505241946" = {
    host = repositories.jcenter;
    path = "org/jacoco/org.jacoco.core/0.7.5.201505241946/org.jacoco.core-0.7.5.201505241946";
    type = "jar";
    pom = {
      sha1 = "7d5f926b08e77b4d2ffbf5372494fbc825d34038";
      sha256 = "1hdlv1hi8i0syca2rwvcabwv5i0sk82scrri91cwgcmhx7hkcs4d";
    };
    jar = {
      sha1 = "1ea906dc5201d2a1bc0604f8650534d4bcaf4c95";
      sha256 = "0278fx30h9hs2wxbp12159ykiizbkgqc7z4bfk83hr4jja0svwgc";
    };
  };
  "https://jcenter.bintray.com/org/jacoco/org.jacoco.report/0.7.5.201505241946/org.jacoco.report-0.7.5.201505241946" = {
    host = repositories.jcenter;
    path = "org/jacoco/org.jacoco.report/0.7.5.201505241946/org.jacoco.report-0.7.5.201505241946";
    type = "jar";
    pom = {
      sha1 = "6d5e2f3835b4a3282265258e0262958a16554708";
      sha256 = "1nx5pllc28s8a71ivwa8b8jm9kbnnc2szqbmlhpji6pgs9ii1csr";
    };
    jar = {
      sha1 = "cb1ac5562a45c98cd7b774452f3e8b867b71cd65";
      sha256 = "1z5hd0a4ksmhamxizi7icbvv9nx9mxd2flizqb4dvxrs10pvl4bf";
    };
  };
  "https://jcenter.bintray.com/org/ow2/asm/asm/5.0.4/asm-5.0.4" = {
    host = repositories.jcenter;
    path = "org/ow2/asm/asm/5.0.4/asm-5.0.4";
    type = "jar";
    pom = {
      sha1 = "b4b92f4b84715dec57de734ff4c3098aa6904d06";
      sha256 = "043zq0mg31zx5p6hp7jg7zmiibim45c23cd6lx2zh9cbpl4c5cmq";
    };
    jar = {
      sha1 = "0da08b8cce7bbf903602a25a3a163ae252435795";
      sha256 = "0852x4qyrk9ykbw1a2ljwq41ljbw5gj7pg3q399049z6ibnihrl9";
    };
  };
  "https://jcenter.bintray.com/org/ow2/asm/asm-analysis/5.0.4/asm-analysis-5.0.4" = {
    host = repositories.jcenter;
    path = "org/ow2/asm/asm-analysis/5.0.4/asm-analysis-5.0.4";
    type = "jar";
    pom = {
      sha1 = "866a126a58622a9dff11a263c737a9009b0128ec";
      sha256 = "0p1jizbdgp70ch02f8v9ljns8lj6cdyajpx9dsynv6h67l6ndd8j";
    };
    jar = {
      sha1 = "51f5031331a56c462a3cc5126e21ab65958759a9";
      sha256 = "0h1li8yf0snizchyazbzp6mi5g4zsag1gv4wyh7kf3wxr2h756cv";
    };
  };
  "https://jcenter.bintray.com/org/ow2/asm/asm-commons/5.0.4/asm-commons-5.0.4" = {
    host = repositories.jcenter;
    path = "org/ow2/asm/asm-commons/5.0.4/asm-commons-5.0.4";
    type = "jar";
    pom = {
      sha1 = "39b727810d4c59d5d10f496307d750323fc03e95";
      sha256 = "0yd1dg2yg5pj8lqnkx4z0ddlflq0g113cl33rb19n7sg9pn14fb4";
    };
    jar = {
      sha1 = "5a556786086c23cd689a0328f8519db93821c04c";
      sha256 = "1bw6fiaq448zx9wmi8lnysxqfgk9npqpbqq3iyqm31mjj2i0wbsk";
    };
  };
  "https://jcenter.bintray.com/org/ow2/asm/asm-debug-all/5.0.1/asm-debug-all-5.0.1" = {
    host = repositories.jcenter;
    path = "org/ow2/asm/asm-debug-all/5.0.1/asm-debug-all-5.0.1";
    type = "jar";
    pom = {
      sha1 = "e536746490b031d435e1bfaa17a8d85f77973412";
      sha256 = "0zsmb8dfmk23b2zcw3sxfxa82h4g9ib9zll6p16vk0fa6xb5x7qz";
    };
    jar = {
      sha1 = "f69b5f7d96cec0d448acf1c1a266584170c9643b";
      sha256 = "0mzdg3cybprgpnry5ghby7k70pwf0vxp2sfvjq04niasa5dxwd27";
    };
  };
  "https://jcenter.bintray.com/org/ow2/asm/asm-parent/5.0.1/asm-parent-5.0.1" = {
    host = repositories.jcenter;
    path = "org/ow2/asm/asm-parent/5.0.1/asm-parent-5.0.1";
    type = "jar";
    pom = {
      sha1 = "fbd79905ab811db2c82640f58ddbd22807cfb29d";
      sha256 = "0brabhbilxzxaxzwf6hlsg9a41mjydg5nrr7zghn8hr48wnw114q";
    };
  };
  "https://jcenter.bintray.com/org/ow2/asm/asm-parent/5.0.4/asm-parent-5.0.4" = {
    host = repositories.jcenter;
    path = "org/ow2/asm/asm-parent/5.0.4/asm-parent-5.0.4";
    type = "jar";
    pom = {
      sha1 = "6c695dbc6aec0b88d14aef35513983f1d80a3ef4";
      sha256 = "0wjam9wl7l1bfd2n8qkigk0dq9z56l8z0pby38rknmr6yafmpw7x";
    };
  };
  "https://jcenter.bintray.com/org/ow2/asm/asm-tree/5.0.4/asm-tree-5.0.4" = {
    host = repositories.jcenter;
    path = "org/ow2/asm/asm-tree/5.0.4/asm-tree-5.0.4";
    type = "jar";
    pom = {
      sha1 = "38787224fd3bcf309f1f6ae676989483b001bac3";
      sha256 = "19i2jw14czb0imrsvcnjhhxlppihfmxqvqhida55wx9g1vmwi3gw";
    };
    jar = {
      sha1 = "396ce0c07ba2b481f25a70195c7c94922f0d1b0b";
      sha256 = "16c3bizs9wysmr785qj4m2q2x8sjgld6f3w48gkwvi7s6sl0yry3";
    };
  };
  "https://jcenter.bintray.com/org/ow2/ow2/1.3/ow2-1.3" = {
    host = repositories.jcenter;
    path = "org/ow2/ow2/1.3/ow2-1.3";
    type = "jar";
    pom = {
      sha1 = "f679d6639bfb209b0836a5e7cf09bfbcc1a41f06";
      sha256 = "1yr8hfx8gffpppa4ii6cvrsq029a6x8hzy7nsavxhs60s9kmq8ai";
    };
  };
  "https://jcenter.bintray.com/org/sonatype/oss/oss-parent/7/oss-parent-7" = {
    host = repositories.jcenter;
    path = "org/sonatype/oss/oss-parent/7/oss-parent-7";
    type = "jar";
    pom = {
      sha1 = "46b8a785b60a2767095b8611613b58577e96d4c9";
      sha256 = "0m4lallnlhyfj3z24ispxzwvsxzaznhw6zsmk4j74sibr5kqh7xm";
    };
  };
  "https://jcenter.bintray.com/org/sonatype/oss/oss-parent/9/oss-parent-9" = {
    host = repositories.jcenter;
    path = "org/sonatype/oss/oss-parent/9/oss-parent-9";
    type = "jar";
    pom = {
      sha1 = "e5cdc4d23b86d79c436f16fed20853284e868f65";
      sha256 = "0yl2hbwz2kn1hll1i00ddzn8f89bfdcjwdifz0pj2j15k1gjch7v";
    };
  };
}
